### ISSUE TITLE
SVG / vector graphics support

### ISSUE THREAD

**Issue by danboid** [pvcraven/arcade#100]
I've had a grep through the Arcade source and it seems that the sprite and drawing classes (or indeed arcade as a whole) don't have any support for using SVGs or any other vector graphics format.

Is vector graphics (SVG) support planned for arcade? Maybe this is a feature request for pyglet instead? It'd be great to be able to use synfig studio and Inkscape to create lossless, scalable graphics for use in Arcade projects.

**Comment by pauleveritt** [comment]
I just did a quick look in the pyglet-users google group and it appears that pyglet doesn’t support it. Here’s something from…uh….7 years ago: https://github.com/fathat/squirtle

Arcade is primarily concerned with setting up and drawing on an OpenGL context.

—Paul

**Comment by danboid** [comment]
I'm not sure what you mean by "primarily concerned with setting up and drawing on an OpenGL context". How does that relate to not supporting SVG? I realise arcade depends upon pyglet with depends upon OpenGL but OGL is something I associate with 3D rendering and not 2D sprites, whether they're bitmaps or vectors.

I think what you're saying is that unless pyglet gains SVG support, arcade won't support it either, right?

**Comment by pauleveritt** [comment]
I’ll let Big Paul answer definitively, but if pyglet doesn’t support it, arcade can’t.

—Paul

**Comment by pvcraven** [comment]
I'd love to see SVG support, but I'm not seeing it available in Pyglet. And I think it would take a fair bit of time to code from scratch.

**Comment by danboid** [comment]
I look forward to seeing this added to arcade one day!

**Comment by danboid** [comment]
This might help

https://blend2d.com/

**Comment by pvcraven** [comment]
I don't think we'll be able to add this anytime soon. Closing for now.
