### ISSUE TITLE
Drawing four lines of text will cause the program to slow down and choke in animations

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#102]
See the example code. Comment out any of the four lines of text that are drawn, and the program runs fast and fine. Draw all four lines, and the code gets slower and slower until it just crawls.
```
import arcade
import time

def draw_text(position_x, position_y):
    # Disable any line, and the program runs fast.
    # Draw all four, and the program gets slow
    arcade.draw_text("Test Line 1", position_x, position_y, (200, 200, 204), font_size=16, font_name="Impact")
    arcade.draw_text("Test Line 2", position_x, position_y - 20, (200, 200, 204), font_size=14, font_name="Impact")
    arcade.draw_text("Test Line 3", position_x, position_y - 40, (200, 200, 204), font_size=12, font_name="Impact")
    arcade.draw_text("Test Line 4", 300, 300, (255, 255, 255), font_size=9, font_name="Impact")


def on_draw(delta_time):

    # Start timer
    start_time = time.time()

    # Draw
    arcade.start_render()
    draw_text(on_draw.text_position, 775)

    # Reset text position
    on_draw.text_position = on_draw.text_position + 5
    if on_draw.text_position >= 1200:
        on_draw.text_position = 0

    # Stop timer and print time
    end_time = time.time()
    print(end_time - start_time)

on_draw.text_position = -100
print()


def main():
    # This is the function that will define the program.
    # Create a window
    arcade.open_window("Test", 1200, 800)
    arcade.set_background_color(arcade.color.BLACK)
    arcade.schedule(on_draw, 1 / 80)
    arcade.run()


# Call main function to to run program.
if __name__ == "__main__":
    main()
```

**Comment by pauleveritt** [comment]
I’ve gotten reasonably good at PyCharm’s profiler, want me to get some numbers?

—Paul

**Comment by pvcraven** [comment]
Sure! Kind of need to know why it slows down. What is the magic that happens on that fourth line of text.

**Comment by pauleveritt** [comment]
First, I can't make the code as-pasted slow down. I leave it running for 30 seconds and it is the same at the end as the beginning.

The profiler says it is spending 88.4% of the time in Label.__init__ and ultimately...no surprise, 46.9% of the time in render.

My game_api branch had an initial implementation of batching on labels. (I stopped on it because (a) I don't know if you like the api and (b) batching sprites means re-doing your sprite implementation). Want me to try the performance there to see how batching affects it?

**Comment by pvcraven** [comment]
Creating a pyglet label is expensive time-wise. Doing this for each frame is a waste. I'll make "create_text" and "render_text" so that we can easily store the text between frames.

**Comment by pauleveritt** [comment]
As a note, this was one of the (few) things I got working with batches on my experiment. Once I had re-done the Arcade API to be in charge of calling (instead of pyglet) it was straightforward.

—Paul

**Comment by pvcraven** [comment]
Drawing text in two steps speeds things up a lot. Example shown by:

https://pythonhosted.org/arcade/examples/drawing_text.html#drawing-text
