### ISSUE TITLE
API is inconsistent

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#103]
The code to open a window with a function:

`arcade.open_window("Drawing Example", 640, 480)`

The code to open a window by creating an object:

`window = arcade.Window(640, 480, "Drawing Example")`

They really should use the same order. Unfortunately fixing this would be API breaking.

**Comment by pauleveritt** [comment]
Yep, that actually bit me during a webinar.

—Paul

**Comment by sebnozzi** [comment]
My 2 cents: introduce a deprecation / migration path.

Start supporting the new way, let's say:

```python
window = arcade.Window("Drawing Example", 640, 480)
```
and make the implementation also work with the old order. But when done so, print a deprecation warning to stdout. Maintain this for one version or two, give users time to adapt their code. Then make the switch.
