### ISSUE TITLE
Possible enhancement of Easy Pull Down Menus for Windows

### ISSUE THREAD

**Issue by mruggerio** [pvcraven/arcade#104]
I am new to Python and learning pygame . I volunteer teaching children to program and am exploring options.  I love your site and will begin using it child next week..  When exploring your site is when I came across your Arcade Library.   But one thing I noticed in both pygame and Python Arcade Library is no easy pull down menu system.  Is there any thought to include this?  Something like AppJar? So that a menu system will easily be added to their games.
Thank You for time.
mruggerio #****

**Comment by pvcraven** [comment]
It would be nice to have some kind of UI support for Arcade, but nothing is being developed now. I'm hoping to do more development on Arcade this summer, and use the experience I'm getting by teaching students how to use it this winter semester.

**Comment by mruggerio** [comment]
Thanks for the reply.  I look forward to the coming development and thank you again for all your work on the API and the site!
