### ISSUE TITLE
Remove numpy

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#107]
Per @pvcraven it was an attempt at a 2d physics improvement that didn't finish and should be removed.

**Comment by johnlage** [comment]
@pvcraven Without removing numpy from the 2d physics improvement, a new installation can no longer function due to lack of numpy when loading the physics_engine_2d submodule.

**Comment by pvcraven** [comment]
I feel like Pymunk does the job so much better, that adding more instruction on how to use Pymunk would be a better choice to make. See https://github.com/pvcraven/arcade/blob/master/examples/pymunk_box_stacks.py and the other example in GitHub.

**Comment by johnlage** [comment]
CLARIFICATION: 'pip install arcade' and then 'import arcade' currently complains about a lack of numpy at the moment, due to the physics engine submodule trying to load it.

**Comment by pvcraven** [comment]
Fixed.
