### ISSUE TITLE
Inconsistent naming?

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#108]
The method used to update a sprite is "update". The method to update the application window is "animate". Should we use the same name for these?

**Comment by mobbarley** [comment]
Should be update for both. IMHO makes more sense.

**Comment by sebnozzi** [comment]
Does this mean that many examples are wrong? (I see `update` as being part of `arcade.Window` all over the place). Take a look at my first comment in issue #117.

**Comment by pvcraven** [comment]
No. Update is the correct function.  Animate is the old out of date
function.

Did you do a pip install --update arcade? What version do you get?

**Comment by sebnozzi** [comment]
@pvcraven That's right, I had not upgraded to the latest version.

This means this issue is resolved, then?
