### ISSUE TITLE
Improve coverage of unit tests

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#11]

**Comment by pvcraven** [comment]
Improved.

**Comment by pvcraven** [comment]
Code testing coverage has fallen and needs to be improved again.

**Comment by pauleveritt** [comment]
@pvcraven It looks like draw_commands.render_ellipse_filled and draw_commands.render_rectangle_filled are no longer used anywhere in the project.

**Comment by pauleveritt** [comment]
I just did #73 for draw_commands.py taking it from around 25% to around 85%.

**Comment by pvcraven** [comment]
Now at over 90%. Closing.
