### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mikemhenry** [pvcraven/arcade#12]
If you want to release the code into the public domain, you might want go with a more formal statement, like the one found [here](http://unlicense.org/). I'd be happy to make PR with the update.
On the subject of licenses, any particular reason you went for public domain over something like MIT? Or even something like LGPL?

**Comment by pvcraven** [comment]
I haven't even thought about the license yet. Maybe do MIT. LGPL might be hard if someone wants to release a game, and they modify the library. 

Paul Vincent Craven

**Comment by mikemhenry** [comment]
A good plus for LGPL is if someone wants to modify the library then the
community gets to benefit from the modifications. If someone wants to use
Arcade + their own stuff then they can do that without having to release
their code. I'm a fan of the MIT license.
