### ISSUE TITLE
Documentation: Pygame Comparison: mistake

### ISSUE THREAD

**Issue by Fornost461** [pvcraven/arcade#120]
On the documentation page [Pygame Comparison](http://pythonhosted.org/arcade/pygame_comparison.html), there is the following bullet point:

> - Command names are consistent. For example, to add to a sprite list you use the **add()** method, like any other list in Python. Pygame uses **append()**.

I believe that _add()_ and _append()_ should be swapped in the above, like this:

- Command names are consistent. For example, to add to a sprite list you use the **append()** method, like any other list in Python. Pygame uses **add()**.

**Comment by pvcraven** [comment]
Fixed on PyPi. It will take a while for the cloud to update for the arcade.academy site.

https://pythonhosted.org/arcade/pygame_comparison.html
