### ISSUE TITLE
Strange behaviour on Linux when creating window instance

### ISSUE THREAD

**Issue by r0the** [pvcraven/arcade#125]
Hi

Great library, thank you!

I'm using arcade with Thonny 2.1.11 / Python 3.6.1 on Debian 9. I noticed a strange behaviour: When creating a window directly, and not using the `arcade.open_window()` function, the screen start turing on and off. I suppose that the program wants to switch to a unsupported resolution.

So, this works:
```
arcade.open_window(800, 500, "Aufgabe 1")
arcade.run()
```

This doesn't work properly:

```
window = arcade.Window(800, 500, "Test")
arcade.run()
```
With some experimentation, I worked out that the problem must be caused by the missing `window.invalid = False` assignment that is used in the `arcade.open_window()` only.

So this works too:
```
window = arcade.Window(800, 500, "Test")
window.invalid = False
arcade.run()
```

Could you consider changing the library so that `window.invalid = False` is also executed when creating a window directly?

**Comment by pvcraven** [comment]
Closed, implemented in 1.2.2 which is now deployed on PyPi.
