### ISSUE TITLE
pypi release requires python 3.6 while repo says 3.5

### ISSUE THREAD

**Issue by irmen** [pvcraven/arcade#127]
Hi, when installing arcade using pip, it fails to run because of a python 3.6 dependency enforced:

    >>> import arcade
    The Arcade Library requires Python 3.6 or higher.

The code here on github however has a check for **3.5** instead.  Any chance to fix the lib on pypi?

**Comment by pvcraven** [comment]
Where is this github 3.5 check? I'm not sure what you are referring to.

**Comment by irmen** [comment]
the code here in the master branch does this check for python 3.5:

https://github.com/pvcraven/arcade/blob/master/arcade/__init__.py#L9

the wheel on pypi (which gets installed via pip) however contains a check against python 3.6 there.

**Comment by pvcraven** [comment]
Version 1.2 branch says it requires 3.6. Will be fixed in 1.2. Probably leave as-is with 3.5 for the 1.1 branch.

**Comment by pvcraven** [comment]
Closed, implemented in 1.2.2 which is now deployed on PyPi.

**Comment by irmen** [comment]
thanks, however, the documentation on http://arcade.academy/installation.html still says Python 3.5

**Comment by pvcraven** [comment]
Thanks, missed that. 

Docs should be updated tomorrow or whenever once the Amazon cloud syncs.
