### ISSUE TITLE
[info needed] How to handle knockbacks from/to AnimatedWalkingSprite

### ISSUE THREAD

**Issue by dzervas** [pvcraven/arcade#130]
This is not actually an issue with the lib, but I need some help on how to implement a "punch" from one player to another.

The punch from one player will knock the other player back. The "broadcaster" of course has to face the right side and the "receiver" will take different amount on force based on how close he is on the broadcaster and if he's above, beside or below him.

In my head, that's a fairly difficult problem. Care to help me with that? Or just help me break it down into pieces a bit...

**Comment by pauleveritt** [comment]
I’ve also wished for some networking. It would have to be integrated with the pyglet event loop. There is some code integrating the Twisted reactor with pyglet from a while back. At EuroPython I talked with the aiohttp guy about it. He looked at the Twisted-pyglet reactor code and said it would be reasonable to do in asyncio. But I think he meant for someone good at such things. :)

Ultimately this is more of a pyglet thing.

—Paul

**Comment by dzervas** [comment]
Oh, sorry, I described the problem I face completely wrong. By "broadcaster" I meant the player giving the punch and "receiver" the player receiving the punch. On the same local game, no networking involved. It's actually a game logic problem

Hint: I'm already working on that exact reactor. I hope I'll have networking working with arcade *SOME* day

**Comment by pauleveritt** [comment]
How do the two players communicate? Is it two processes (IPC) or two joysticks/keyboards on the same physical computer?

That is *very* exciting about the reactor. What library are you using?

—Paul

**Comment by dzervas** [comment]
2 keyboards on the same computer. but it could be an NPC receiving or giving the punch. Should i just alter the collider of the player giving the punch a bit? and if the face of the collision is the same with the face of the player giving the punch add some x or y velocity to the player getting the punch?

I've played a bit with twisted, but I might go with something of higher level, or just write a wrapper on my own.
My goal is to make the whole networking thing really easy to use even for an existing game. I don't know though, I have much research to do, let alone start implementing stuff.

**Comment by pvcraven** [comment]
I think you would need to get a bit of change_x/change_y velocity to the sprite. Alternatively you could use a full 2D physics engine like PyMunk. However I spent a lot of time with that and I don't think it works well for most platformers.

**Comment by pvcraven** [comment]
Not doing anything with this for now. PyMunk can handle this. We might make an "in between" engine that is better than the simple engine, but simpler than PyMunk.
