### ISSUE TITLE
Need better error message for calling "update" in the window without delta_time

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#133]
New programmers are often finding that if they derive from Window and create an update() method, they get an error because they forgot delta_time. The error they get isn't good. Make it better.

**Comment by pauleveritt** [comment]
update is called from pyglet.clock. Nothing we can do until we consider inversion of control, IMO.

**Comment by pvcraven** [comment]
I wonder if in the `__init__` we can test the method signature? I haven't done that in Python before and don't know how easy it is. I know in Java the reflection API would let you do it.

**Comment by r0the** [comment]
Maybe this could help: https://stackoverflow.com/a/23257774/8365557

**Comment by pauleveritt** [comment]
Ah yes, __new__, this is a good use for that technique.

—Paul

**Comment by pvcraven** [comment]
Closing, don't see a reasonable way to do this.
