### ISSUE TITLE
Rate of update not set by set_update_rate

### ISSUE THREAD

**Issue by christopburns** [pvcraven/arcade#137]
In my application, I want to have the update function do some complicated things and still maintain a regular interval. So I would like to set a slower update rate than 1/80, but it appears that the set_update_rate function is not working as I expect based on the documentation.

Here are the first three lines of my __init__ function:
super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT)
                                  
self.set_update_rate(UPDATE_RATE)

UPDATE_RATE is set to 1/20

I put a print statement in my update function to print delta_time, and here is a sample of what is printed:
0.05023312568664551
0.01657414436340332
0.016754865646362305
0.01661515235900879
0.06659650802612305
0.016652345657348633
0.01661205291748047
0.016669511795043945
0.016651391983032227
0.06658720970153809
0.016654253005981445

This means the update function is not being called every 1/20 seconds - often it is called more often and sometimes less often. What is going on?

**Comment by christopburns** [comment]
I have some more data. The call to arcade.start_render() is taking between 12 and 19 milliseconds most of the time so this appears to be the main area of slowdown in my environment. Is there a way to have the draw function run less often?

**Comment by christopburns** [comment]
Yet more info: by using a boolean argument stored in my class I've been able to stop the on_draw function from running, but update is still showing delta_time about 12-20 ms.

The current run time of my update function is around 100-200 microseconds, so it's not adding a lot of processing time.

**Comment by pvcraven** [comment]
I swear we had another bug report on this, but I can't find it.

**Comment by pvcraven** [comment]
Test code:

import arcade
    import time
    
    class MyApplication(arcade.Window):
    
        def __init__(self, width, height, title):
    
            # Call the parent class's init function
            super().__init__(width, height, title)
            arcade.set_background_color(arcade.color.ASH_GREY)
            self.last_call_time = time.time() * 1000
            self.set_update_rate(1/10)
    
    
        def on_draw(self):
            """ Called whenever we need to draw the window. """
            arcade.start_render()
            current_call_time = time.time() * 1000
            time_elapsed = current_call_time - self.last_call_time
    
            if time_elapsed > 0:
                fps = 1000 / time_elapsed
            else:
                fps = "?"
    
            self.last_call_time = current_call_time
    
            print(fps)
    
    
    window = MyApplication(640, 480, "Drawing Example")
    
    arcade.run()

**Comment by pvcraven** [comment]
Will be fixed with bug fix version 1.1.1.

**Comment by christopburns** [comment]
Do you know when that will be? And I should be able to get it directly from pip install --upgrade, right?

Thanks for your help!

**Comment by pvcraven** [comment]
1.1.1 is out. Try updating and let me know if it works better.

**Comment by christopburns** [comment]
Now I'm getting much more consistent delta_time in update. Thanks!

The only issue now is that it seems like the rendering is taking a long time. I'm not sure if it's my opengl or what but the start_render function takes a long time. Do you have any tips on speeding it up?

**Comment by pvcraven** [comment]
The start_render function should not take a long time at all. Not sure how you are timing it? An example would help. This would need to be a separate bug.

**Comment by pvcraven** [comment]
Fixed in 1.2 branch.
