### ISSUE TITLE
collision_radius

### ISSUE THREAD

**Issue by jjsanchemx** [pvcraven/arcade#139]
May  I have an example about **collision radius**, and how Works?
Thanks.

**Comment by pvcraven** [comment]
Not exactly sure what you are looking for. The collision radius is the first fast-check to see if an object is close enough that they MIGHT be colliding. Then we use a detailed point analysis.

**Comment by jjsanchemx** [comment]
Hi Paul.
the question is about arcade.sprite.Sprite.collision_radius
>>> import arcade
>>> empty_sprite = arcade.Sprite()
>>> empty_sprite.width = 3
>>> empty_sprite.height = 4
>>> empty_sprite.collision_radius
can i define a custom or alter the collision radius for a sprite?

**Comment by pvcraven** [comment]
If you want to change the collision boundaries, see how it is done with the ramp example: http://arcade.academy/examples/sprite_ramps.html#sprite-ramps

**Comment by pvcraven** [comment]
Note to self: Improve documentation around this for next release.

**Comment by pvcraven** [comment]
Closed, implemented in 1.2.2 which is now deployed on PyPi.
