### ISSUE TITLE
Standardize name of main class in examples

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#152]
Examples use MyApp, MyWindow, MyApplication as the child class to aracade.Window. Standardize this.

**Comment by pauleveritt** [comment]
Good point. If it were up to me, I'd use MyGame instead of application, window, etc. Focus on the fun goal.

**Comment by pvcraven** [comment]
Oh, I like that idea better than the MyWindow I was doing. Thanks.

**Comment by pvcraven** [comment]
Done and closed with release 1.2.3.
