### ISSUE TITLE
SpriteList.move() code needs to be cleaned up

### ISSUE THREAD

**Issue by Aareon** [pvcraven/arcade#169]
https://github.com/pvcraven/arcade/blob/c285e873cc2ad547a3a93281ff35d362c1e3fd22/arcade/sprite.py#L658

Here we set `dirty` equal to `self.vbo_dirty`. We then perform a check, maybe do some stuff with OpenGL or what have you, then at the end of it all, we reset `self.vbo_dirty` to the value in `dirty` when it doesn’t seem it’s been touched at all.

If it is a pointless modification, I’d suggest modifying the conditional to match 
```py
if not self.vbo_dirty:
    ...
```

**Comment by Aareon** [comment]
@pvcraven this does need your input

**Comment by pvcraven** [comment]
I think that was supposed to be code to move a set of sprites in the same direction. It would keep the same vertex buffer objects and move them all as one translate operation. I don't think that code was ever finished so now it is kind of a mess.

**Comment by Aareon** [comment]
Then maybe I can make a couple minor improvements to help with the process?

**Comment by pvcraven** [comment]
Sure!

**Comment by pvcraven** [comment]
Delivered as part of 1.3.0.
