### ISSUE TITLE
Request for transforms

### ISSUE THREAD

**Issue by jarav** [pvcraven/arcade#172]
## Enhancement request:

Support for coordinate transformations such as translations and rotations and general 2D matrix transformations as for example in [Processing](https://processing.org).

### What should be added/changed?
Ability to rotate drawing primitives and sprites about any point and not just about their centers.

### What would it help with?
We will be able to make more interesting animations in an easy way.

**Comment by jarav** [comment]
At the moment, using `rotate_point`, we can manually calculate the vertices of a rectangle and rotate it about any other point but if you want nested transformations it will help if they can be pushed  into and popped off a stack.

**Comment by pvcraven** [comment]
It isn't intuitive, but you can also use a shape_list:

import arcade
    
    SCREEN_WIDTH = 800
    SCREEN_HEIGHT = 600
    
    
    def make_shape():
    
        shape_list = arcade.ShapeElementList()
    
        # Shape center around which we will rotate
        center_x = 20
        center_y = 30
    
        width = 30
        height = 40
    
        shape = arcade.create_ellipse_filled(center_x, center_y, width, height, arcade.color.WHITE)
        shape_list.append(shape)
    
        return shape_list
    
    
    class MyGame(arcade.Window):
        """ Main application class. """
    
        def __init__(self):
            # Call the parent class initializer
            super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, "Shape Demo")
    
            self.shape_list = make_shape()
    
            # This specifies where on the screen the center of the shape will go
            self.shape_list.center_x = SCREEN_WIDTH / 2
            self.shape_list.center_y = SCREEN_HEIGHT / 2
    
            arcade.set_background_color(arcade.color.AMAZON)
    
        def on_draw(self):
            """
            Render the screen.
            """
    
            # This command has to happen before we start drawing
            arcade.start_render()
    
            self.shape_list.draw()
    
        def update(self, delta_time):
            """ Movement and game logic """
            self.shape_list.angle += 1
    
    
    def main():
        window = MyGame()
        window.setup()
        arcade.run()
    
    
    if __name__ == "__main__":
        main()

**Comment by jarav** [comment]
Thank you for that example. With the use of the `ShapeElementList` I was able to make a very simple animation of the earth going around the sun with the moon going around the earth. But I think it would have been easier with transforms. Here is my program:

```python
"""
Earth moon sun
"""

import arcade
   
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600

class MyGame(arcade.Window):
    """ Main application class. """

    def __init__(self):
        # Call the parent class initializer
        super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, "Earth Moon Sun")
        self.sun_x = SCREEN_WIDTH/2
        self.sun_y = SCREEN_HEIGHT/2
        self.earth_dist = 180
        self.moon_dist = 40
        self.sun_dia = 20
        self.earth_dia = 10
        self.moon_dia = 5

        self.moon_shape_list = arcade.ShapeElementList()
        moon = arcade.create_ellipse_filled(self.moon_dist, 0,
                self.moon_dia, self.moon_dia, arcade.color.WHITE)
        self.moon_shape_list.append(moon)

        self.moon_angle = 0
        self.earth_angle = 0

        self.earth_shape_list = arcade.ShapeElementList()
        sun = arcade.create_ellipse_filled(0, 0,
                self.sun_dia, self.sun_dia, arcade.color.YELLOW)
        earth = arcade.create_ellipse_filled(self.earth_dist, 0,
                self.earth_dia, self.earth_dia, arcade.color.BRIGHT_GREEN)
        self.earth_shape_list.append(sun)
        self.earth_shape_list.append(earth)

        self.earth_shape_list.center_x = self.sun_x
        self.earth_shape_list.center_y = self.sun_y
        self.moon_shape_list.center_x = self.sun_x + self.earth_dist
        self.moon_shape_list.center_y = self.sun_y
        arcade.set_background_color(arcade.color.DARK_MIDNIGHT_BLUE)

    def on_draw(self):
        """
        Render the screen.
        """

        # This command has to happen before we start drawing
        arcade.start_render()

        self.earth_shape_list.draw()
        self.moon_shape_list.draw()

    def update(self, delta_time):
        """ Movement and game logic """
        self.earth_angle += 1
        self.moon_angle += 5
        earth_center_x, earth_center_y = arcade.rotate_point(
                self.sun_x + self.earth_dist, self.sun_y,
                self.sun_x, self.sun_y, self.earth_angle)
        self.moon_shape_list.center_x = earth_center_x
        self.moon_shape_list.center_y = earth_center_y

        self.earth_shape_list.angle = self.earth_angle
        self.moon_shape_list.angle = self.moon_angle

def main():
    window = MyGame()
    arcade.run()


if __name__ == "__main__":
    main()
```

**Comment by pvcraven** [comment]
Thanks for the code sample. You are right, being able to do transforms would make code like that easier to do. I'll keep this on the todo list.

**Comment by JosiahBradley** [comment]
I'll look into implementing this starting with translations and rotations then moving onto arbitrary transform matrices.

**Comment by pvcraven** [comment]
Closing. Emphasis for a while will be more on the sprites side of things than drawing. I am open to PRs on drawing though.
