### ISSUE TITLE
background.jpg missing from sprite_rooms example

### ISSUE THREAD

**Issue by LexVerheesen** [pvcraven/arcade#173]
### Actual behavior:
FileNotFoundError: [Errno 2] No such file or directory: 'images/background.jpg'

### Expected behavior:
Working sprite_rooms example

### Steps to reproduce/example code:
Run "python -m arcade.examples.sprite_rooms" in a freshly created environment

**Comment by pvcraven** [comment]
Confirmed. Only png images are being copied into jpg folder.

**Comment by pvcraven** [comment]
Fixed with release 1.2.5.
