### ISSUE TITLE
Why are the instructions so basic?

### ISSUE THREAD

**Issue by LoganDark** [pvcraven/arcade#175]
Good god! I know what a terminal is, I already have Python installed, if someone does not know how to do those things, they aren't a programmer. For real. The instructions are so fucking basic..

`pip install PyObjC arcade`. That's it. That's all you need. Then, here, get this:

`import arcade`

Unbelievable, right? So complicated.

**Comment by pauleveritt** [comment]
I realize this is your experience. But step back and realize, not everyone is like you.

Specifically, Paul (a college professor) uses this library to teach introductory programming. To people who are...new to programming. People who don't think the terminal and Python installs are "fucking basic".

Speaking for myself, I'm glad he's doing it this way. But we'll see if others agree with you, and if so, crank it up a little.

**Comment by LoganDark** [comment]
Sorry I was so rude. But, if you're going to teach an introductory course, can you at least put it on a separate page? e.g. "Getting Started with Python Programming Using Arcade" or something.

**Comment by pvcraven** [comment]
It is easy for an experienced programmer to read basic instructions, but not the other way around. The target audience of this library includes both programmers, and new those learning.

**Comment by LoganDark** [comment]
I understand if you're targeting new learners, but if you want to introduce them to *Python*, and not just using this library *with* Python, I'd prefer if you keep the overly basic instructions on a separate page. But that's just my personal opinion. Obviously, nobody cares about my personal opinion, so I'll shut up now.
