### ISSUE TITLE
Should/can this be changed?

### ISSUE THREAD

**Issue by Aareon** [pvcraven/arcade#178]
https://github.com/pvcraven/arcade/blob/6827fcc69a90047dc0e290bd37f7da0b17864d28/arcade/sprite.py#L316

If this is always an integer and never a boolean, I think a better solution would be to use `if self.collision_radius == 0:`

**Comment by pvcraven** [comment]
I'm not really sure which is more Pythonic. Either is valid code. My thought in reading that was the wording was more like "if there isn't a collision radius" than comparing it to zero.

**Comment by Aareon** [comment]
It’s functional, but typically you check non-Boolean values with `==`.

**Comment by pvcraven** [comment]
Closing, unless someone can point me to a document that specifies an expected style for this, like PEP-8.
