### ISSUE TITLE
BUG on_mouse_press function doesn't trigger on mouse click. 

### ISSUE THREAD

**Issue by DavidEnds** [pvcraven/arcade#181]
The function on_mouse_press, when overwritten on a script, doesn't execute the code when the mouse is pressed.

Other functions like on_mouse_released do work as intented.

**Comment by pvcraven** [comment]
Example code?

**Comment by DavidEnds** [comment]
For example:

http://arcade.academy/examples/array_backed_grid.html#array-backed-grid

**Comment by pvcraven** [comment]
The example works fine for me. Are you working on a laptop with a touchpad? I've seen a few computers where that was an issue.

**Comment by DavidEnds** [comment]
Yes, is a laptop, but i`ll try with a optic mouse and same result

**Comment by pvcraven** [comment]
Interesting. The other two cases I've seen, worked with a plug-in mouse. This is hard for me to fix when I can't replicate it.

**Comment by DavidEnds** [comment]
I checked it in a desktop computer and same result

**Comment by dlanghorne0428** [comment]
I just ran into this problem today on the sprite_bullets example. It is a problem in pyglet 1.3.1 on Windows 10. They have a fix which I verified.
[](https://groups.google.com/forum/#!topic/pyglet-users/Eh4-pAa4_b4)

**Comment by pvcraven** [comment]
Ah, that explains a lot. Thanks.

**Comment by pvcraven** [comment]
Fixed with newest version of Pyglet.
