### ISSUE TITLE
Need support to disable anti-aliasing

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#187]
## Bug Report

From: https://www.reddit.com/r/pythonarcade/comments/85dl7w/how_to_disable_antialiasing/

I'd like to make a game with a pixel art feel. When I load my assets they get smoothed an anti-aliased. How do I deactivate the smoothing in arcade to keep the assets original pixels?

**Comment by pvcraven** [comment]
Used 16x16 pixel art from Aesprite. Didn't notice any issue. Need more info for bug replication.

**Comment by pvcraven** [comment]
Can't replicate.

**Comment by rb-dahlb** [comment]
Just saw this three days after it was closed, but posting here anyway. Not sure if it is related to anti-alias, but maybe: I have some small 64x64 tiles with dirt and grass, that I scroll from right to left in an attempt to make an "endless runner" game like the [Dino game in Chrome](chrome://dino/). But the grass flicker when the tile is scrolled, see video here: https://youtu.be/yJMti0ojvEg

The tile graphics:

![ground_0](https://user-images.githubusercontent.com/7920910/39753222-4a2811e0-52be-11e8-984d-b0e0818d366e.png)
![ground_1](https://user-images.githubusercontent.com/7920910/39753223-4a43659e-52be-11e8-860a-9d53715d8edb.png)
![ground_2](https://user-images.githubusercontent.com/7920910/39753224-4a62a4e0-52be-11e8-8246-523216008f02.png)

**Comment by pvcraven** [comment]
Interesting. I don't see flickering quite like that:

https://youtu.be/_ZwguNzCYbk

Do you have a code sample?

You might want to make sure everything lands on exact pixel boundaries. Don't scale the sprite. Don't move the viewport in fractional amounts. Keep everything on integer values.

**Comment by rb-dahlb** [comment]
Your example looks much more smooth yes, no flickering :)

I have looked at the example code for platforms and scrolling viewport, and maybe that's the strategy I should use. What I am doing currently is moving each tile, the viewport is static. The idea being that the ground potentially can change with random sequence of the tiles so the ground does not repeat itself.

Not sure if this is baked into the Sprite class, but I want the movement to be framerate independent, so I adjust the change_x relative to the delta_time each update. When I detect that the tile is beyond the left edge of the screen, I move the tile back to the right side.

Code is here: https://gist.github.com/rb-dahlb/810e553b2357676c1f821112587b888c

**Comment by pvcraven** [comment]
The update in the Window class gives you the time since last call. But the update in the Sprite does not. You'll need to create your own update that includes that data to get the info.

For performance reasons, I'd recommend moving the viewport, rather than each sprite. Moving the viewport is one call to the graphics card, where the other is a call for each sprite you've got.

**Comment by invalidenumerant** [comment]
I had an issue like this in Debian Linux running MATE.

The cause was that the viewport was somehow getting resized by 1 pixel wide and 1 pixel high, therefore all textures were being scaled by a very small percentage and they all looked fuzzy. I resolved by doing:

`self.set_viewport(0, SCREEN_WIDTH, 0, SCREEN_HEIGHT)`

in the __init__ event. When I run the same script in Windows, I can comment out that line, it makes no difference.

**Comment by einarf** [comment]
> I had an issue like this in Debian Linux running MATE.
> 
> The cause was that the viewport was somehow getting resized by 1 pixel wide and 1 pixel high, therefore all textures were being scaled by a very small percentage and they all looked fuzzy. I resolved by doing:
> 
> `self.set_viewport(0, SCREEN_WIDTH, 0, SCREEN_HEIGHT)`
> 
> in the **init** event. When I run the same script in Windows, I can comment out that line, it makes no difference.

This is fixed in 2.6 / development branch.

**Comment by invalidenumerant** [comment]
ok got it
