### ISSUE TITLE
version 1.3.3 appears to be broken on windows

### ISSUE THREAD

**Issue by jrheard** [pvcraven/arcade#199]
### Actual behavior:

on windows (not sure which version, sorry, making this bug report for a student i'm helping):

`pip install --user arcade`

`python`

`import arcade`

output:

```
Traceback (most recent call last):
  File "Y:\Comp Sci 3-4\Per3_evan_arcade\arcade_test_file.py", line 1, in <module>
    import arcade
  File "C:\Users\emrazik7366\AppData\Roaming\Python\Python36\site-packages\arcade\__init__.py", line 21, in <module>
    from arcade.sound import *
  File "C:\Users\emrazik7366\AppData\Roaming\Python\Python36\site-packages\arcade\sound.py", line 173, in <module>
    _load_sound_library()
  File "C:\Users\emrazik7366\AppData\Roaming\Python\Python36\site-packages\arcade\sound.py", line 61, in _load_sound_library
    pyglet.lib.load_library(path)
  File "C:\Users\emrazik7366\AppData\Roaming\Python\Python36\site-packages\pyglet\lib.py", line 158, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "C:\Program Files (x86)\Python36-32/lib/site-packages/arcade/Win32/avbin" not found.
```

### Expected behavior:

`import arcade` shouldn't raise an ImportErorr, and should just silently work successfully.

### Steps to reproduce/example code:

see above

extra context: "C:\Program Files (x86)\Python36-32/lib/site-packages/" doesn't seem to have an "arcade" directory.

version 1.3.2 works fine on these windows machines, so we'll just use that for now - but 1.3.3 reliably reproduces this issue on multiple windows machines in this classroom.

thanks!

**Comment by pvcraven** [comment]
Hm, looks like it is looking in a local-to-the-user folder. I've seen something similar with virtual environments.  I probably need it to fail silently if it can't find the library. 

Thanks for the report. I'm at PyCon now. Hope to fix it early next week.

**Comment by jgrantdev** [comment]
This problem occurs when you install arcade to the user site, it does not occur when you you are in a virtual environment.

We are asking pyglet to load avbin from the global site directory.

We should try to load it from the user-site directory, if an ImportError is raised then try to load it from the global site directory.

**Comment by kankri** [comment]
I just learned about Arcade and decided to give it a try, but stumbled into this issue with **version 1.3.4** on Windows:

```
>pip3 install --user arcade
>py -3 -c "import arcade"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\arcade\__init__.py", line 21, in <module>
    from arcade.sound import *
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\arcade\sound.py", line 193, in <module>
    _load_sound_library()
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\arcade\sound.py", line 70, in _load_sound_library
    pyglet.lib.load_library(path)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\pyglet\lib.py", line 158, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "C:\Program Files\Python36/lib/site-packages/arcade/Win64/avbin" not found.
```
Looking at the installed files shows:

```
>pip3.exe show --files arcade
Name: arcade
Version: 1.3.4
Summary: Arcade Game Development Library
Home-page: http://arcade.academy
Author: Paul Vincent Craven
Author-email: paul.craven@simpson.edu
License: MIT
Location: c:\users\user\appdata\roaming\python\python36\site-packages
Requires: pyglet, pillow
Files:
  ..\..\lib\python3.6\site-packages\lib\site-packages\arcade\lib\libavbin.10.dylib
  ..\..\lib\site-packages\arcade\Win32\avbin.dll
  ..\..\lib\site-packages\arcade\Win64\avbin.dll
  arcade-1.3.4.dist-info\INSTALLER
  arcade-1.3.4.dist-info\METADATA
  arcade-1.3.4.dist-info\RECORD
  arcade-1.3.4.dist-info\WHEEL
  arcade-1.3.4.dist-info\top_level.txt
  arcade\__init__.py
...
```
And indeed Arcade installs the dynamic libraries in completely wrong directories, the Mac library is in `%APPDATA%\python\lib\python3.6\site-packages\lib\site-packages\arcade\lib\libavbin.10.dylib` and the Windows DLLs are in `%APPDATA%\python\lib\site-packages\arcade\Win*\avbin.dll` instead of under `%APPDATA%\python\python36\site-packages\arcade`.

**Comment by pvcraven** [comment]
Next version will use ffmpeg for sound, and should work for both platforms. avbin has always been a headache, and coordinating with wherever pyglet expects the libraries hasn't been fun.

**Comment by pvcraven** [comment]
Closing.
