### ISSUE TITLE
A minor inconsistency in Window's methods' names; on_draw() vs update()

### ISSUE THREAD

**Issue by Mahi** [pvcraven/arcade#203]
Sorry if this is intended, but to me it felt like an accidental inconsistency between similar methods; the `arcade.application.Window` class has some methods with the `on_` prefix:
```
on_draw
on_mouse_visible
on_resize
```
But then there's the `update()` method that doesn't have the `on_` prefix, even though it seems very similar to `on_draw` in my opinion.

**Comment by pvcraven** [comment]
Yes, this is true. Adding to that:

* update() takes a delta time argument in the window class, but not the sprite class. The sprite class should.
* Probably need to do something other than `kill` for sprites, as `self.kill()` isn't necessarily cool with some people.
* There was something else this got me thinking of naming-related on the plane yesterday, but I can't remember it right now. Hopefully I will soon.

I think for backwards comparability we could just have both `update` and `on_update` work. The most work would be updating all the documentation to use the new name.

**Comment by pvcraven** [comment]
I'll leave updating the examples to `on_update` for a later release.

**Comment by pvcraven** [comment]
Closed with release of 1.3.4 on 28-May-2018.
