### ISSUE TITLE
Linux How to Compile documentation is invalid

### ISSUE THREAD

**Issue by jgrantdev** [pvcraven/arcade#204]
### Where is it located?
doc/how_to_compile.rst

### What is wrong with it?
The how to compile instructions for Linux involve makefast.sh and makedoc.sh which do not exist. The remaining make.sh command needs a ./ in front of make.sh.

**Comment by jgrantdev** [comment]
It looks like the Windows installation instructions reference batch files that do not exist. I am not in that environment so I am just correcting the Linux portion that I can test.

**Comment by jgrantdev** [comment]
Since I am back using Windows for a bit I want to update the How to Compile -> Windows section of the documentation.

I am going to wait until PR #220 is resolved since it will change the steps with the introduction of dev_requirements.txt.

**Comment by pvcraven** [comment]
Closing, should be fixed from back in April.
