### ISSUE TITLE
Sprite Class set_position Method Declared Twice

### ISSUE THREAD

**Issue by jgrantdev** [pvcraven/arcade#208]
The `set_position()` method of the `Sprite` class is declared twice with different signatures. 

https://github.com/pvcraven/arcade/blob/d5e51add5270aea66d9ca7d37c4a445cf64f9ce6/arcade/sprite.py#L227

https://github.com/pvcraven/arcade/blob/d5e51add5270aea66d9ca7d37c4a445cf64f9ce6/arcade/sprite.py#L302

If you read the documentation [here](http://arcade.academy/_modules/arcade/sprite.html) you would expect this to work:
```
my_sprite = arcade.Sprite()
my_sprite.set_position(10, 10)
```
However it results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: set_position() takes 2 positional arguments but 3 were given
```

The examples all work because they are directly changing `my_sprite.center_x` and `my_sprite.center_y` instead of using `set_position()`.

One implementation is modifying the member variables `center_x` and `center_y`. The other implementation is modifying the member list `_position`.

The `draw()` method is passing `center_x` and `center_y` to `draw_texture_rectangle()` so right now the only `set_position()` that would work is the one that is not accessible.

The following methods are all accessing `_position`
```
_get_center_x
_get_center_y
_set_center_x
_set_center_y
get_position
set_position
```

Is this a problem with trying to do the same thing two different ways or was center_x and center_y intended to be used to change the origin for the sprite?

The main documentation hides the first implementation of `set_position()`, but when you go to the view source part of the documentation I linked it is there.

I can fix this and update the examples, I am just unsure of what is intended.

**Comment by pvcraven** [comment]
I'd probably go with the former definition, even though Python will pick the second one.

The idea was for a faster atomic operation that assigned both x and y simultaneously. However in profiling I never found that to be much of a bottleneck, so I never used the operation.

Removing the first operation would be my suggestion for a fix. Hopefully no one is using it.

**Comment by jgrantdev** [comment]
@pvcraven I am confused about going with the former definition, but removing the first operation.

Removing `def set_position(self, new_position: (float, float)): ` makes the most sense to me.

**Comment by pvcraven** [comment]
Yes, let's do that. Remove `def set_position(self, new_position: (float, float))`. 

Do you want to do the pull request?

**Comment by jgrantdev** [comment]
Yes, I am still learning how to do this.
