### ISSUE TITLE
RFC: Path-based strings for static assets

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#209]
# Problem

Beginners paste some code into an editor and run it, but it breaks because they haven't downloaded the images. (Or don't have the right relative path.) Our tests break because you have to run the working directory from the right path.

# Proposal

In Pyramid we have a path-based language in static asset strings. Mainly, you can supply a prefix that includes the package name.

Python 3.7 has an API for this which is backported: http://importlib-resources.readthedocs.io/en/latest/

I propose that strings that look like this:

Sprite(‘examples/images/coin.png’)

...would continue to work as current. But this:

Sprite(‘arcade.examples.images:coin.png’)

...would load the image from the arcade package's examples/images directory (though it requires __init__.py all the way down.) Obviously this would work for any pip-installed package.

# Implementation

I plan to make a branch and a PR. It will be a whopper, so I'd prefer that we want to do this before I get started:

- A function which can pick things apart, with tests

- Find all the places we accept paths and route it through a function, then write tests, then change to the new behavior

- Find all places in docs and examples and convert

- Make sure the change is documented and obvious

**Comment by pvcraven** [comment]
Current functions that load files:
* `load_texture`
* `load_textures`

I'm not sure if you'd need to change any others.

Upcoming, `read_tiled_map` or whatever the final name is.

**Comment by pvcraven** [comment]
With the release of Kenney's toon characters, I'm really wanting to do this now. I'm thinking of prepending everything with `:resource:` but I'm open for other ideas:

```
load(":resource:characters/my_character.png")

**Comment by pvcraven** [comment]
Implemented in release 2.2.0
