### ISSUE TITLE
Make Arcade compatible with PyInstaller / cx_Freeze

### ISSUE THREAD

**Issue by r0the** [pvcraven/arcade#215]
## Enhancement request:
My students would like to create an executable file from their Arcade project. There are [various application bundlers available][1], but only two support Python 3.x: PyInstaller and cx_Freeze (py2exe seems to be abandoned).

I have experimented with both, but have had some issues:
- sound.py throws an exception because both PyInstaller and cx_Freeze have different implementations of the `site` module.
- I can't figure out how to bundle libav.dll with PyInstaller.
- With PyInstaller, resources can't be bundled in a single executable.

### What should be added/changed?
1. Make sound.py compatible with PyInstaller. PyInstaller uses virtualenv which doesn't provide `site.getsitepackages()`. I have a pull request that will fix that.
2. Make sound.py compatible with cx_Freeze, which returns an empty array from `site.getsitepackages()`.
3. Don't crash the application when libav cannot be loaded.
4. Support [loading of resources from PyInstaller bundles][2] using `sys._MEIPASS`.

### What would it help with?
Arcade projects could be bundled and distributes as executable files.

[1]: https://stackoverflow.com/a/14165470
[2]: https://stackoverflow.com/a/13790741

**Comment by pauleveritt** [comment]
Very good job for working on this. I have a related idea which could benefit from this and possibly contribute to it.

I don't want to hijack your ticket so I'll be terse and let you say whether I should describe a bit more.

# Arcade Collective

- A monorepo for games and a community that support them
- Docs, tests, PyPI installable packages, easy to get and run
- A way to teach people not just how to write games but also to work on open source community projects

I could imagine a PyInstaller binary for the Arcade Collective which allowed browsing, launching, and updating by bundling the .git directory.

**Comment by r0the** [comment]
I like your idea of an open source community to share projects. I think it would benefit the students to be able to share and try out the code of others.

I'd have more to say on this, but I think this goes in a different direction than what I intended with this issue. The goal is that my students can share their projects with friends with minimal effort. Just "here's the file, try it out."

Would you be so kind and open a separate ticket with you suggestion, so we can continue a discussion there?

**Comment by pauleveritt** [comment]
@r0the I wrote some ideas in #218 that hopefully explain a little more. I added a part covering what I think you discuss.

In some cases, I don't think "here's the code, try it out" will work. The code might have images that need to be in the right place with the right name, for example. So I proposed a way to package into a zip archive then open a zip archive.

But you're right, #218 isn't at all what you describe. I was just curious if there's a way to use your binary as a distribution point for a compendium of quality, maintained games -- the Achilles heel IMO of PyGame.

**Comment by pvcraven** [comment]
Using one of BeeWare's packages, we were able to create an installer for an Arcade game both on Windows and Mac. It worked rather well. There's a few things that need to be tuned to make it a smooth process though.

**Comment by pvcraven** [comment]
Briefcase was the name of the package: 
https://pybee.org/project/projects/tools/briefcase/

This needed a fix in Pyglet (removing 2to3 dependency) and a fix in briefcase. (I forget what exactly.) The Pyglet fix is slated for Pyglet's next release. I was thinking same for briefcase.

**Comment by r0the** [comment]
Thanks for pointing out Briefcase, but there seems to be little documentation yet.

**Comment by r0the** [comment]
I figured out how to package an Arcade game with PyInstaller on Windows 7 x64. I made an example in PR #227. The handling of avbin.dll is not trivial, see PR.

**Comment by pvcraven** [comment]
Closing for now.
