### ISSUE TITLE
RFC: Arcade Collective for community collection of game development and distribution

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#218]
This is just a placeholder for an idea/discussion.

# Summary

Create a GitHub repo/organization to collectively create and maintain games, with an easier system for distributing those games.

# Goals

- Central place for maintained games

- Easy to create a game, easy to get and run a game

- More advanced people do the infrastructure (CI, testing, Sphinx, PyPI) that more junior people can tap into

- Consistency across games (directory/file/symbol naming, styling, docs, etc.)

- Teach new developers the skills of participating in open source (tickets, branches, pull requests, docs, etc.)

- Perhaps ship platform binaries which allow browsing, running, and updating games in the collective

# Scenario

Mary downloads the windows binary for Arcol (Arcade Collective) and runs it. It has a listing of possible games and some other controls (update, about.) She selects Space Invaders and sees a panel with some info about the game and a button that says "Run". She clicks the button and a new pyglet 
window opens with the Arcade game running.

She decides this is fun and decides to hack on it. She clicks the "Clone" button and it makes a new subdirectory in the "Local" directory inside Arcol. She opens her editor, hacks on it a little, it works nicely.

She then clicks "Share" which makes a Python zip archive .zip file which she can email to someone. That person can use the "Open Zip" button in Arcol to consume it. The zip file has the code, static assets, etc. for her game and uses Python's zipimport to load.

Later she decides she wants this to be an ongoing game project in the Arcade Collective. She clones github.com/arcade/arcol and uses the Python binary and Pipenv installed in Arcol to quickly get the repository setup for development. She moves her clone into a new directory in the package. The Arcol developer docs give her some boilerplate for writing a basic test and a page in the docs. (Later we provide a cli for doing this.)

She follows the instructions to make sure tests still pass and documentation still builds and issues a PR. Others in the collective have a conversation with her about her code, until it is ready for acceptance. The PR is merged.

Mary then goes back to the Arcol GUI and clicks "Update". There's her game! She clicks Run and thinks how much fun that was.

# Implementation

- Arcol is a pyglet window with some GUI elements, built using PyInstaller

- It also has dulwich, a pure Python implementation of Git, to cover the tiny surface area of git we need to do a git pull for updating from the collective's repo

- The Arcol GUI can run games from (a) the git clone, (b) Python zipimport of local files, or (c) games authored in the Arcol GUI's data directory

**Comment by pvcraven** [comment]
Sounds interesting. So:

* A git organization. Which has a lot of git repos, each having their own directory structure.
* Some kind of GUI that can pull/clone each of the repos and run them?

Questions:

* How do we get the ball rolling? I can think of a few games that could be included from the start.
* On the flip side, how do we pick a minimum standard for including a game?

**Comment by pauleveritt** [comment]
I actually think the collective should be a monorepo. It's a good way to help others. Plus, it might be nice to install one package and get a bunch of runnable games (as long as the static assets don't get too huge.)

It would be nice to have a GUI that already had Python and could dramatically simplify getting the games. But I don't want to push @r0the into something unwillingly. This idea would still be a huge win over other projects even if you had to pip install arcol to consume the games.

To get the ball rolling, I don't want to make other take on new burdens. I could do some rough passes on it, taking some of your existing games. I could work out the docs, the "gallery" website, some guidelines, and let others review. But the big question would be: where is the repo? pvcraven/arcol is ok, but a "collective" implies a group.

**Comment by pvcraven** [comment]
"pythonarcade" sound ok as a name for the organization? I created it and added you as an admin.

I wouldn't mind if Arcade was in an organization, but I don't know how to move it to one without starting over again with all the 'stars' and such.

**Comment by r0the** [comment]
@pauleveritt I really like the idea of an Arcade community. I haven't the capacity to take on something big, but I'm happy to help out a bit, test, submit some games and such.

**Comment by r0the** [comment]
@pvcraven You can transfer a repo to an organization (Settings / Danger Zone / Transfer ownership). I tested it with my fork of Arcade, seems to work and keep the stars (well, only mine).

**Comment by r0the** [comment]
Another thought I have which goes in a similar direction is to integrate Arcade in an educational IDE. There are two that seem interesting to me:

- [Thonny](http://thonny.org/): Single-Exe installer, bundled Python 3.6, pip from UI. I use this one with my students.
- [Mu](https://codewith.mu/): Single-Exe installer, bundled Python, very simple GUI, different modes (micro:bit, Pygame, there should be an Arcade mode...)

Maybe Arcol could be integrated in one of these as a plugin. Or they could give hints as how to design Arcol.

**Comment by pauleveritt** [comment]
As someone that works for an IDE company, I probably need to be careful about that one. :)

More specifically, I don’t think integrating pyglet’s main loop into another GUI’s main loop would be trivial. 

—Paul

**Comment by pauleveritt** [comment]
Very good, thanks! I’ll make a repo and start doing some notes.

—Paul

**Comment by pauleveritt** [comment]
If you could contribute a couple of games, that would be a fantastic start. Even very simple things. Plus help while we’re setting the styles and such.

—Paul

**Comment by pvcraven** [comment]
Oh cool! Didn't know you could transfer ownership. Thanks r0the. When we figure out what we're doing, I'll probably do that.

**Comment by r0the** [comment]
@pauleveritt I've noticed before, but I didn't think about that now. I probaly don't need to tell you about IDE(a)s... :)

**Comment by pvcraven** [comment]
For now, we've got Facebook, Twitter, and Instagram accounts for showing off work. Closing until a project comes along we want to implement.
