### ISSUE TITLE
Add Player for background music.

### ISSUE THREAD

**Issue by zeziba** [pvcraven/arcade#229]
## Enhancement request:
Add the ability to play music in the background with little setup.
By doing this it will allow a user to add atmosphere to an environment easily and quickly.

### What should be added/changed?
Change the sound.py file so that it incorporates the above feature so that a user can easily add background music to an application.

### What would it help with?
It would make it easier to add music to a program allowing for a more user friendly experience.

I have already implemented this into my project as it allows for quick and easy use of background noise to add atmosphere to an environment.

Here is an example of what it will look like to add background music to a program.

```python
bg = arcade.Player()
bg.load_dir('resources\\sounds\\background')
bg.add('Game-Menu')
bg.play()
bg.volume(5)
```

The player I have made supports the queue system of pyglet and as such allows for multiple files to be loaded into memory for consumption. With the queue system there are features such as next, stop, looping, play, add, volume, clear, load_file and load_dir.

As I showed above I just use the file name without extension and can access the music file. Both a directory and single file can be loaded. After the files are loaded each file is put into a dictionary and associated with its filename allowing it to be accessed by name.

```python
# The files in the resources folder are wave1, wave2, wave3
bg = Player()
bg.load_dir("resources/")
print(bg.music)
#OUTPUT: ['wave1', 'wave2', 'wave3']
```

By doing the above it is easy to see what is loaded and makes it so each can be iterated over quickly and efficiently.

Overall this is a quality of life improvement that would allow a user to quickly and effectively add background music to a file.

**Comment by rb-dahlb** [comment]
I am also interested in this. A way to play different music based on game state for example, one piece of music for "start menu", one for "in game" and another for "game over screen".

Would need the API to be able to set a parameter for looping sound, so if you stay in the "start menu", the music just loops, and also an API call for stopping a sound currently playing, for example when the game is switching mode from "start menu" to "in game".

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html

**Comment by pvcraven** [comment]
Reopening- See issue #372. Should be possible now.

**Comment by pvcraven** [comment]
Example now posted: https://arcade.academy/examples/background_music.html#background-music
