### ISSUE TITLE
Add binary files to the package

### ISSUE THREAD

**Issue by dangillet** [pvcraven/arcade#241]
## Enhancement request:
Currently arcade setup.py adds the avbin binary files as data_files to some specific locations which should correspond to the platform specific site-packages directory.

There are problems with this method:

- If we install arcade in developer mode `pip install -e .` the binaries won't be discovered.
- If we try to make an executable with `briefcase`, `arcade` will be installed in a dedicated directory which will not be `site-packages`. Again the binaries won't be correctly discovered.

### What should be added/changed?

Making the binaries part of the package will allow `arcade` code to find them wherever the package is installed. I would have one directory - say `lib` - containing folders like `Win32`, `Win64` and `MacOS`. All the needed binaries for the relevant platform would be placed in those folder.

As an example, the code in `sound.py` would become:

```
from pathlib import Path

def _load_sound_library():
    """
    Special code for Windows so we grab the proper avbin from our directory.
    Otherwise hope the correct package is installed.
    """
    # lazy loading
    if not _load_sound_library._sound_library_loaded:
        _load_sound_library._sound_library_loaded = True
    else:
        return

    import os
    appveyor = not os.environ.get('APPVEYOR') is None

    this_dir = Path(__file__).parent

    import platform
    system = platform.system()

    if system == 'Windows':
        import sys
        is64bit = sys.maxsize > 2 ** 32

        if is64bit:
            path_global = this_dir / 'Win64' / 'avbin'
        else:
            path_global = this_dir / 'Win32' / 'avbin'

    elif system == 'Darwin':
        path_global = this_dir / 'MacOS' / 'libavbin.10.dylib'
        pyglet.options['audio'] = ('openal', 'pulse', 'silent')

    else:
        path_global = "avbin"
        pyglet.options['audio'] = ('openal', 'pulse', 'silent')

    path_global = str(path_global.resolve())
    pyglet.lib.load_library(path_global)

    pyglet.have_avbin = True
```
Note that I didn't handle the `appveyor` part as I'm not sure where it should be placed. I just want to give an example to get the conversation started.

### What would it help with?
Using arcade in develop mode and packaging arcade projects using Briefcase and other utilities such as PyInstaller.

Maybe there are very good reasons why the binaries are data_files and I fail to see them. :)

As a side-note, Python 3.7 will implement [importlib.resources](https://docs.python.org/3.7/whatsnew/3.7.html#whatsnew37-importlib-resources) for accessing resources in packages. There is a backport on PyPI for previous python versions. I believe this is worth considering, both for accessing binaries and for all necessary resources an application might need, such as images, sounds, ...

**Comment by pauleveritt** [comment]
Thanks so much for giving Arcade some of your time, we're lucky to have attention from you on this. I plan to kick the tires on your pyglet fork today. Sorry I didn't last week.

FWIW, I talked with @pvcraven at the PyCon Arcade sprint about a path-based language for loading static assets from packages, and then found about importlib.resources and the backport. My first limited try worked. So IMO it is safe to plan on that backport being included.

**Comment by pauleveritt** [comment]
On a different-but-related note...I'm working on a pytest mock that lets us unit test things without popping up a billion pyglet windows: https://github.com/pvcraven/arcade/blob/master/tests/unit/conftest.py#L5

I'm curious if you can think of an approach for mocking sound.

**Comment by pauleveritt** [comment]
Back to your enhancement proposal, it also covers the case I'm interested in:

- A new developer copies and pastes an Arcade example

- Runs it, but fails because the didn't download the images

**Comment by dangillet** [comment]
Thank you for the kind words!

> I'm curious if you can think of an approach for mocking sound.

What is it that you want to test which involve sounds? I would assume that pyglet does the heavy-lifting and you want to test if you're calling the right functions / methods. It would be easier if you could point me to an actual piece of code you'd like to test.

**Comment by pauleveritt** [comment]
> What is it that you want to test which involve sounds? I would assume that pyglet does the heavy-lifting and you want to test if you're calling the right functions / methods. It would be easier if you could point me to an actual piece of code you'd like to test.

sound.py has been a bug magnet, with lots of branching conditionals. Yes, I was thinking to mock the underlying pyglet calls and just make sure they were called with the correct arguments in various simulated platforms. As we find flaws on the Arcade, we write a test before fixing the bug.

—Paul

**Comment by pauleveritt** [comment]
@dangillet And almost immediately after I type that, here's an example: https://travis-ci.org/pvcraven/arcade/builds/393680631#L1147

I suspect a mock of pyglet sound would have triggered a unit test failure.

**Comment by pvcraven** [comment]
Closing.
