### ISSUE TITLE
Move over some doctests to unit tests in pytest

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#242]
## Enhancement request:

We have some tests in our documentation which aren't really about documentation. They were added there because all the tests were in doctest.

### What should be added/changed?

We should identify which tests we want to keep as part of the documentation effort and I will move the rest to unit tests with a mock pyglet (hopefully.)

As part of this ticket, I'll make sure the resulting coverage on unit tests meets what we'd like.

### What would it help with?

- Fix AppVeyor
- Make documentation better by removing extraneous noise
- Tests will run a LOT faster by not popping up a window on every test
- "Unit" tests will actually test a unit

**Comment by zeziba** [comment]
Along with this enhancement I also purpose all doc strings include important information about the use of the function/method in question.

An example of this is as follows
```python
import arcade
help(arcade.play_sound)
```

This outputs

```python
Help on function _play_sound_win in module arcade.sound:
_play_sound_win(sound:Type[pyglet.media.sources.base.Source])
    Play a sound on Windows
```

As can be clearly seen it tells me that I can play a sound on windows. The help should tell me in this specific case how to use it and what file types it does support so the user is not surprised they cannot load a ```.whatisthis``` file into the loader.

In that vein of changing the doc tests I can help write the doc strings and unit tests if you would like. Just let me know if and what if anything is needed to change.

**Comment by pauleveritt** [comment]
You're right that docstrings make for a good place to put that information. However, docstrings are usually aimed at the users of a function. They aren't going to use _play_sound_win (the leading underscore shows that) directly. Plus, the name of the function pretty clearly indicates its use. Finally, I'm not sure, but I think help(arcade.play_sound) will return the docstring for play_sound, not the function returned by play_sound.

**Comment by zeziba** [comment]
The doc string is what I placed above, it does tell of the parent function. It is possible to override this behavior though so it will look like

```
Help on function play_sound in module arcade.sound

play_sound(...)
    play_sound(sound:Type[pyglt.media.sources.base.Source]) -> None
    Play a sound using operation system dependent libraries. Windows uses avbin which is provided, MacOs uses cocoa and Linux uses GStreamer.

    {INSERT Docstring for version specific playsound for usage and other important information}

    Formats that are accepted are
        Windows: .wav, .oog, .mp4
        MacOs(Darwin): .wav
        Linux: .wav, .oog, .mp4 # Not sure about this one
```

This is how the doc string should be when help is used on the function. It is as succinct as possible without any usage examples. The other benefit is if we use automated document creation tools it will pull the doc string to build and in that way each doc string should provide a very abstract detail about the function/method in question. 

Again let me know if you want any help with this.

**Comment by zeziba** [comment]
Also, before I forget and to show you what I mean

```python
import arcade

print(arcade.play_sound.__name__)
# outputs: _play_sound_win
print(arcade.play_sound.__doc__)
# outputs: "\nPlay a sound on Windows\n"
```

This can be changed of course

```python
from arcade import play_sound

# add this to change it
from arcade import play_sound

# add this to change it
play_sound.__name__ = "play_sound"
play_sound.__doc__ = """
    play_sound(sound:Type[pyglt.media.sources.base.Source]) -> None
    Play a sound using operation system dependent libraries. Windows uses avbin which is provided, MacOs uses cocoa and Linux uses GStreamer.

    {}

    Formats that are accepted are
        Windows: .wav, .oog, .mp4
        MacOs(Darwin): .wav
        Linux: .wav, .oog, .mp4 # Not sure about this one
""".format(play_sound.__doc__)
```

This then outputs what is expected

```python
help(play_sound)
```

Output
```
play_sound(sound:Type[pyglet.media.sources.base.Source])
    play_sound(sound:Type[pyglt.media.sources.base.Source]) -> None
    Play a sound using operation system dependent libraries. Windows uses avbin which is provided, MacOs uses cocoa and Linux uses GStreamer.
    
    
    Play a sound on Windows
    
    
    Formats that are accepted are
        Windows: .wav, .oog, .mp4
        MacOs(Darwin): .wav
        Linux: .wav, .oog, .mp4 # Not sure about this one
```

It is imperative to replace the name and doc string of the function if the parent function is not needed to be seen.

**Comment by pvcraven** [comment]
Many doc tests have been moved to unit tests, but the current unit test are not working well at all for some reason.

**Comment by pvcraven** [comment]
PyTest working ok now in 2.0.6
