### ISSUE TITLE
sound._Player.play generates AttributeError in pyglet _get_queue_source

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#243]
## Bug Report

The doctest for arcade.sound._Player is generating [an exception on Travis](https://travis-ci.org/pvcraven/arcade/builds/393680631#L1147).

### Actual behavior:

```
    m = pyglet.media.StaticSource(self._music[music])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pyglet/media/sources/base.py", line 397, in __init__
    source = source._get_queue_source()
AttributeError: 'str' object has no attribute '_get_queue_source'
```

### Expected behavior:

pyglet.media.StaticSource(self._music[music]) should be passing in a pyglet Source instance instead of a self._music[music]  string.

### Steps to reproduce/example code:

Run the doctests as described in .travis.yml:

```
$ pytest --cov=arcade -m 'not not_ci' arcade
```

**Comment by pauleveritt** [comment]
@zeziba I think this one is yours.

**Comment by zeziba** [comment]
I had this 
```self._music = {"{}".format(name): load_sound(os.path.join(name))}``` 
which is now 
```self._music = {"{}".format(name): load_sound(file)}```
It was trying to use the string name of the file vs the actual sound file. I will push it after I rewrite the test to check for version and display the appropriate warning as that is throwing the warnings for not being able to load a file as I intended but I didn't have it in the doctest.
