### ISSUE TITLE
Add support for window resizing

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#25]
Right now Pyglet supports window resizing, but not Arcade. Should be straight forward.

**Comment by pauleveritt** [comment]
@dlazarus Did you have any luck on this?

**Comment by pauleveritt** [comment]
As a note, here are the [pyglet docs](http://pyglet.readthedocs.io/en/latest/programming_guide/windowing.html#size-and-position) that cover window sizing. It's going to be an interesting question about how much functionality we expose, and how to do so.

**Comment by pauleveritt** [comment]
#74 implements some aspects of resizing:

- application.Window and draw_commands.open_window both allow a resizable:bool to be passed in, which is then passed into the pyglet.window.Window constructor
- arcade.Window.set_minimum_size and set_maximum_size methods which raise ValueError if the window isn't resizable
- arcade.Window.set_size which, like pyglet, forces a size change programmatically
- A stub on_resize method
- doctests

I'll use the other ticket to write an example that uses it.

**Comment by pauleveritt** [comment]
Hmm, the doctest fails in Travis but not for me locally (though I'm running 3.6b3). I'll re-open this.

**Comment by pvcraven** [comment]
Implemented in current code-base for 1.2
