### ISSUE TITLE
Mouse coordinates and custom viewport

### ISSUE THREAD

**Issue by Hudler** [pvcraven/arcade#250]
In my app I have drawn a map and later I wanted some margin around the border. I thought I can use set_viewport instead of redrawing the whole app.

The problem is, that the map coordinates obtained on mouse press do not correspond to the original coordinates even when counting in the margin.

In the following example, when I click on the bottom left corner of the rectangle, I get coordinates (25,25) (or (0,0) after subtracting the margin). Then when I click on the bottom right corner, I expect coordinates (1075,25) but I get (1125,25). According to this, the line lengthens by 50 units after using set_viewport.

How is this possible and what can I do to fix this?

```
import arcade

D1 = 680
D2 = 1050
MARGIN = 50

class MyWindow(arcade.Window):

    def __init__(self):
        super().__init__(D2+2*MARGIN, D1+2*MARGIN, "MyWindow")
        
    def on_draw(self):
        arcade.start_render()      
        arcade.set_viewport(-MARGIN/2, D2+MARGIN/2, -MARGIN/2, D1+MARGIN/2)
        point_list = ((0, 0),
                      (0, D1),
                      (D2, D1),
                      (D2,0))
        arcade.draw_polygon_outline(point_list, arcade.color.WHITE, 3)
    
    def on_mouse_press(self, x, y, button, modifiers):
        print(x,y)
        print(x-MARGIN/2,y-MARGIN/2)

if __name__ == '__main__':
    window = MyWindow()
    arcade.run()
```

**Comment by dangillet** [comment]
Your problem is that you set the window size too large compared to the viewport.

Your window size is defined by `D2+2*MARGIN, D1+2*MARGIN`. So you add `MARGIN` twice. We expect to have a viewport which can encompass this whole area. But for the viewport you only use half the `MARGIN` on each side.

Here is a proposal:

```
import arcade

D1 = 680
D2 = 1050
MARGIN = 50


class MyWindow(arcade.Window):

    def __init__(self):
        super().__init__(D2 + 2 * MARGIN, D1 + 2 * MARGIN, "MyWindow")

    def on_draw(self):
        arcade.start_render()
        point_list = ((0, 0),
                      (0, D1),
                      (D2, D1),
                      (D2, 0))
        arcade.set_viewport(-MARGIN, D2 + MARGIN, -MARGIN, D1 + MARGIN)
        arcade.draw_polygon_outline(point_list, arcade.color.WHITE, 3)

    def on_mouse_press(self, x, y, button, modifiers):
        print(x, y)
        print(x - MARGIN, y - MARGIN)


if __name__ == '__main__':
    window = MyWindow()
    arcade.run()
```

Hope it helps. :smile:
