### ISSUE TITLE
read_tiled_map should support a tileset image

### ISSUE THREAD

**Issue by MushroomMaula** [pvcraven/arcade#252]
## Bug Report
`arcade.read_tiled_map()` is not able to get the tiles if they are stored in a tileset and not in the map file
### Expected behavior:
`read_tiled_map()` should support getting the tiles from a tileset
should be pretty easy to implement, the only problem I see is when I call `arcade.read_tiled_map('maps/map.tmx')` and the tileset is in the maps dir
the source in the xml will be `'tiles.tsx'` and not `'maps/tiles.tsx'` which leads to an error when trying to parse the file

**Comment by MushroomMaula** [comment]
This is what i came up with
```python
        # FILE: arcade.read_tiled_map()
        # LINE: 83
        # ISSUE: #252 
        # checking if tiles are inside the map file
        # checking if tileset is given
        if not tile_tag_list and tileset_tag.attrib.get("source") is not None:

            path_to_tile_set = tileset_tag.attrib.get("source")

            import os
            directory, file = os.path.split(filename)
            # check if map file in diffrent directory
            if directory:
                # if so we need to add the directory to the tileset source
                path_to_tile_set = os.path.join(directory, path_to_tile_set)
            # if not, path_to_tile_set doesnt need to be changed

            # read and parse tileset
            tile_set_tree = etree.parse(path_to_tile_set)
            tile_set_root = tile_set_tree.getroot()
            # Grab each tile
            tile_tag_list = tile_set_root.findall("tile")
```

**Comment by akapkotel** [comment]
How did you make it work? It is not working for me, I’am still receiving an error of passing wrong key to the my_map.global_tile_set - probably I do not paste the path in the proper place. Should I paste these lines after line 83 of read_tiled_map() or somewhere else?

**Comment by pvcraven** [comment]
Support will be in alpha 3 release.

**Comment by pvcraven** [comment]
Support is built into Arcade for Tiled maps now.

**Comment by pdblood** [comment]
Using the latest master branch code, I also still get a key error when trying to load a tmx file:

`Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\arcade-master\arcade\examples\sprite_move_animation_test_map.py", line 444, in <module>
    main()`

  `File "C:\Python37\Lib\site-packages\arcade-master\arcade\examples\sprite_move_animation_test_map.py", line 439, in main
    window.setup()`

  `File "C:\Python37\Lib\site-packages\arcade-master\arcade\examples\sprite_move_animation_test_map.py", line 371, in setup
    my_map = arcade.read_tiled_map("Forest Map.tmx", SPRITE_SCALING)`
 
 `File "C:\Python37\lib\site-packages\arcade-2.0.0b3-py3.7.egg\arcade\read_tiled_map.py", line 231, in read_tiled_map
    grid_location.tile = my_map.global_tile_set[key]`

`KeyError: '1'`

**Comment by pvcraven** [comment]
Hm, any chance you can send me a sample file of this? paul@cravenfamily.com or post here or something.

**Comment by pdblood** [comment]
Thanks for the quick response. I think I found the issue: the current implementation read_tiled_map.py does not support [the workflow described in the Tiled docs](https://docs.mapeditor.org/en/stable/manual/introduction/#creating-a-new-map) involving creating a map from a single tileset image and [using the terrain brush](https://docs.mapeditor.org/en/stable/manual/using-the-terrain-tool/). Once I created a map using separate images for each tile, it worked fine. So, I suppose support for that workflow could be an enhancement request for future versions.

**Comment by pvcraven** [comment]
Ooh, right. Thanks for the reminder I need to support that.

**Comment by Beefy-Swain** [comment]
Have we had any progress on this front? This would be a great feature to have.

**Comment by pvcraven** [comment]
No progress lately. Maybe this summer.

**Comment by Beefy-Swain** [comment]
I am working on this as part of #362.

Question, what do think would be the most performant way to create a bunch of sprites from a single image?

I assume the `arcade.load_textures` function?

**Comment by pvcraven** [comment]
Ok, so this would require work both at the `Sprite` and `SpriteList` level. The `SpriteList` right now creates a sprite sheet out of the images that the `Sprite` classes have.

I think you'd need new `Sprite` constructor options that let you pass in a large image, and coordinates for the sub-image on it. Then the `SpriteList` class would need to use that image instead of manage its own and insure all members of that list are part of that larger image.

**Comment by pvcraven** [comment]
New tilemap code works with a tileset image.
