### ISSUE TITLE
Is this library good for Raycaster like Wolf3D & Wolfenstein RPG?

### ISSUE THREAD

**Issue by Alihusejn** [pvcraven/arcade#253]

**Comment by pvcraven** [comment]
From scratch? Probably not a good fit. You'd want something to write to a bitmap I'm guessing. Or learn to write OpenGL stuff.

**Comment by Alihusejn** [comment]
If Pygame is suitable for this, then Arcade should be especially suited because it is built on top of Pyglet.

**Comment by pvcraven** [comment]
Pygame has a bitmap focus. Pyglet has an OpenGL focus. Normally, with OpenGL you'd use OpenGL commands for 3D, and not write the raycaster yourself.
