### ISSUE TITLE
Extend PhysicsEngineSimple to support a SpriteList of "players"

### ISSUE THREAD

**Issue by ChrisJefferson** [pvcraven/arcade#256]
The PhysicsEngineSimple only supports a single player, and a set of blocks.

It would be nice if an arraylist of "players" were supported. The idea is these would interfere with each other, but all be stopped from walking through the blocks. This could be used to make enemies which also couldn't walk through walls.

**Comment by pvcraven** [comment]
Just create a physics engine for each player or enemy. You aren't limited to one.

**Comment by ChrisJefferson** [comment]
Ah, that would work too! Might be worth mentioning that in one of the tutorials (I'll see if I can spot a good place to do it. The other option would be to combine one of the "with enemy" demos with a physics engine.

**Comment by ChrisJefferson** [comment]
Just to say, I tried this. The problem is that I can't just (efficiently) "kill" a sprite any more, because I need to clean up it's physics engine too.

If I could pass a SpriteList to a physics engine, then I could call `kill` on elements of the SpriteList and clean things up easily.

**Comment by pvcraven** [comment]
Have you taken a look at PyMunk?

**Comment by pvcraven** [comment]
Closing. PyMunk, or using multiple physics engines are options.
