### ISSUE TITLE
arcade.Window's resizable=True doesn't work on Windows 10

### ISSUE THREAD

**Issue by asweigart** [pvcraven/arcade#259]
## Bug Report

Passing True for the resizable parameter doesn't result in a window that's resizable on Windows 10. (This also might be the case for other OSes, I haven't checked.) 

### Actual behavior:

There's no icon change to the draggable arrows when the mouse is over the edges of the window, and the maximize button on the window doesn't do anything.

### Expected behavior:

The usual two-arrow mouse cursor should appear when the mouse is over the edge of the window, and the window should resize when dragging the edges.

### Steps to reproduce/example code:

I discovered this by running the code in the Application Class Module documentation:

    >>> import arcade
    >>> window = arcade.Window(200, 100, resizable=True)

**Comment by asweigart** [comment]
Closing this issue. This just comes from a misunderstanding I had while working through the documentation. The window doesn't resize because we haven't set up code correctly. Perhaps I should submit an issue about the documentation snippet instead.

**Comment by pauleveritt** [comment]
That’s a good point about that line of the docs. How about editing an extra line, doing a diff, and pasting it here. I’ll apply the diff to master.

Thanks for hanging out with us last night.

—Paul
