### ISSUE TITLE
[Example Code] A better way to toggle fullscreen mode.

### ISSUE THREAD

**Issue by carlsmith** [pvcraven/arcade#260]
In some of the examples ([like this one][1]), there are places where these two lines are used:

``` python
self.is_full_screen = not self.is_full_screen
self.set_fullscreen(self.is_full_screen)
```

This code seems to do the same thing:

``` python
self.set_fullscreen(not self.fullscreen)
```

Did I overlook something?

[1]: http://arcade.academy/examples/full_screen_example.html#full-screen-example

**Comment by pvcraven** [comment]
Either works. Your example is cleaner. If you'd like to make a pull request, I'll put it in.

**Comment by carlsmith** [comment]
Thank you. I was worried I'd overlooked something.

I will look into updating the code examples now. Should be simple enough.

**Comment by pvcraven** [comment]
Closing.
