### ISSUE TITLE
AttributeError: module 'arcade' has no attribute 'open_window'

### ISSUE THREAD

**Issue by Code4SAFrankie** [pvcraven/arcade#264]
### Steps to reproduce/example code:

import arcade

# Open up a window.
# From the "arcade" library, use a function called "open_window"
# Set the window title to "Drawing Example"
# Set the and dimensions (width and height)
arcade.open_window(600, 600, "Drawing Example")

# Set the background color
arcade.set_background_color(arcade.color.AIR_SUPERIORITY_BLUE)

# Get ready to draw
arcade.start_render()

# Draw a rectangle
# Left of 5, right of 35
# Top of 590, bottom of 570
arcade.draw_lrtb_rectangle_filled(5, 35, 590, 570, arcade.color.BITTER_LIME)

# Finish drawing
arcade.finish_render()

# Keep the window up until someone closes it.
arcade.run()

### What is wrong with it? How can it be improved?
Installed a fresh copy of anaconda (latest) after having the same issue, pip install arcade, get this error when running the above code:

C:\ProgramData\Anaconda3>python e:\Work\Python\arcade.py
Traceback (most recent call last):
  File "e:\Work\Python\arcade.py", line 7, in <module>
    import arcade
  File "e:\Work\Python\arcade.py", line 13, in <module>
    arcade.open_window(600, 600, "Drawing Example")
AttributeError: module 'arcade' has no attribute 'open_window'

Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by Code4SAFrankie** [comment]
Code above should be:
import arcade

arcade.open_window(600, 600, "Drawing Example")
arcade.set_background_color(arcade.color.AIR_SUPERIORITY_BLUE)
arcade.start_render()
arcade.draw_lrtb_rectangle_filled(5, 35, 590, 570, arcade.color.BITTER_LIME)
arcade.finish_render()
arcade.run()

**Comment by pvcraven** [comment]
The program that you listed works fine for me.

BUT, you can't have a file named `arcade.py`. What is happening is that Python is importing `arcade.py` instead of the arcade library.
