### ISSUE TITLE
OpenGL on Ubuntu doesn't support 3.3 by default on Mac Mini

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#265]
With the current opengl_shaders branch, I get the following under Ubuntu on my Mac Mini:

`arcade.shader.ShaderException: Shader compile failure (0): 0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES`

Do we need instructions on OpenGL versions and management of drivers?

**Comment by dangillet** [comment]
GLSL version 3.3 is supported with OpenGL version 3.3 and above.

Is it on Mac OS X or on Ubuntu? I'm confused. If it's Mac OS X, as discussed we need to fix that in pyglet as it defaults to compatible profile.

If it's on Ubuntu, can you make sure you have a core profile 3.3 active?

**Comment by pvcraven** [comment]
Don't think this is still an issue, closing.
