### ISSUE TITLE
load_texture() position starts from up-left?

### ISSUE THREAD

**Issue by Clutetot** [pvcraven/arcade#268]
## Problem
according to the document from arcade-book, it says that library will calculate the position based on Cartesian coordinate system, which means `0, 0` is the _bottom_ left.

but when I call `load_texture` with specified position, It will crop the image from _top_ left.
same problem applies to the `load_textures` function.

I don't know if this is an intended behavior, but I find that this is kind of confusing.
I thought that I must be missing something and I've looked up the `load_texture` section of the document,
but as far as I read it doesn't pointed out this particular behavior.

excuse me for this messy writing.
this is literally the first time I'm opening an Issue & English is not my first language.

## reproducing code
<details>
<summary> Code </summary>

```python
#!/usr/bin/python

import arcade
assert arcade.VERSION == '1.3.4' # make sure that arcade is the latest version

IMAGE_PATH = 'images/layer_test.png'
IMAGE_SIZE = 500

# opening new window with the size of [500, 500].
arcade.open_window(IMAGE_SIZE, IMAGE_SIZE, 'reproduce')


# according to the documentation of arcade, position [0, 0] should point the bottom-left of the window.
position = 0 # x = 0, y = 0.

# load the texture from position [0, 0] with the size of 250, 250 ( 1/4 of the original image )
left_down_image = arcade.draw_commands.load_texture(IMAGE_PATH,
                                                      x=position,
                                                      y=position,
                                                      width=IMAGE_SIZE // 2,    # 1/4 of the image.
                                                      height=IMAGE_SIZE // 2    # 1/4 of the image.
                                                      )

# start drawing image on the window.
# it points the position [125, 125] so it should be the bottom-left.

arcade.start_render()

arcade.draw_texture_rectangle(center_x=IMAGE_SIZE // 4,
                                center_y=IMAGE_SIZE // 4,
                                width=left_down_image.width,
                                height=left_down_image.height,
                                texture=left_down_image
                                )

arcade.finish_render()

arcade.run()
```
</details>

### Result
<details>
<summary>Original Image and Result screen</summary>

#### Original
![layer_test](https://user-images.githubusercontent.com/5960126/44436385-d25ee000-a5ef-11e8-9c05-7d41d461b3ee.png)

#### Result
![screenshot from 2018-08-22 09-41-08](https://user-images.githubusercontent.com/5960126/44436585-fd95ff00-a5f0-11e8-8fed-583758106df1.png)
</details>

**Comment by pvcraven** [comment]
Images normally have 0, 0 in the upper left. Which is confusing when the main coordinate system runs 0, 0 in the lower left.

**Comment by pvcraven** [comment]
Documentation updated, closing.
