### ISSUE TITLE
Drawing primitives video has old parameter order for arcade.open_window

### ISSUE THREAD

**Issue by FooDownunder** [pvcraven/arcade#272]
### What documentation needs to change? 
The Drawing primitives video has incorrect parameter order (name, coord, coord)

### Where is it located?
https://vimeo.com/167158158 linked on http://arcade.academy/examples/drawing_primitives.html, highlighted at the 1 minute mark

### What is wrong with it? How can it be improved?
Is it possible to slice the video with the new format?
Is it worth highlighting at https://github.com/pvcraven/arcade/blob/master/arcade/examples/drawing_primitives.py#L32 that this is the correct order? (and the video is no longer correct?)

**Comment by pvcraven** [comment]
Thanks for the catch. This is video needs to be redone.

**Comment by simonchih** [comment]
The comment make drawing primitives can't run, see issue #365

**Comment by pvcraven** [comment]
Removed video.
