### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by impactcolor** [pvcraven/arcade#276]
I installed
pip3 install PyObjC arcade

tested it by going to "python3"
in python terminal I "import arcade" to test.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
/python/arcade/arcade.py", line 8, in <module>
    arcade.open_window(SCREEN_WIDTH, SCREEN_HEIGHT, "Drawing Example")
AttributeError: module 'arcade' has no attribute 'open_window'

It's very straight forward but it doesn't work.  Any ideas?

**Comment by pvcraven** [comment]
Do you have a file named "arcade.py"? Looks like it is importing your file
instead of the library.

**Comment by impactcolor** [comment]
Worked great! @pvcraven
