### ISSUE TITLE
load_textures not handling new Texure

### ISSUE THREAD

**Issue by TheFonus** [pvcraven/arcade#282]
## Bug Report
draw_commands.py->Texture contructor has been updated with a mandatory name parameter (for cache). 

load_textures cant handle this atm. (load_texture has been updated though).

### Steps to reproduce/example code:

Example uses a image map size 64*32
image_location_list = [[0, 0, 32, 32], [32, 0, 32, 32]]
texture_list = arcade.load_textures(
     file_name="my_image.png",                                      
     image_location_list=image_location_list)

### Where is it located?
draw_commands.py

**Comment by pvcraven** [comment]
Should be working at this point.
