### ISSUE TITLE
Way to draw multiple polygons with same transparency

### ISSUE THREAD

**Issue by aole** [pvcraven/arcade#283]
### What should be added/changed?
Multiple calls to draw polygons causes the transparency to add up (transparent color provided in the color parameter to draw_polygon_filled(..).
Need a way to draw multiple polygons in one batch with the same transparency.

### What would it help with?
Creating a simple top down game which has vision cones (polygon) for each of the characters. When drawing overlapping vision cones, their transparency gets added and starts looking weird.

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html

**Comment by einarf** [comment]
This is possible by just changing the `ctx.blend_func`, so I'd consider this already supported. We do need an alpha blending section with more information, but that should be added later with the OpenGL stuff.
