### ISSUE TITLE
[Help] Can I add text to a ElementShapeList?

### ISSUE THREAD

**Issue by owlnical** [pvcraven/arcade#287]
I'm trying to make a class for buttons. It includes two shapes + text. Ideally I would like to draw this as a single ShapeElementList. Is this possible, or do I need to draw the text separately?

This is what I do for the shapes:

```python
self.shape_list = arcade.ShapeElementList()
background = arcade.create_rectangle_filled(x, y, w, h, background_color))
self.shape_list.append(background)
outline = arcade.create_rectangle_outline(x, y, w, h, outline_color, outline_size)
self.shape_list.append(outline)
return self.shape_list = arcade.ShapeElementList()
```

Can I do something this for the text?

```python
button_text = arcade.create_text(x, y, w, h, text)
self.shape_list.append(button_text)
```

Thanks for creating the Arcade Library. Me and my friend are having a lot of fun learning python over [here](https://github.com/owlnical/fc-aqua-fish).

**Comment by pvcraven** [comment]
Unfortunately not at this time. Text is drawn differently than the drawing
primitives, and I never thought to put them together.
Paul Vincent Craven

**Comment by owlnical** [comment]
Ok, thanks.
