### ISSUE TITLE
Feature request: Sprite position and velocity as Vector

### ISSUE THREAD

**Issue by MrGallo** [pvcraven/arcade#289]
## Enhancement request: 
Represent `arcade.Sprite.position` and `velocity` as a Vector.

### What should be added/changed?
I would like to suggest having the `arcade.Sprite` base-class use an arcade Vector class.

### What would it help with?
I have been working with arcade and I'm seriously considering switching to it to teach my high school classes, so, nice work on the project as a whole! Every time I make a little game, I always extend the `arcade.Sprite` to incorporate `pymunk.Vec2d` to store `Sprite.position` and `Sprite.velocity`. 

To alleviate the need to import another dependency, as noted by @pvcraven, arcade should have its own Vector class.

Working with vectors allows for greater readability and mathematical manipulation of the `position` and `velocity` fields.

If one, wishes, they can still use the `center_x` and `change_x` fields without touching vectors.
But, the change would open up the possibility for:

```python
sprite.position += sprite.velocity
sprite.velocity.y -= GRAVITY
sprite.position = 100, 100
sprite.velocity *= 0.95

difference_vector = player.position - sprite.position
if difference_vector.length < something:
    # do something
```

**Comment by pvcraven** [comment]
Moving to enhancement list. Please re-open this issue if you are actively developing on it.
http://arcade.academy/enhancement_list.html

**Comment by MrGallo** [comment]
What should the next steps for this be? I can resolve conflicts in the PR if we want to have that `Vector` class integrated. Or we can use that other vector class you mentioned somewhere.

**Comment by alejcas** [comment]
I've changed the Vec2 into something more useful and I think that it should be standard. 
The main reason is this:

Vec2 doesn't allow to operate on scalar values so I can't do: `Vec2(2, 3) * 4`

For this reason I re-implement Vec2 like so:

```python
def __mul__(self, other):
    if isinstance(other, tuple):
        return self.__class__(self[0] * other[0], self[1] * other[1])
    else:
        return self.__class__(self[0] * other, self[1] * other)
```
Same with `__add__` and others...

Also sometimes I need a vector to be integer or float and instead of recreate a vector with the correct type I just implement these:

```python
    def as_type(self, return_type: type) -> "Vector":
        return self.__class__(return_type(self[0]), return_type(self[1]))
```
so now I can just call:

```python
vec = Vector(4, 6)
vec.as_type(float)
```

**Comment by einarf** [comment]
@janscas This is something you could raise in the pyglet project. Possibly make a PR.
