### ISSUE TITLE
Load a spritesheet with a texture_region map

### ISSUE THREAD

**Issue by MichaelRijsdijk** [pvcraven/arcade#291]
## Enhancement request:
It would be an improvement to be able to import a spritesheet which can be cut into separate Sprites through code or with an included region information file. This would reduce the amount of I/O operations for setting up for example character animations. If the animation has 10 frames/Sprites you could load in one file and convert them into a list of Sprites through code.

### What should be added/changed?
load_spritesheet -> can be as simple as loading an image
texture_region -> holds coordinate and size information for items in the loaded spritesheet.

Or maybe it would be possible to enhance the load_textures function with an extra option for a region description file.

Example basic:
A basic implementation could be a spritesheet image and a generate_textures with Sprite size which splits the image into Textures.

generate_textures(spritesheet, sprite_size)

Example advanced:
![uiskin](https://user-images.githubusercontent.com/2979561/50954818-c51b9280-14b7-11e9-892d-322f0c95c7e9.png)

[uiskin.txt](https://github.com/pvcraven/arcade/files/2744265/uiskin.txt)

Programs like TexturePacker create these kind of files where Sprites could have different sizes.

### What would it help with?
Reduce I/O load
Reduce the amount of images
Most frameworks for games support this method of loading Sprites

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html

**Comment by einarf** [comment]
We already have `load_spritesheet` and `load_textures` that takes region information. It should be quick and easy to make some custom format like a json file and dump that into list with a one-liner if neded.

There are so many different texture packers and formats. I'd rather see these as external packages. We already have waaaay to much code to maintain in arcade as it is.
