### ISSUE TITLE
Can't read tiled map if tileset ids are not continuous

### ISSUE THREAD

**Issue by missmici** [pvcraven/arcade#292]
## Bug Report
arcade.read_tiled_map() cannot read the tiled map from individual images, if it's not 128x28 in size.

### Actual behavior:
When I try to read a map with other size of tiles(32x32), I get the following error message every time:

File "\site-packages\arcade\read_tiled_map.py", line 231, in read_tiled_map
grid_location.tile = my_map.global_tile_set[key]
KeyError: '235'

### Steps to reproduce/example code:
I used mainly the example code "[work with a tiled map](http://arcade.academy/examples/sprite_tiled_map.html)".

**Comment by pvcraven** [comment]
I've used this with 70x70 tiles ok. It might be possible the error is something other than tile size. A sample tiled file with tiles would be helpful to debug.

**Comment by missmici** [comment]
[volatiles.zip](https://github.com/pvcraven/arcade/files/2817827/volatiles.zip)

I see. I made a really basic tiled map, packed it together with the images, hope this helps!

**Comment by pvcraven** [comment]
Arcade assumes tileset ids start at 1 and go up from there. In this example, there are some apparently deleted tiles from the tileset, and the ids skip:

  <tile id="7">
   <image width="32" height="32" source="images/25.png"/>
  </tile>
  <tile id="8">
   <image width="32" height="32" source="images/27.png"/>
  </tile>
  <tile id="9">
   <image width="32" height="32" source="images/30.png"/>
  </tile>
  <tile id="12">
   <image width="32" height="32" source="images/s5.png"/>
  </tile>
  <tile id="13">
   <image width="32" height="32" source="images/9.png"/>
  </tile>

This is an incorrect assumption on Arcade's part.

**Comment by pvcraven** [comment]
Can you test with version 2.0.0b4 I just uploaded? I think the changes I made should fix the issue.

**Comment by missmici** [comment]
I tested it with the new example code, and the arcade example map, now i get this -- 
File "/pls.py", line 80, in setup
    my_map = arcade.read_tiled_map(map_name, SPRITE_SCALING)
  File "\site-packages\arcade\read_tiled_map.py", line 227, in read_tiled_map
    print(i.keys)
AttributeError: 'str' object has no attribute 'keys'

-- not sure if I miss something.

**Comment by pvcraven** [comment]
That's weird. Because line 227 on the 2.0.0b4 is ``for column_index, column in enumerate(row):`` and not ``print(i.keys)``. In fact, I don't see that line anywhere in the file.

You might try checking that file and see what it does have on that line. Check the same directory and see if version.py does have 2.0.0b4. Maybe uninstall, reinstall that beta version if the files don't look right.

**Comment by pvcraven** [comment]
Closed with 2.0 release.
