### ISSUE TITLE
Fix minor documentation inconsistencies and simple bugs in example programs

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#295]
### Summary
While going through the example programs for the first time, I noticed some typos, copy/paste errors, and inconsistencies in the docstrings. So, I did a quick pass to fix some of these issues.  I was also able to fix a few simple bugs to get broken examples to run with the library as it is on master.

### Expected behavior:
Each example should be able to run, have a unique window title, and have a correct "python -m ..." path in the docstring. 

### Actual behavior:
Simple bugs, copy paste errors and simple omissions made the example code feel a bit inconsistent.

### What should be added/changed?
* The broken example code should be able to be run
* Documentation typos should be fixed
* Each bit of example code should have a unique window title

**Comment by pvcraven** [comment]
Merged. Thank you so much!!!

**Comment by pvcraven** [comment]
CI can't test opengl stuff. I need to turn that off.

**Comment by pvcraven** [comment]
Deployed.
