### ISSUE TITLE
What is the correct way to set the transparency of a sprite ?

### ISSUE THREAD

**Issue by Subzero8** [pvcraven/arcade#311]
Hi, sorry to disturb.

I am a student from belgium and I'm trying to make a "game of go” clone.
So I tried to make my stones transparent when hovering my mouse on the board. I tried to set the sprite alpha attribute to 0.5 but it only works once, when I click one the board it sets the stone and when I’m hovering again, the transparency won’t set.
Here is my project repo, the arcade class is in the class “game/GoGui.py”.

https://github.com/Subzero8/Go

I added some console printing to see if the alpha was not setting up correctly but from what’s written, the value of alpha is correct (0.5) but the stone is not half transparent =(

Please excuse my english and my code which may not be pretty to look at.

Thanks in advance

Alexandre

**Comment by pvcraven** [comment]
With version 2.0.0b4, If you want 50% visible, set the 'alpha' to 127. Goes on a scale 0-255. So in your example, line 81:

``stone.alpha = 127``

**Comment by Subzero8** [comment]
> With version 2.0.0b4, If you want 50% visible, set the 'alpha' to 127. Goes on a scale 0-255. So in your example, line 81:
> 
> `stone.alpha = 127`
Thank you for your answer.
I installed the 2.0.0b4 on my mac and I got this error : 

```
Traceback (most recent call last):
  File "/Users/alexandredepape/Documents/Python/Games/Go/Main.py", line 1, in <module>
    import arcade
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arcade/__init__.py", line 24, in <module>
    from arcade.sound import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arcade/sound.py", line 65, in <module>
    _load_sound_library()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arcade/sound.py", line 39, in _load_sound_library
    import pyglet_ffmpeg
```
ModuleNotFoundError: No module named 'pyglet_ffmpeg'

Do you know why it happens ?

**Comment by Subzero8** [comment]
Ok I downloaded pyglet-ffmpeg manually and it works, but now my window resized to something very little.
So I resized the window to 1200 1200 but the on_mouse_motion function gives me 600 600 when placing my mouse on the top right corner.
I am on macos.

**Comment by pvcraven** [comment]
Oh, darn. Those bugs with the Mac are why I haven't released the beta version yet. No, the 2.0 version does not play nice with the Mac because of the Retina display.

**Comment by pvcraven** [comment]
New beta 2.0.0b5 out now. I played around with the code in that area. Forgot to check if I need to monkey-patch pyglet.

**Comment by Subzero8** [comment]
Thanks, it appears that when creating a window of size 1200 1200, the top right corner has coordinate 600, 600. Do you know how can I fix it ?

**Comment by pvcraven** [comment]
There's a 2.0.0b5 out where I messed around with that part. Are you running
b5 or b4? I hope it works with b5.

**Comment by pvcraven** [comment]
Ok, it didn't work with b5. I just released 2.0.0b6 and I think I have the
issues fixed on the Mac.
Paul Vincent Craven

**Comment by Subzero8** [comment]
Thank you very much ! Sorry for the late answer, I was working on other projects.
I have a question, if I wanted to create a little menu, would it be possible to add a listener to each of the buttons in the menu ?

**Comment by pvcraven** [comment]
As far as the listener, not at this time.
