### ISSUE TITLE
Fix minor documentation rendering issues

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#316]
- Fix a few minor, isolated documentation rendering issues (code block, function arguments)
- Fixed broken path to gameshell.jpg
- Add table of contents to API and Quick API pages
- Get rid of some `make doc` warnings

**Comment by pvcraven** [comment]
These should be up now.

**Comment by SirGnip** [comment]
The "GameShell" image at the bottom of http://arcade.academy/examples/index.html isn't rendering with proper proportions, which appears to also be throwing off the proportions of the other images in that row. I somehow missed that in my local doc build.  I'll take a look.

**Comment by pvcraven** [comment]
Closed with 2.0 release.
