### ISSUE TITLE
Pixels on Mac retina displays are super weird

### ISSUE THREAD

**Issue by maludwig** [pvcraven/arcade#319]
### Actual behavior:

Weird things happen with retina displays on OSX:

<img width="1011" alt="screen shot 2019-02-24 at 5 09 27 pm" src="https://user-images.githubusercontent.com/9811172/53307576-21aff280-3857-11e9-9da0-4ba6a038f6ad.png">

### Expected behavior:

Everything should scale cleanly with a retina display. For example, two pixels, one at (x,y) and one at (x+1,y) should have no pixels in between them.

### Steps to reproduce/example code:

https://gist.github.com/maludwig/fe5a1d73ed039717767d43d0ea2f807f

#### Extra Info

Keywords for future searchers: MacOS OSX Mac Retina Display HDPI

**Comment by maludwig** [comment]
Same screenshot from a not-Retina scale:
<img width="498" alt="screen shot 2019-02-24 at 5 30 34 pm" src="https://user-images.githubusercontent.com/9811172/53307893-098da280-385a-11e9-8bcd-96590ec92d17.png">

**Comment by maludwig** [comment]
So, in another interesting turn of events, I tried to reproduce the bug by cloning down the repo, with the intent to fix it. But when I did that, it installed pyglet==1.4.0b1, where previously I had 
pyglet==1.3.2

Seems like pyglet 1.4 makes the window unnaturally small, not scaled at all, but with none of the previous issues. Now I'm not sure what to do. Like, should I define this as a bug? Should arcade just require the latest pyglet to fix it?

**Comment by pvcraven** [comment]
The beta (master branch) of Arcade uses Pyglet 1.4.0b1. And yes, retina displays are a serious headache.

**Comment by pvcraven** [comment]
<img width="990" alt="screen shot 2019-02-24 at 7 33 33 pm" src="https://user-images.githubusercontent.com/1463116/53309068-48782400-386b-11e9-8a46-b085fe0141ed.png">
On my Mac the horrible looking text destracts from the bugs. (Seriously, the main reason I haven't released the beta version is the Mac graphic bugs.)

**Comment by pvcraven** [comment]
Possibly related to Issue #299.

**Comment by saildata** [comment]
Same bug is visible in Arch Linux 4.20.13. (2160p60 display, 162 dpi) 
![arcade_text_bug](https://user-images.githubusercontent.com/11636184/53684305-40880c00-3cd1-11e9-8096-2070e77024ba.png)

**Comment by pvcraven** [comment]
Could you try with the new 2.0.0b5 version please? Thanks.

**Comment by saildata** [comment]
Checking it out now. @pvcraven did you forget `git tag` for the release?

**Comment by saildata** [comment]
I honestly can't tell. Maybe this screenshot with 2.0.0b5 will help someone.
![retina-bug-update-2b5](https://user-images.githubusercontent.com/11636184/53691092-b2e20600-3d3c-11e9-908b-e4dadfdc00d7.png)

**Comment by pvcraven** [comment]
Turn the alias back on

**Comment by saildata** [comment]
![retina-but-update-2b5-v2](https://user-images.githubusercontent.com/11636184/53933248-0917b780-4063-11e9-8ac3-4a5d5f0ddf1e.png)

**Comment by pvcraven** [comment]
Should be fixed with 2.0 release. Re-open if not the case.
