### ISSUE TITLE
Add forward method to sprite?

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#323]
### What should be added/changed?

Add a forward() method to the sprite.

If a sprite has an angle, perhaps it should also have a forward() method to move it ahead a few pixels? I'm not sure if there should be a corresponding left/right/reverse. Right now that would make a name collision with left/right. Need a decent naming convention.

**Comment by lixingqiu** [comment]
suport  like turtle module ,forward(fd), backword(back,bk)，or  make a enhanced module like turtle' module 
 use Arcade module.

**Comment by SirGnip** [comment]
This would be interesting.  Other game coding frameworks focused on beginners (for example, [Scratch](https://scratch.mit.edu/)) make heavy use of relative motion (forward, back, turn_right, turn_left).  For beginners, it is often easier to reason about "turning and moving in that direction" than doing coordinate and vector math.

**Comment by JosiahBradley** [comment]
I've implemented forward, strafe, and stop to tackle turtle like motion. Will be sending pull request soon. turn_left and turn_right are currently implemented via modifying Sprite.change_anlge

**Comment by lixingqiu** [comment]
thank you,it updated  in http://arcade.academy?


------------------
你好,  请下载附件,  未尽事宜,  请发电子信箱商议.
 


 




------------------ 原始邮件 ------------------
发件人: "JosiahBradley"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 凌晨2:19
收件人: "pvcraven/arcade"<arcade@noreply.github.com>;
抄送: "李兴球"<406273900@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [pvcraven/arcade] Add forward method to sprite? (#323)




I've implemented forward, strafe, and stop to tackle turtle like motion. Will be sending pull request soon. turn_left and turn_right are currently implemented via modifying Sprite.change_anlge

**Comment by pvcraven** [comment]
This is in prod, closing.
