### ISSUE TITLE
Quality and performance hit on 2.0.0

### ISSUE THREAD

**Issue by aole** [pvcraven/arcade#325]
### Actual behavior:
The quality and performance has taken a huge hit on the new release version 2.0.0

### Expected behavior:
Quality/performance should be >= to the previous versions

### Steps to reproduce/example code:
Run the same code in 2.0.0 and 1.3.7 to see the difference.

This is from 1.3.7
![image](https://user-images.githubusercontent.com/4707543/54131869-9c494800-43e9-11e9-925a-1c480946c3fa.png)

This is from 2.0.0
![image](https://user-images.githubusercontent.com/4707543/54131963-c569d880-43e9-11e9-8df7-88359a150130.png)

Above displays the quality issue (aliasing). Do I have to turn some flags on or make any changes to the code (like increasing the line width)? But this is exactly the same code.

Also, when dragging the above (primitives) (on_mouse_motion/set_viewport) there is a significant lag now.

**Comment by pvcraven** [comment]
The quality issue goes to anti-aliasing as you've assumed. Might have been introduced around #275. I'll take a look at making a setting to flag this on/off as I think both are needed.

Using shaders slows regular drawing commands. Using buffered drawing commands will speed things significantly. Can you give that a try? I can't keep the old drawing code because with OpenGL there's a huge change in drawing once you get to OpenGL 3.x version which Arcade 2.x was updated to use.

**Comment by pvcraven** [comment]
Ok, quality hit came from updating to OpenGL 3+. We are using polygons to draw lines, as OpenGL deprecated thick lines.

Simple solution would be to add polygon smoothing, but that adds artifacts as described here:
https://gamedev.stackexchange.com/questions/110286/how-to-fix-texture-edge-artefacts

Solution seems to be to revamp the whole app to use multi-sampling. Ugh.

**Comment by pvcraven** [comment]
Manually drawing and flipping the screen allows for multisampling and smooth lines:

    while True:
        window.on_draw()
        window.flip()
        window.dispatch_events()

But calling the standard pyglet run does something that disables it:
```
pyglet.app.run()
```
Not sure why or what the fix is yet.

**Comment by pvcraven** [comment]
Would you mind trying 2.0.1b1 version I just released?

**Comment by wamiqurrehman093** [comment]
yes I will try it... man also add generate sprites function for tmx map
layers

**Comment by aole** [comment]
Got the following error with 2.0.1b1

> Traceback (most recent call last):
  File "C:\Users\baole\workspace\github\Civilization\src\main.py", line 800, in <module>
    game = parse_xml('core.xml')
  File "C:\Users\baole\workspace\github\Civilization\src\main.py", line 784, in parse_xml
    game = Game(400, 400, 'Civilization')
  File "C:\Users\baole\workspace\github\Civilization\src\main.py", line 347, in __init__
    super().__init__(width, height, title)
  File "C:\ProgramData\Anaconda3\lib\site-packages\arcade\application.py", line 55, in __init__
    gl.glEnable(gl.GL_MULTISAMPLE_ARB)
NameError: name 'gl' is not defined

**Comment by pvcraven** [comment]
Obviously I need to get the unit testing working again. 2.0.1b2 is out. Sorry, hope this one works.

**Comment by aole** [comment]
Quality is back on. (I have not tested with batching for performance but its still sluggish). Looks good to me, 
2.0...
![image](https://user-images.githubusercontent.com/4707543/54637746-cb9e2b80-4a5f-11e9-9e02-c05a400022ba.png)

The difference is rendering the text, may be now its taking width into account, but did not have to time to explore this further.
1.3.7....
![image](https://user-images.githubusercontent.com/4707543/54638021-6a2a8c80-4a60-11e9-9539-02fe54099aa0.png)
