### ISSUE TITLE
Fix examples that are broken after 2.0 release

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#326]
I ran `python -m arcade.examples.run_all_examples` to go through the example apps after the 2.0 release.  A number of examples had problems.  I think some of these (ex: pinball) have been broken for awhile.  I ran these on Windows 7 with code from 37f8450.

I found and fixed a few errors (PR is forthcoming).  The remaining errors were:

* drawing_primitives.py: expect the points in the "draw points" area to be squares. They are triangles.
* mountains_midpoint_displacement.py: Throws `AttributeError: module 'arcade' has no attribute 'decorator'` on startup
* mountains_random_walk.py:  Throws `AttributeError: module 'arcade' has no attribute 'decorator'` on startup
* pinball.py: Starts up but simply shows a black screen with one white triangle at the bottom that has some slight oscillating motion.
* shape_list_demo_1.py: Stalls on startup. An empty window that doesn't draw anything.  Windows reports it as "Not Responding" after a couple seconds.  High CPU usage.  Have to kill it to close window.
* shape_list_demo_2.py: takes 30+ seconds to draw anything
* shape_list_demo_3.py: Throws `AttributeError: module 'arcade' has no attribute 'create_rectangles_filled_with_colors'` on startup
* shape_list_demo_skylines - Throws `AttributeError: module 'arcade' has no attribute 'create_rectangles_filled_with_colors'` on startup

**Comment by pvcraven** [comment]
Thanks. My list was similar, but I missed the triangles for draw points.

Not anti-aliasing things is something I also missed, and is a pretty big
deal. Trying to figure out how to do multisampling now.

Paul Vincent Craven

**Comment by pvcraven** [comment]
Ok, I love your automatic test runner. I patched in an os environment thing so it automatically cycles through them.

**Comment by SirGnip** [comment]
Glad it is helpful!  Taking 10 minutes after a major code change to cycle through all the example code and do a quick visual inspection is a great way to catch regressions.  Not as fully automated as unit tests obviously, but still extremely helpful in catching errors...

**Comment by pvcraven** [comment]
Currently can cycle through all tests on windows without error.

**Comment by SirGnip** [comment]
Even with the breakage you mentioned here: https://github.com/pvcraven/arcade/issues/333#issuecomment-486841558?  I've got a fix. Should be able to push up PR tonight.

**Comment by pvcraven** [comment]
Yes. I cycle through all the programs and only run them for one frame. So your stats died because they assumed at least two frames. I just added an 'if' to make sure there were at least two data points.

**Comment by SirGnip** [comment]
That'll do it.  Thanks for the fix!

**Comment by SirGnip** [comment]
Hm. I got the newest code (which included your "two frame" fix), ran "make test" and the particle examples (particle_systems.py) didn't crash, but they popped up the matplotlib window which had to be closed manually before the tests would continue.  Not great for automated testing. So, I pushed up a PR with a quick fix: https://github.com/pvcraven/arcade/pull/370.

**Comment by pvcraven** [comment]
Fixed in 2.0.8 released 2019-04-27.
