### ISSUE TITLE
Getting texture id in 2.0?

### ISSUE THREAD

**Issue by UplinkPhobia** [pvcraven/arcade#330]
### Expected behaviour:

In previous versions, one could get the id of a Texture by simply calling `texture.texture_id`.

### Actual behaviour:
Now, however, it seems impossible to get any useful information from a bare Texture, and the "closest" thing I found related to a texture_id was in SpriteList.

However, it doesn't seem possible (I might very well be wrong on this, I just did a quick reading of the related code) without calling the draw() function of a SpriteList.

### Question
Is there still a way to get a texture_id directly from a Texture?

**Comment by pvcraven** [comment]
SpriteList manages the textures now that Arcade is using shaders. It also tries to find duplicate textures and reuse them, which didn't always make texture id applicable. What use-case do we need the id for?

**Comment by UplinkPhobia** [comment]
Sorry, my previous message was apparently never sent.

My use case is a little bit peculiar, as I'm using Arcade next to Glooey (that I use as the GUI).
Glooey is based on pyglet's image handling (the ImageData class if I remember correctly). 
Until the new Arcade version, I could load a spritesheet with Arcade by using load_textures(), and use the loaded texture (through their texture id) to create an ImageData I could then feed to glooey. The goal of this was to avoid loading the spritesheet and creating the textures twice.

I understand that this case is a bit too specific, and I don't know if there are many use cases where one would need to reuse textures as I tried to do.

I'm not very familiar with pyglet and the underlying openGL behaviours though, so maybe I'm doing it wrong.

**Comment by pvcraven** [comment]
The SpriteList will actually create one big texture that has all the images for that sprite list. So it is no longer one texture per sprite. It is one texture per SpriteList, where we pull out the parts we want for each sprite.
