### ISSUE TITLE
Add support for particle systems in arcade

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#333]
As I was watching Paul's Arcade talk from PyCon 2018, I noticed that [particles where mentioned in the "What's Next" portion of the talk](https://www.youtube.com/watch?v=DAWHMHMPVHU&t=24m2s).  I thought I'd write an Issue to track discussion.  I'll also be submitting a PR with a "discussion starter" implementation.

**Comment by pvcraven** [comment]
This adds a dependency for all projects to PyMunk just for getting Vec2D. Not wild about that.

**Comment by SirGnip** [comment]
The unnecessary dependencies have been removed in 17b8570

**Comment by pvcraven** [comment]
The test programs for these are failing?

  File "C:\Web Server\arcade\arcade\examples\frametime_plotter.py", line 34, in _show_stats
    print("StdDev: {:.5f}".format(statistics.stdev(self.times)))
  File "C:\Program Files (x86)\Python37-32\lib\statistics.py", line 649, in stdev
    var = variance(data, xbar)
  File "C:\Program Files (x86)\Python37-32\lib\statistics.py", line 587, in variance
    raise StatisticsError('variance requires at least two data points')

**Comment by SirGnip** [comment]
@pvcraven, how were you running the particle example scripts?  With `python -m arcade.examples.particle_systems`?  From an IDE?  Using `python -m tests.test_examples.run_all_examples`?  `make test'?

**Comment by pvcraven** [comment]
This system needs to be documented a bit more. Or more examples, but since it is in, I'm going to close this out.
