### ISSUE TITLE
Update to 2.0.1: import arcade warns "FFmpeg binaries could not be loaded."

### ISSUE THREAD

**Issue by ReblochonMasque** [pvcraven/arcade#335]
## Bug Report
Update to 2.0.1 from 1.3.7: import arcade warns "FFmpeg binaries could not be loaded."
### Actual behavior:
Warning: warns "FFmpeg binaries could not be loaded."
### Expected behavior:
No warning
### Steps to reproduce/example code:
On OSX

ideas?

**Comment by ReblochonMasque** [comment]
2.0.2b2 update also warns that `FFmpeg binaries could not be loaded.`

Is that a known problem, maybe related to [milestone 4](https://github.com/pvcraven/arcade/milestone/4), or is it likely a problem with my set up?  
(version==1.3.7 did not show warnings)

**Comment by ReblochonMasque** [comment]
For reference, 2.0.4 also warns that FFmpeg binaries could not be loaded.

**Comment by jdshaeffer** [comment]
I'm experiencing these warnings as well. What do they mean? Why do they show up?

**Comment by pvcraven** [comment]
If it can't find the ffmpeg binaries, it can't play mp3 and ogg sound files.
