### ISSUE TITLE
Not all graphic cards support multisampling

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#339]
## Bug Report

By default, 2.0.1 uses multisampling. This apparently isn't supported everywhere. See:

https://stackoverflow.com/questions/55404539/python-3-6-4-arcade-module-window-errors-pyglet-gl-lib-glexception-binvalid

### Actual behavior:

Generates error.

### Expected behavior:

If the graphics card doesn't support it, we should just downgrade gracefully.

**Comment by pvcraven** [comment]
Version 2.0.2b1 has been released. If you could test it and let me know, I'd appreciate it.

**Comment by pvcraven** [comment]
Fixed with 2.0.3 release.

**Comment by pvcraven** [comment]
![image](https://user-images.githubusercontent.com/1463116/56063528-26603580-5d35-11e9-90a1-f10050f7c00b.png)

Looks like the fix didn't work.

**Comment by streetartist** [comment]
I find the same problems too.

We need to fix it!

**Comment by einarf** [comment]
Create the window with `antialiasing=False`
