### ISSUE TITLE
Use of setup method instead of __init__?

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#34]
I see in your examples that you encourage the definition of a setup method, called immediately after class instantiation, instead of an __init__. For the asteroid_smasher.py demo, my linter complained about defining instance attributes outside of __init__. When I got rid of setup and moved everything to MyApplication.__init__, and called super() on arcade.window, it all seemed to work ok.

Looking at the Window.__init__ source, it doesn't look like it is doing much. Is there a reason to frown on sticking with __init__? Perhaps some pyglet thing I don't know about?

**Comment by pvcraven** [comment]
Hi, thanks for the feedback. I'll try to improve that sample and make it easier to understand and pass linting.

What linter are you using? I've run the code through pep8, but probably should use some other tools as well.

I use setup() in that class because if the game can be 'restarted', the programmer can just call setup() again. I probably need need to call it start_game() or something better. And also declare the variables in the init(). I'll get to work on it.

**Comment by pvcraven** [comment]
I'll assume it is the standard pylint package and work to improve what it reports.

**Comment by pauleveritt** [comment]
I'm using the linting/analyzer that comes in PyCharm.

I have to say, I like reading your code. Kudos on the level of docstrings, tests, and examples. I'm curious as to your design goals, who you'd like to use it, what's considered anti-goals, etc.

**Comment by pvcraven** [comment]
It is intended for students, or hobbyists that want to create games. Simplicity wins over power for this library. Pyglet or Kivy are great choices for those that want more power. Or there's always Unity, etc.

I've taught students with Pygame a long time. I think if I could remove some of the Pygame 'oddities' they could learn and do more.

**Comment by pauleveritt** [comment]
Any chance you are at PyCon?

—Paul

**Comment by pvcraven** [comment]
Yes! Are you? I presented yesterday. 

Paul Vincent Craven

**Comment by pauleveritt** [comment]
I am at the JetBrains booth. I would love to talk to you.

**Comment by pvcraven** [comment]
Cool, I'll find you. 

Paul Vincent Craven

**Comment by pauleveritt** [comment]
I believe I missed you earlier, do you have time this afternoon ?

**Comment by pauleveritt** [comment]
Great meeting you yesterday. If you're up for some sprinting on Thursday, I'll try and tackle a couple of the issues in the tracker.
