### ISSUE TITLE
Use color not csscolor

### ISSUE THREAD

**Issue by graeme-f** [pvcraven/arcade#347]
https://github.com/pvcraven/arcade/blob/b764eb412032beb79c85d697eb2856ad68fa481e/arcade/examples/platform_tutorial/01_open_window.py#L22

arcade.set_background_color(arcade.color.CORNFLOWER_BLUE)

**Comment by pvcraven** [comment]
CSS color was put in to use standardized CSS colors instead of the non-standard colors that are part of the 'color' package. Either works, but CSS colors are probably better for people learning since they carry over to multiple domains.

**Comment by graeme-f** [comment]
I installed aracde via pip, and csscolor is not imported, so I either had to use color or add a line to import csscolor. So I think, under those circumstances, using color is better.

**Comment by pvcraven** [comment]
Oh, it was in the master branch and not the fix branch. That's seriously annoying.

**Comment by pvcraven** [comment]
CSS color in 2.0.4 release.
