### ISSUE TITLE
Run pylint on the code and improve it based on pylint feedback

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#35]
As noted in a different issue, pylint shows several issues. Spend some time making that better.

**Comment by pvcraven** [comment]
Some work has been done on this with recent check-ins. Not done yet though.

**Comment by pvcraven** [comment]
Some work has been done on this with recent check-ins. Not done yet though.

**Comment by pvcraven** [comment]
Some work has been done on this with recent check-ins. Not done yet though.

**Comment by pauleveritt** [comment]
Next time I will close with commit.
