### ISSUE TITLE
pyglet-ffmpeg isn't importing for Linux

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#350]
Probably should make pyglet-ffmpeg optional as an import, as I'm getting a lot of complaints from people that can't find a compatible build architecture-wise. Or learn how to build more versions of it.

Also, should add a menu item for how to install from source.

**Comment by ReblochonMasque** [comment]
What is strange is that (in my case), `ffmpeg` was loading well in versions 1.x; it is version 2 that broke it.  

Maybe that reveals a clue as to where to look for the problem?

**Comment by pvcraven** [comment]
ffmpeg wasn't used in versions 1, avbin was instead.

Paul Vincent Craven

**Comment by ReblochonMasque** [comment]
haha, ok, thank you. That explains it!

**Comment by ReblochonMasque** [comment]
ref to #335, now closed.

**Comment by pvcraven** [comment]
Improvements have been made for 2.0.6. I think it works for both Windows and MacOS. Linux still erroring out.

**Comment by pvcraven** [comment]
Should be working for Mac. Updated to show it isn't working for Linux.

**Comment by ReblochonMasque** [comment]
Not working on mac osx 10.12.5 and python 3.7  
`FFmpeg binaries could not be loaded.`

`arcade 2.0.7`

**Comment by pvcraven** [comment]
Did pyglet-ffmpeg2 install? Or just pyglet-ffmpeg?

**Comment by ReblochonMasque** [comment]
`Successfully installed arcade-2.0.7 pyglet-ffmpeg2-0.1.12`

**Comment by pvcraven** [comment]
Are you able to modify library files? If you follow the chain to `pyglet_ffmpeg2\loader.py` and the `_locate_binaries` function here:

https://github.com/pvcraven/pyglet-ffmpeg/blob/master/pyglet_ffmpeg2/loader.py#L24

What value does `paths` take? Does the library file install into one of those folders?

**Comment by dangillet** [comment]
Hi,

The original intent behind pyglet-ffmpeg was to provide users with the right ffmpeg binaries (version 4.x), using the Python wheels mechanism.

For Windows and Mac, I just downloaded the ffmpeg binaries from the website. For Linux, it's a more complicated story. Each variant of distros and each version need different compiled binaries.

Last year, on Ubuntu, `sudo apt-get install ffmpeg` was installing ffmpeg 3.4. But Pyglet relies on ffmpeg 4.x. It seems that today the command would install the right version of ffmpeg.

I had made an attempt at compiling myself ffmpeg 4.0 for Ubuntu - described in the documentation. But this was only running on the Ubuntu version I had back then (16.04 to the best of my memory) and possibly on newer ones. But today it would be best to instruct the user to install ffmpeg on his distro. The code should then be amended for Linux in order not to change the environment variable `LD_LIBRARY_PATH` as it should already contain the path to the installed ffmpeg 4.X binaries.

The doc said it clearly that only Mac and Windows were supported. But it's true that wheels were built for linux, which creates this situation. Best would probably be to remove the linux wheel altogether.

**Comment by jcbianic** [comment]
Commenting out line 55 of loader.py does the trick for me:

`#path = path.replace("/lib/", "/lib64/")`

pyglet_ffmpeg2 install path was 

> /lib/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/

rather than:

> /lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/

Note : install done through a conda env.

**Comment by alkanen** [comment]
So, in Linux, if you've made sure you have ffmpeg 4.x.x installed, is there any way to install arcade by making it not try to install pyglet-ffmpeg2?

**Comment by pvcraven** [comment]
I don't think there is a way to do per-platform dependencies. I do think it will now load on any platform, just won't do anything for unsupported platforms.

**Comment by pvcraven** [comment]
Closing, as it should load even if it can't find the libraries well.
