### ISSUE TITLE
Improve Tiled Support

### ISSUE THREAD

**Issue by Beefy-Swain** [pvcraven/arcade#362]
## Enhancement request:
Support for Tiled is poor. Arcade does not support single file tsx, it does not support non-polyline hitboxes, the functionality is largely un-documented, and the code has few comments, and it is poorly tested.

### What should be added/changed?
- External tileset file (tsx) support, including multiple tsx files
- Tilesheets
- all supported hitbox types
- add a dict with custom properties to each sprite(?) object
- anything else that tiled supports that is unsupported
- more tests for Tiled related functionality

### What would it help with?
using Tiled with Arcade

---

I would be happy to make the requisite changes, as I think that I am (hopefully) qualified to do so, but I have 2 concerns:

1. The kind of changes that are likely necessary would be breaking changes. I don't know how that is handled in this project
1. I don't know how to use pytest or whatever we do for testing.

I will get started on adding the functionality I can think of, and hopefully someone else can either tell me how to test it, or can write the tests for it.

Thanks!

**Comment by Beefy-Swain** [comment]
Thought I had for concern 2:

I will create another file called tiled.py, and if my changes are accepted then read_tiled_map.py can be deprecated with a warning, then eventually removed.

**Comment by Beefy-Swain** [comment]
I'm really struggling here to figure out how to test this code effectively. How do I say, "if the pixel at (x,y) is value foo, fail" for instance.

**Comment by Beefy-Swain** [comment]
It seems like `pyglet.image.get_buffer_manager().get_color_buffer().save('screenshot.png')` could maybe do what I want. Any idea how to get that working?

**Comment by pauleveritt** [comment]
I can help. If you can give me a couple of code paths as examples, I can suggest a strategy. I admit, I know exactly zero about the Arcade code under discussion.

First, for "unit testing", you can use monkeypatch or mocks to replace the "rest of the system". Then see if those parts were called with the right values.

Or, if the tiled system keeps some state, you can reset it between tests and, during a test, assert if its "model" has the correct info.

Or, start by writing tests for the existing reported bugs for Tiled. Helps get a test base in place.

I will start by reading your comments in #360

**Comment by Beefy-Swain** [comment]
@pauleveritt I appreciate the help!

I have written a bunch of "[tests](https://github.com/Beefy-Swain/arcade/blob/new_tiled/tests/unit2/test_tiled.py)" for the new Tiled module I am working on, but unfortunately they don't all work as I would like. For instance, the background doesn't seem to work. The issue is, this doesn't cause a fatal error, so the tests "pass". There are a number of issues like this.

**Comment by pauleveritt** [comment]
If you could fork pvcraven/arcade into your own repo, make a branch there, and invite me as a collaborator, I can work with you on it.

**Comment by Beefy-Swain** [comment]
I have done so :) sure thing!

https://github.com/Beefy-Swain/arcade/tree/new_tiled

**Comment by Beefy-Swain** [comment]
I think I understand what you mean when you say

>First, for "unit testing", you can use monkeypatch or mocks to replace the "rest of the system". Then see if those parts were called with the right values.

are you saying don't literally test if the window shows a background, or if a tile is transparent, but check the sprites for those attributes. That makes sense.

**Comment by pvcraven** [comment]
There is [arcade.get_pixel](http://arcade.academy/arcade.html#arcade.get_pixel) if you want to get a point and test its color.

**Comment by Beefy-Swain** [comment]
Ah man, I feel really dumb now.

Thanks!

**Comment by pauleveritt** [comment]
@Beefy-Swain I have to apologize, I've gotten swamped prepping PyCharm stuff for PyCon. Not going to get to it this week. :(

**Comment by Beefy-Swain** [comment]
@pauleveritt I'll see you there!

**Comment by pauleveritt** [comment]
@Beefy-Swain Come see @pvcraven give a mini-talk on Arcade in the PyCharm booth, Friday 11-11:15

**Comment by Beefy-Swain** [comment]
@pauleveritt Sure thing! I plan on working on this during my free time so having you two close by will probably help with that ;)

**Comment by akrokho** [comment]
https://github.com/bitcraft/PyTMX
Today I had the idea to use this library to solve a problem. But there are nuances associated with the fact that in the arcade for downloading images using the library PIL. Going to move in this direction (adapt libraries)
P.S. I do not understand English very well and I use a translator, sorry)))

**Comment by Beefy-Swain** [comment]
@akrokho I would be mindful of a couple issues that I ran into when I looked into that library.

1. The license is not compatible with the Arcade library, so code adapted from it could not be bundled with Arcade
1. While it does have much better TMX support than Arcade currently does, it does not have full TMX support.

**Comment by pvcraven** [comment]
This enhancement is pretty generic. I'd love to see it broken out into discrete items, like #375 does to support rotated tiles.

**Comment by Beefy-Swain** [comment]
My current intention is to write a fully compliant parser for TMX/TSX files, and perhaps the JSON formatted files too if I'm feeling particularly motivated, and then start creating Arcade integration from there.

I am currently about 70% of the way to having TMX/TSX files fully parsed to the spec. Hoping to discuss some of this in person at PyCon if you think you would have time for that?

**Comment by pvcraven** [comment]
You'd better believe I'll make time for that!

Paul Vincent Craven

**Comment by pvcraven** [comment]
Branch `tmx_update_try_2` can load multiple tsx files. Hitboxes aren't supported yet.

**Comment by SirGnip** [comment]
I pushed up PR #420 which makes the bottom-left corner of the bottom-left tile sit at the window's origin.  The current behavior is for the left-most column and bottom-most row to be drawn off-screen.  This is the same change discussed in #415 (see screenshots).  In that issue @pvcraven asked:

> "should the lower left sprite be at 0, 0 for a center, or 0, 0 for the lower left corner of the sprite?"

In keeping with the "principle of least astonishment", I think users would expect that after they load a map and draw it with Arcade that it would be completely visible (assuming the window was sized appropriately).  Having to add an offset in the map or code just to get it all to show up seems confusing to me.  In the code's current state, the bottom-most row and left-most column of tiles are drawn off-screen.  My vote is that (by default) the lower-left corner of the lower-left tile should be at 0,0.  If the user wants to add offsets to move it, they can do that from a relatively obvious starting place.

**Comment by wamiqurrehman093** [comment]
New updates on Platformer is really good I am really hyped to implement those features in my game. Nice Work ^-^

**Comment by pvcraven** [comment]
Closing. New versions have better support.
