### ISSUE TITLE
draw_xywh_rectangle_textured error

### ISSUE THREAD

**Issue by simonchih** [pvcraven/arcade#363]
arcade.draw_xywh_rectangle_textured(cell_width * x, cell_height * y, cell_width, cell_height, istone, 0)
  File "C:\Program Files\Python37\lib\site-packages\arcade\draw_commands.py", line 1374, in draw_xywh_rectangle_textured
    repeat_count_y)
TypeError: draw_texture_rectangle() takes from 5 to 9 positional arguments but 10 were given
Error in sys.excepthook:

**Comment by pvcraven** [comment]
Fix should be in next release. Thanks.
