### ISSUE TITLE
pyglet-ffmpeg2 loads bad path on raspberryPi

### ISSUE THREAD

**Issue by bkasel** [pvcraven/arcade#367]
## Bug Report
pyglet-ffmpeg2 badly constructs paths to ffmpeg binaries
### Actual behavior:
path uses linux_x86_64 in load path
### Expected behavior:
path should use RPi
### Steps to reproduce/example code:
open arcade window on raspberry pi

### What should be added/changed?
This issue is probably linked to issue #350 

On the raspberry Pi `sys.platform` in the loader.py file simply returns 'linux'. If you would like to check for the raspberry Pi (ARMv7) you could do `os.uname().machine=="armv7l` This fixed the issue for me

**Comment by pvcraven** [comment]
Thanks, this fixes that part. Can you get it to run at all on the Pi? I get a NoSuchConfigException later on.

**Comment by bkasel** [comment]
No I get the same error. I have been trying around to get a valid config, but with no success...

**Comment by pvcraven** [comment]
Maybe. Have you tried enabling OpenGL yet? I haven't, but a quick search makes me wonder if it is worth trying:

https://eltechs.com/how-to-enable-opengl-on-raspberry-pi/

**Comment by bkasel** [comment]
good idea...I'll try that tomorrow

**Comment by bkasel** [comment]
BTW I am getting the same error on ubuntu in virtualbox with hardware acceleration enabled. I will keep you posted if I succeed on the raspi.

**Comment by dangillet** [comment]
Hello,

The binaries for RPi never worked unfortunately. I don't have a RPi myself. So in an attempt to help RPi users, I tried to cross-compile ffmpeg 4.X from Linux an armv7l version. But the RPi user I was trying to help back then told me it didn't work. And I left it in that state.

Best would be to check what ffmpeg version is today installed on RPi. If it's 4.X, then you should be good to go. Pyglet should be able to find the ffmpeg binaries, provided they're on your `LD_LIBRARY_PATH` environment variable. If the version is still 3.4, you will need to attempt to compile FFmpeg 4.x from source. In case you are successful, the resulting binaries could be added to the pyglet-ffmpeg wheels to prevent future users with the pain of compiling ffmpeg from source themselves.

**Comment by pvcraven** [comment]
Thanks, I'll try it that way. Of course, I'm not sure if I can get the OpenGL working on Raspberry Pi, so I'll probably work on that first.

**Comment by pvcraven** [comment]
Fixed (?) in 2.0.8 released 2019-04-27. Although OpenGL doesn't work, so it is kind of pointless. Going to close this and open a issue to explore getting a context working.
