### ISSUE TITLE
Move the examples out of docs

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#37]
I'd like to make the examples feel more like first class citizens in the project, in a top-level "games" directory. We'd then change the Sphinx literal include references to point up to the games.

This would allow the following way to run a game:

- pip install arcade
- python -m arcade.games.asteroids

...instead of having to get asteroids.py copied into a directory somewhere.

I can do a PR for this if it is approved.

**Comment by pvcraven** [comment]
I totally agree and would like to see this happen. I think it was moved down because with the sphinx docs, I didn't know how to reference the example file if it wasn't in the base directory where the docs started. Can you manage to figure out how to do this?

**Comment by pauleveritt** [comment]
Merged and closed.
