### ISSUE TITLE
Move sound support to SoLoud

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#372]
Look at [SoundFile](https://pypi.org/project/SoundFile/) and [SoundDevice](https://pypi.org/project/sounddevice/) and see if they have good ideas we can use.

**Comment by pvcraven** [comment]
The SoundFile/SoundDevice combo appear to only support playback of one sound at a time. That doesn't work well for sound effects.

**Comment by pvcraven** [comment]
Might need to create our own interface on top of: https://app.assembla.com/spaces/portaudio/git/source

**Comment by pvcraven** [comment]
* [avbin](https://avbin.github.io/AVbin/Home/Home.html) - Pygame uses, old (2012) and unsupported
* SoundDevice - only one sound at a time. No good.
* ffmpeg - Currently can't figure out universal support on all platforms
* PyAudio - still worth looking at?

**Comment by pvcraven** [comment]
Soloud works under MacOS and Windows now. Need to get Linux support and it will clear a lot of the rest of these issues up.

**Comment by humansHS** [comment]
[Pyglet Sound and Audio](https://pyglet.readthedocs.io/en/latest/programming_guide/media.html)

>Decoding of compressed audio and video is provided by FFmpeg v4.X, an optional component available for Linux, Windows and Mac OS X.

> **FFmpeg needs to be installed separately.**

Pyglet's FFmpeg works fine with a bunch of features that weren't properly implemented in Arcade (I have been experimenting with it myself and was going to try to fully implement and bug test them before offering to Arcade), you just have to download and install it.

With that said, I am reading [SoLoud QuickStart](https://sol.gfxile.net/soloud/quickstart.html) and it does have quite a lot of support (and I believe it DOES work on Linux?), so seems the switch would be fine. Just thought I would present an alternative in case anything is troubling with SoLoud.

**Comment by pvcraven** [comment]
I've messed with that for years. Getting new programmers to do a separate install of ffmpeg does not lead to success.

I created a separate package with ffmpeg libraries for the different platforms, but it was always a real pain because it would work for a while, then break. And debugging it through all Pyglet's layers was a time-sink.

Right now, when I build SoLoud on linux, then hook it up to Python, I get missing link errors. I'm hopeful I can get that working.

I like soloud because of its ease of use, and support for volume and panning.

**Comment by humansHS** [comment]
Excellent, I look forward to seeing it. I will be installing Linux Lite 4.8 next weekend to test another environment, so Linux support is a huge plus! I would offer my support but I'm not confident I can help haha. Thanks as always for all the great stuff :)

**Comment by pvcraven** [comment]
Done.
