### ISSUE TITLE
TypeError: __init__() takes from 3 to 11 positional arguments but 12 were given in text.py

### ISSUE THREAD

**Issue by Rohzen** [pvcraven/arcade#373]
I know was already fixed but it seems to be present in the latest release (2.0.8).

I've fixed temporarily on my local version adding a dummy argument:

class CreateText:
    """ Class used for managing text """
    def __init__(self,
                 text: str,
                 color: Color,
                 font_size: float = 12,
                 width: int = 20,
                 align="left",
                 font_name=('Calibri', 'Arial'),
                 bold: bool = False,
                 italic: bool = False,
                 anchor_x="left",
                 anchor_y="baseline",
                 **nop = 0,**
                 ):

**Comment by pvcraven** [comment]
Can you give a code example that generates the error?

**Comment by Rohzen** [comment]
Hi, yes it's from a game sample i've found:

  File "game.py", line 422, in on_draw
    self.score_text = arcade.create_text(output, arcade.color.GREEN, 10)
  File "C:\Python37\lib\site-packages\arcade\text.py", line 60, in create_text
    my_text = CreateText(text, color, font_size, width, align, font_name, bold, italic, anchor_x, anchor_y, rotation)
TypeError: __init__() takes from 3 to 11 positional arguments but 12 were given

**Comment by pvcraven** [comment]
Thanks, that's what I needed.

**Comment by Rohzen** [comment]
You're welcome, i am using your tutorials for pygame and arcade library.Very nice work!

**Comment by pvcraven** [comment]
Fixed with 2.0.9 release.
