### ISSUE TITLE
Support basic sprite animations like rotate, flicker, disappear, etc.

### ISSUE THREAD

**Issue by akrokho** [pvcraven/arcade#377]
I think that you need to add basic animations for sprites (rotation, flicker, disappearance, periodic motion, etc.). The first question is - is it necessary? Interested in your opinion (yes or no).

**Comment by pvcraven** [comment]
Some of these should just be programmed. Probably fade, rotation, periodic motion. We might need examples showing it.

Frame-by-frame animation should be better supported. Also, I'd like to see the animations specified in the Tiled Map Editor load by default.

**Comment by akrokho** [comment]
I used to work with cocos2d library. On my view in it implemented very convenient system animations (http://python.cocos2d.org/doc/programming_guide/actions.html). To implement a similar system for the Sprite class, it seems to me quite simple (add a list of animations and implement the update_animations method). The only thing I do not know if I will not be accused of plagiarism)))

**Comment by akrokho** [comment]
Good day! Made a trial version of simple animations. Archive in the attachment. I send you for review. I think that this implementation of animations is simple and clear. I wonder your opinion. Should I add animation in this form to the library? 29.04.2019, 16:22, "Paul V Craven" <notifications@github.com>:Some of these should just be programmed. Probably fade, rotation, periodic motion. We might need examples showing it.Frame-by-frame animation should be better supported. Also, I'd like to see the animations specified in the Tiled Map Editor load by default.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by akrokho** [comment]
I attach an archive with an example of the implementation of simple animations. The implementation is "raw" but working. I will be glad to hear criticism and suggestions for improvement.

**Comment by akrokho** [comment]
[animations.zip](https://github.com/pvcraven/arcade/files/3142996/animations.zip)

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html
