### ISSUE TITLE
Support angle change in radians

### ISSUE THREAD

**Issue by Ace5273** [pvcraven/arcade#378]
### What should be added/changed?
The property of change angle in a sprite only
takes full integers which make the movement of an object
sort of funky
### What would it help with?
The funky movements :D

**Comment by pvcraven** [comment]
Where do they appear to be used at integers in the `Sprite` class? The get/set are floats. I need more direction to that part of the code.

**Comment by Ace5273** [comment]
My bad... I was looking at the property
