### ISSUE TITLE
Remove requirement for "sudo pip" in installation instructions.

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#38]
The install instructions for Linux:

http://pythonhosted.org/arcade/installation_linux.html

should not require sudo. Find some way to get the installation to work without sudo.

**Comment by malikoth** [comment]
Steps I used on Ubuntu 16.04:
```bash
apt update && apt install -y libjpeg-dev zlib1g-dev python3-dev python3-pip git
sudo pip3 install virtualenv virtualenvwrapper
viritualenv ~/.virtualenvs/<project name> -p python3
source ~/.virtualenvs/<project name>/bin/activate
pip install git+git://github.com/pvcraven/arcade.git
```
I haven't actually gotten it running on Linux, since my Linux is just running in a container.  But those are the steps I was able to use to install it from a barely-bootstrapped state.

**Comment by pvcraven** [comment]
Update the documentation with this.

**Comment by pauleveritt** [comment]
If we switch from promoting virtualenv to just using the bundled python3 -m venv (pyvenv) then I suspect this issue is solved?

**Comment by mikemhenry** [comment]
sudo will be needed to install the system packages needed. If you want, we can look into conda for packaging since it will allow users to install arcade without having to download extra packages and use sudo since it can build packages that are not pure python.

**Comment by pauleveritt** [comment]
I wonder what conda would mean for pyglet/avbin.

—Paul

**Comment by mikemhenry** [comment]
Looks like those packages already exist:
https://anaconda.org/conda-forge/pyglet

I could package avbin so it could be installed as a dependency.
While conda as its own quarks, its really nice for packaging projects that
can't rely on a pure python installation.

Some other software I use has switched over to conda and now we rarely see
installation issues on the mailing list.

**Comment by pauleveritt** [comment]
I’m up for considering it. I need to do better with conda anyways for my day job (PyCharm) and I think it could dramatically help the total newbie experience.

We’d have to keep all the existing stuff, so I suspect it’s a new ticket. As an FYI, I’m also interested in cookiecutter.

—Paul

**Comment by mikemhenry** [comment]
I agree, conda packages would be auto-built by the CI when we make a push
to master so they wouldn't replace any packages but just allow an easy
install method for new people to really hit the ground running. I'll make a
new issue on the conda idea.

But to get back on topic, I can edit the docs to remove some of the sudo
requirements but as it stands sudo will be needed for the system packages.
If someone has an issue where they don't have sudo access they *could*
build everything they needed but I think that is out side of the scope for
our installation manual.

**Comment by pauleveritt** [comment]
For Linux, you have:

```bash
apt update && sudo apt install -y python3-dev python3-pip libjpeg-dev zlib1g-dev
sudo pip3 install virtualenv virtualenvwrapper
virtualenv ~/.virtualenvs/arcade -p python3
source ~/.virtualenvs/arcade/bin/activate
pip install arcade
```

1. The first ``apt install`` needs to be ``sudo``.
2. Is ``python3-pip`` really needed? I think ``pip3`` comes for free if you have ``python3`` installed.
3. Would the ``-dev`` packages be needed if we make a wheel for ``arcade``?
4. I plan to make a different ticket to drop ``virtualenv`` and switch to the native Python 3 approach (``python3 -m venv name-of-virtualenv``).

**Comment by mikemhenry** [comment]
Your right that I omitted the first sudo, I'll play around and see what
packages are actually needed. Unfortunately each distribution might have
packages be slightly different so I've found its better to be explicit than
rely on the dependencies being correct. If we make a wheel I don't think we
would need -dev, but I'm not sure. I've never made a wheel before so I'll
have to learn to test it.

I didn't know Python now has built in virtual environments! Do you know of
this is something that we be ported back to 2.7? One thing nice about
virtualenv was the ability to select the Python executable you wanted to
make the environment with.

**Comment by pauleveritt** [comment]
It’s not something that will ever be back ported. Which doesn’t affect arcade, of course.

I tried it on Ubuntu, only to find that ``python3 -m venv`` requires a package that has to be installed with apt. :(

—Paul

**Comment by pvcraven** [comment]
Closed. I think we'll keep things as-is on install.
