### ISSUE TITLE
TypeError: draw_rectangle_filled() got an unexpected keyword argument 'border_width'

### ISSUE THREAD

**Issue by akrokho** [pvcraven/arcade#385]
File "C:\Users\Andrey\PycharmProjects\arcade\arcade\draw_commands.py", line 1166, in draw_lrtb_rectangle_filled
    draw_rectangle_filled(center_x, center_y, width, height, color, border_width=border_width)
TypeError: draw_rectangle_filled() got an unexpected keyword argument 'border_width'

**Comment by akrokho** [comment]
Found a bug when you run the example particle_fireworks.py

**Comment by pvcraven** [comment]
Fixed with 2.0.9 release.
