### ISSUE TITLE
Experiment with threading option for update() method

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#388]
Update can be a bit slow. See if threading would help or hurt.

**Comment by akrokho** [comment]
http://qaru.site/questions/17499502/update-and-ondraw-pyglet-in-thread
An example of working with threads in pyglet. I do not know the truth as far as the example is correct.

**Comment by pvcraven** [comment]
Update would be a bit more complex I think.

You'd need 'worker threads' and a 'work queue' that would pull sprite update() methods that need to be run. It is a standard multi-threading pattern, but it could actually slow things down rather than speed them up.
