### ISSUE TITLE
Optimize polygon drawing

### ISSUE THREAD

**Issue by Fezzboi** [pvcraven/arcade#390]
im doing a 3D Renderer in python and with large models i discovered that arcade.draw_polygon_outline function was making roughly 80% of my games delta time, maybe make a polygon_list class much like the sprite_list class but for polygons. I've tried various multiprocessing and threading optimizations but in the end they made it the same speed if not slower, and the code itself i like to think of as pretty efficient.

**Comment by pvcraven** [comment]
Have you tried buffered drawing? It is WAY faster because it loads the polygon to the graphics card and then just redraws it.

**Comment by Fezzboi** [comment]
Thanks i'll look into it!

**Comment by pvcraven** [comment]
See: http://arcade.academy/arcade.html#arcade.create_line_loop

**Comment by pvcraven** [comment]
Also, in the examples folder, look at the examples beginning with `shape_list`

**Comment by Fezzboi** [comment]
aha i guess i didn't read the docs enough sorry for wasting your time xD

**Comment by Fezzboi** [comment]
from what i understand if it loads it onto the gpu at once then i wont be able to change the shapes point lists at runtime?

**Comment by Fezzboi** [comment]
Also the ShapeElementLists dont support item assignment

**Comment by Fezzboi** [comment]
@pvcraven the vertices of the models change each frame so the projected polygons need to be generated each frame as well, and ShapeElementLists dont support item assignment so the only way i think of implementing them is to make a one each frame which and append to it then render it which seems counter-intuitive to me. Please tell me if have overlooked something, or any ideas.

**Comment by pvcraven** [comment]
How many points/lines do you have? If you want that level of control, you might need to dive into OpenGL and learn how that works.

Unfortunately for your purposes, it sounds like the 'simplicity' this API strives for is working against your needs.

**Comment by Fezzboi** [comment]
ok thanks
