### ISSUE TITLE
PhysicsEngine, working with multiple lists

### ISSUE THREAD

**Issue by akrokho** [pvcraven/arcade#395]
PhysicsEngine supports working with one list of sprites. It is worth adding work with several lists (for example, a tile map has several layers of obstacles)

**Comment by akrokho** [comment]
Alternatively, you can add the magic method __add__ to the SpriteList class, and add lists.

**Comment by pvcraven** [comment]
Not a bad idea. Could just pass in a list instead of a SpriteList.

**Comment by pvcraven** [comment]
Closing for lack of development on this.
