### ISSUE TITLE
Return hit list from physics engine update

### ISSUE THREAD

**Issue by FredSkar** [pvcraven/arcade#401]
### What should be added/changed?
Return a hit list from physics engine uptade functions.

### What would it help with?
No extra functioncall to check_for_collision_with_list() if you want to do something with the hitted object. 

Is this a good way to do it or is it another way to do it? I'm still new to arcade.

**Comment by pvcraven** [comment]
Right now it generates two lists internally. One for the x direction and one for the y direction. It wouldn't be a bad idea to add this feature.

**Comment by pvcraven** [comment]
Fixed with release 2.2.6.
