### ISSUE TITLE
Slow arcade.draw_rectangle_filled?

### ISSUE THREAD

**Issue by feinstaub** [pvcraven/arcade#403]
Is there is reason why arcade.draw_rectangle_filled(x, y, WIDTH, HEIGHT, color) is so slow on my machine

E.g.:
http://arcade.academy/examples/array_backed_grid.html#array-backed-grid
Drawing the 15x15 grid takes about 300 - 500 ms.

If I remove the call to arcade.draw_rectangle_filled, the draw method finishes almost instantly.
 
Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.57.0
Qt Version: 5.12.3
Kernel Version: 4.19.36-1-MANJARO
OS Type: 64-bit
Processors: 2 × AMD E-450 APU with Radeon(tm) HD Graphics
Memory: 7,4 GiB

**Comment by pvcraven** [comment]
Yes, non-buffered draw commands are slow. Use shapelists and
create_rectangle. The ln you can draw them all in one operation.

**Comment by pvcraven** [comment]
See also: 

https://github.com/pvcraven/arcade/blob/master/arcade/examples/array_backed_grid_buffered.py

**Comment by feinstaub** [comment]
Thanks for updating the doc!

I tried the buffered example you mentioned earlier but I wasn't aware that it is indeed faster than the unbuffered example. It still has got a noticeable "lag" when clicking a square.

I drafted a (potentially memory extensive when used in other cases) caching mechanism in recreate_grid(self) of array_backed_grid_buffered.py. Now, the color of a square changes super-fast on mouse click:

```
                key = "{}{}{}{}{}".format(x, y, WIDTH, HEIGHT, color)
                current_rect = None
                if not key in self.rect_dict:
                    current_rect = arcade.create_rectangle_filled(x, y, WIDTH, HEIGHT, color)
                    self.rect_dict[key] = current_rect;
                else:
                    current_rect = self.rect_dict[key]
                self.shape_list.append(current_rect)
```

**Comment by feinstaub** [comment]
For the array example: does it make sense (and is it possible) to only create two rectangles (white and green) at position 0,0 and then translate it to the correct position while building the grid? That would save memory while staying fast. Or must the position be "hard-coded" to each shape in a shap list?

**Comment by pvcraven** [comment]
I think this would require an OpenGL call for each translation. If you pre-load everything, it can be drawn with one call. I'll have to look at the timings on the buffered array.
