### ISSUE TITLE
Get Arcade added to Tiled "Libraries and Frameworks" page?

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#411]
Would it be worth getting Arcade added to the Tiled map editor's "Libraries and Frameworks" page?

https://doc.mapeditor.org/en/stable/reference/support-for-tmx-maps/#support-by-framework

More exposure for Arcade, maybe...

**Comment by akrokho** [comment]
First, it is worth completing support for the tiled map. Now it is not complete. And so definitely worth it.

**Comment by pvcraven** [comment]
PR Made: https://github.com/bjorn/tiled/pull/2209

**Comment by pvcraven** [comment]
Haha, PR was accepted.
