### ISSUE TITLE
Support for multiple tsx files in tiled map.

### ISSUE THREAD

**Issue by FredSkar** [pvcraven/arcade#417]
## Enhancement request:
Be able to use a tiled map with multiple tsx files. Today it is not possible due to no offsets for when "firstgid" is not 1 in different tsx files.

### What should be added/changed?
Add an offset of "firstgid" when loading the tiles.

### What would it help with?
Better tiled support.

**Comment by pvcraven** [comment]
Currently in-progress with TMX revamp.

**Comment by FredSkar** [comment]
> Currently in-progress with TMX revamp.

Any idea of when we will see a first version of the TMX revamp? I'm working a lot with Tiled maps and I'm looking into a few enchantments that could be done, but if the Tiled support is going through a big update/change I don't want to start work on my ideas before we have a new version.

**Comment by pvcraven** [comment]
This summer, not sure exactly when. 

Just pushed branch tmx_update_try_2 which can use multiple external tilesets. Haven't really figured out API naming yet, and the branch doesn't missing hitbox support. Plus it depends on a project that hasn't been released to pypi yet I think.

**Comment by pvcraven** [comment]
Closing, please track this under Issue #362.
