### ISSUE TITLE
How do you find if sprite is clicked?

### ISSUE THREAD

**Issue by Obround** [pvcraven/arcade#418]
How do you recognize the action of a sprite being clicked? As far as I know, the `on_mouse_press` function only works for the whole screen.

**Comment by pvcraven** [comment]
This needs to be added. There are examples and code that come close, but don't have exactly what we need. Opening issue e#419 to manage.

**Comment by Obround** [comment]
Thank you. I'll see what I can do.

**Comment by BluePhoenixGame** [comment]
I found that this works in the meantime 
```python
def _has_been_clicked(x, y, sprite):
    return sprite.left < x < sprite.right and sprite.bottom < y < sprite.top
```

**Comment by pvcraven** [comment]
That works only if your sprite is not rotated and is using a rectangular hit-box. So, most cases, but not all.
