### ISSUE TITLE
Create function to get sprites at a particular point.

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#419]
Per question #418, create a function that will figure out what sprites are at a particular point. Something to make clicking on a sprite easier to handle.

For performance reasons, probably won't add an `on_click` handler for each sprite.

**Comment by Obround** [comment]
Is this fixed yet?

**Comment by pvcraven** [comment]
No, this feature has not been added yet.

**Comment by BluePhoenixGame** [comment]
A possible way to implement this would be to implement the `in` operator. Like `if x,y in arcade.Sprite()`. But it might break some python foundations in the way that the `in` operator is often used with iterables. Or just have a function that returns some kind of tuple with each coordinate that the sprite cover.

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html
