### ISSUE TITLE
Add support for drawing rounded rectangles

### ISSUE THREAD

**Issue by denys00** [pvcraven/arcade#421]
Hi, how can I draw a rectangle with rounded corners? Maybe there is a special function for this? I have not found anything like this in the documentation.

**Comment by pvcraven** [comment]
There is not a built-in function for drawing a rectangle with rounded corners.

**Comment by denys00** [comment]
But how can I make a rounded rectangle? I need to use it in my game.

**Comment by pvcraven** [comment]
Draw two rectangles, and four circles.

Paul Vincent Craven

**Comment by denys00** [comment]
Thanks for the tip. I tried to do as you said, but I also found the code for pygame to create rounded rectangles, here it is:
http://www.pygame.org/project-AAfilledRoundedRect-2349-.html
The problem is that pygame has more smoothed corners than arcade did (see screenshot below). I want to achieve the same smoothing on the arcade, how can I do this?
![screenshot](https://user-images.githubusercontent.com/37739893/58767653-5be80900-8597-11e9-8bb1-80357e8cfabb.png)

**Comment by denys00** [comment]
I also noticed some transparency issues, I would like to make the same shade over the whole shape.
![изображение](https://user-images.githubusercontent.com/37739893/58768015-ea12be00-859c-11e9-8b59-b0044efc651d.png)
I really hope for your help.

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html

**Comment by einarf** [comment]
Rounded rectangles should be possible with 9patch textures in 2.7.
