### ISSUE TITLE
Arcade fails inside a VM with OpenGL compile error.

### ISSUE THREAD

**Issue by Quest79** [pvcraven/arcade#427]
## Bug Report
Platform tutorial (downloaded) fails in VMWare Workstation 15 (with OpenGL 3.3)  with the below error.

### Actual behavior:
```
  File "C:\Users\Code\Anaconda3\lib\site-packages\arcade\shader.py", line 257, in compile_shader
    f"Shader compile failure ({result.value}): {msg.value.decode('utf-8')}")
arcade.shader.ShaderException: Shader compile failure (0): 0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
```

### Expected behavior:
The screen should show without issue.

### Steps to reproduce/example code:
Make VM (workstation 15) with windows 10, install vmware tools

### What should be added/changed?
Support for VM environments.

### What would it help with?
People that partition environments to VMs for certain workflow.

**Comment by pvcraven** [comment]
This is the error that comes back when OpenGL isn't being supported. The drivers aren't there, the hardware, or for some other reason the OS can't get a context for OpenGL. I don't think there's anything Arcade can do about it.

**Comment by Quest79** [comment]
The drivers are VMWare drivers for OpenGL, so when shader.py tries to compile, it doesn't understand the VM environments version of them. Here is some more info: [https://i.imgur.com/l2xLtf0.png](url)

**Comment by pvcraven** [comment]
Can you modify arcade/application.py's Window.__init__ to include these lines?

        gl.glfwWindowHint(gl.GLFW_CONTEXT_VERSION_MAJOR, 3);
        gl.glfwWindowHint(gl.GLFW_CONTEXT_VERSION_MINOR, 3);
        gl.glfwWindowHint(gl.GLFW_OPENGL_PROFILE, gl.GLFW_OPENGL_CORE_PROFILE);

**Comment by pvcraven** [comment]
Closed, no more info.
