### ISSUE TITLE
arcade.draw_points() - points as triangles instead squares

### ISSUE THREAD

**Issue by ThisWojciech** [pvcraven/arcade#429]
### Actual behavior:
arcade.draw_points() draws triangles
### Expected behavior:
arcade.draw_points() should draws squares just like:
arcade.draw_point()  function.
![Example](https://user-images.githubusercontent.com/46927059/61013959-52677300-a385-11e9-86d3-59410d45eb29.png)

### Steps to reproduce/example code:
Run "Drawing Primitives" example

**Comment by ThisWojciech** [comment]
**current draw.commands.py**
`new_point_list = _get_points_for_points(point_list, size)
    _generic_draw_line_strip(new_point_list, color, gl.GL_TRIANGLES)`

**Comment by pvcraven** [comment]
This fix is in production.
