### ISSUE TITLE
Exceptions are suppressed if arcade cannot find a default font for draw_text

### ISSUE THREAD

**Issue by MrGallo** [pvcraven/arcade#432]
Several students of mine were reporting `draw_text` wasn't working on our classroom Linux machines. After several hours of investigation I noticed some machines were actually missing all the default fonts arcade looks for if no font is specified. If the exceptions were not suppressed I would have figured this out much quicker.

https://github.com/pvcraven/arcade/blob/d548ebfa3f4ac826f8f14776545888b408603244/arcade/text.py#L198-L210

**Comment by MrGallo** [comment]
Neglected to check existing issues. #402

**Comment by MrGallo** [comment]
Actually (re-opening issue), I think the fix for #402 neglected to raise an appropriate error that would have been helpful.

**Comment by pvcraven** [comment]
Fixed with release 2.2.6.
