### ISSUE TITLE
Add support for bitmapped fonts

### ISSUE THREAD

**Issue by joezeng** [pvcraven/arcade#433]
### Enhancement request:

I notice that Arcade seems to only support drawing strings using a named font, or at least that's the only method that appears in the documentation.

### What should be added/changed?

Bitmap are raster fonts that are loaded from a bitmap file with some auxiliary data to define where the bounds of each renderable character are. I propose we support rendering these fonts in some way.

### What would it help with?

I make a lot of pixel fonts in bitmap form to use in my games, especially when they have pre-coloured effects, and it would be pretty tedious to have to convert them to TTF to use in Arcade, or to program the individual sprites to be drawn letter by letter (which is exactly what a method to draw text using bitmap fonts would automate).

**Comment by pvcraven** [comment]
I would love to see something like this added.

**Comment by joezeng** [comment]
I'll see what I can figure out.

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html

**Comment by invalidenumerant** [comment]
Is there a way to kill anti-aliasing on true type fonts so they show up like "pixel" fonts?

**Comment by einarf** [comment]
@invalidenumerant Use #851

**Comment by gran4** [comment]
> This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:
> 
> http://arcade.academy/enhancement_list.html

@pvcraven The link doesn't seem to exist anymore.
