### ISSUE TITLE
Support for networked games

### ISSUE THREAD

**Issue by samfrances** [pvcraven/arcade#437]
This is either an enhancement request or a documentation request, depending on whether the feature is supported.

### What should be added/changed?

Add support for making network (e.g. http requests) or other similar IO tasks in the background and then triggering some sort of custom event.

### What would it help with?

Making multiplayer games which run over a network.

### What documentation needs to change? 

If the enhancement above is in fact already implemented, or it is straightforward to achieve the same effect, it would be nice to have a reference example.

**Comment by pvcraven** [comment]
I'd love to see something like this, but I think it would be a separate project. Even large engines like Unity separate it out with projects like Phaser.

**Comment by samfrances** [comment]
Ok, thanks for considering the idea, in any case.

**Comment by cjrh** [comment]
I presented some thoughts on multiplayer network aspects at PyCon AU 2018 here: https://youtu.be/2SMkk63k6Ik

There are two distinct issues the talk raises:

1. The network comms can be done either with asyncio or with threading.  In the talk I used asyncio even though I had to run the asyncio event loop in a separate thread. I am still on the fence with this idea, particularly with respect to the client side comms. It might be simpler to avoid asyncio and just do all network comms in a separate thread (with blocking io) on the client.  (On the server, using asyncio is definitely the right choice).
2. There is quite a lot of complexity associated with decoupling the _screen render_ from the _network game state updates_.  I think there are solutions here, but it's quite intricate.

I agree with @pvcraven that these ideas are better explored in separate project/packages. There is no "one right way" to do them and that makes it unattractive to implement in the main arcade game engine.

**Comment by sbischoff-ai** [comment]
There are some game-specific networking libraries for python.
[Pygase](https://github.com/sbischoff-ai/pygase) is one I have written for my own python game projects.
Right now I only have a pygame example in the repo and the only public project I'm using it in is a cocos2D one, but I'd love to write a guide to multiplayer games with pygase + arcade.
Pygase is highly stable, has a simple and pythonic API and is suitable for twitchy games like platformers.

**Comment by pvcraven** [comment]
This is a great idea, going to close for now due to no one currently working on it. I think having the networking library be seperate is a good idea, but including some Arcade samples in the Examples section would be excellent if anyone wants to work on it.
