### ISSUE TITLE
AttributeError: module 'arcade' has no attribute 'is_point_in_polygon'

### ISSUE THREAD

**Issue by barnablewis** [pvcraven/arcade#442]
## Bug Report
AttributeError: module 'arcade' has no attribute 'is_point_in_polygon'
AttributeError: module 'arcade.geometry' has no attribute 'is_point_in_polygon'
Only seems to be missing in the version installed with pip install arcade

### Actual behavior:
is_point_in_polygon seems to be missing from the source code despite being documented online http://arcade.academy/arcade.html#module-arcade.geometry
### Expected behavior:
there is a method that uses ray tracing to establish if an x,y, point is within a polygon

### Steps to reproduce/example code:
try calling arcade.is_point_in_polygon() or arcade.geometry.is_point_in_polygon()

**Comment by MrGallo** [comment]
`is_point_in_polygon` was added about 2 months ago in commit 78169eaa196e559753a9ef287b67c66c304142bc. 

The latest arcade version is `2.0.9`. Is this the version you are using?

To check your arcade version, in the terminal, type `pip freeze` and it will give you a list of installed libraries and their versions:
```sh
$ pip freeze
arcade==2.0.9
...
```

**Comment by pvcraven** [comment]
That was a half-implemented function. As a sprite can be a rotated polygon, it isn't quite as easy as I'd like.

**Comment by pvcraven** [comment]
This function should be working ok as of Arcade 2.2.5.

**Comment by barnablewis** [comment]
Thanks!
