### ISSUE TITLE
Step 5 has duplicate lines

### ISSUE THREAD

**Issue by ckopotic** [pvcraven/arcade#444]
### Actual behavior:
Lines 51 - 53 are the same as 60 - 62
        # Used to keep track of our scrolling
        self.view_bottom = 0
        self.view_left = 0

### Expected behavior:
Not sure if the duplicate lines are intentional but if is then 60-62 should also be highlighted in step 5

### Where is it located?
http://arcade.academy/examples/platform_tutorial/index.html

**Comment by pvcraven** [comment]
That's on purpose.

The first set of lines 51-53 create the variable as part of the class. They need to be in the `__init__.

The second set of lines in the `setup` function will reset those values. Later on, when a person adds reset or multiple layer capability, you can call `setup` and make sure the view is reset to the start of the level.
