### ISSUE TITLE
Isometric Example complains about missing art assets

### ISSUE THREAD

**Issue by Morrolan** [pvcraven/arcade#445]
### Actual behavior:
When running the isometric example as documented:
```python
python -m arcade.examples.isometric_example
```
It generates:
```python
FileNotFoundError: [Errno 2] No such file or directory: 'isometric_dungeon/stone_W.png'
```

### Expected behavior:
If the art assets need to be downloaded and installed separately, I would expect instructions of where to place the assets directory.

**Comment by pvcraven** [comment]
Closing, the appears to have been fixed a while back, but never closed.
