### ISSUE TITLE
Add a minimal example that demonstrates the absolute basics of new View class

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#448]
The existing `different_screens_*.py` examples do a good job illustrating the different features of the `View` class.  But I was curious if it would help to have an even more minimal example of the `View` class in action.  Or, is this just too much duplication with the other example files?  Thoughts, @MrGallo?

**Comment by pvcraven** [comment]
New example docs are on-line:

http://arcade.academy/examples/index.html#view-management

You can add non-code explanations to the files as well, just update the RSTs that import them.

**Comment by pvcraven** [comment]
These docs are out.
