### ISSUE TITLE
Reenable Travis CI tests

### ISSUE THREAD

**Issue by cclauss** [pvcraven/arcade#453]
Turn on the repo switch at https://travis-ci.org/profile for the repo https://travis-ci.org/pvcraven/arcade

A manual test run may be required to prime the pump.

**Comment by pvcraven** [comment]
Manually triggered: https://travis-ci.org/pvcraven/arcade/builds/570867065

**Comment by pvcraven** [comment]
It is not auto-triggering, and I'm not sure why.

**Comment by cclauss** [comment]
Agreed.  #454 did not trigger a build.  The toggle switch is ON at https://travis-ci.org/profile?

You might need to switch over to .com  https://travis-ci.com/profile

**Comment by pvcraven** [comment]
Last push auto-triggered.

**Comment by cclauss** [comment]
Fixed.  Thanks.
