### ISSUE TITLE
Missing requirement for pytiled_parser

### ISSUE THREAD

**Issue by n-Holmes** [pvcraven/arcade#463]
### Actual behavior:
Installing the library via `pip install arcade` seems to work, but attempting to import arcade throws

    ModuleNotFoundError: No module named 'pytiled_parser'

After manually installing pytiled_parser, importing works fine. 

### Expected behavior:
`pytiled_parser` should be installed as a requirement during `pip install`.

### Versions
This issue happened with Python 3.7.4 on Windows whilst installing arcade 2.1.0

**Comment by pvcraven** [comment]
Requirement is listed in `requirements.txt`, but not in `setup.py` so it doesn't auto-load.

**Comment by pvcraven** [comment]
Fix deployed in 2.1.1.
