### ISSUE TITLE
Text drawing in Arcade is very slow

### ISSUE THREAD

**Issue by joezeng** [pvcraven/arcade#466]
## Bug Report

While creating my new game in Arcade, I've been creating screens that are simply to render the state of the game in text, so that I can verify that inputs and game state are working before implementing graphics. However, these screens have been running at a low 50 FPS instead of the 60 I expect them to run at, and I think I've figured out why.

### Steps to reproduce/example code:

I tried running the following program (importing Arcade 2.1.1):

```
"""
Text-rendering test
"""
import arcade
import random

# Constants
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Text-rendering test"

def generate_random_ascii_string():
    output = ""
    for i in range(100):
        output = output + chr(random.randint(33, 126))
    return output

class TextRenderingTest(arcade.Window):
    """
    Main application class.
    """

    def __init__(self):

        # Call the parent class and set up the window
        super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)

        arcade.set_background_color(arcade.color.BLACK)

    def setup(self):
        pass

    def on_draw(self):
        """ Render the screen. """

        arcade.start_render()
        # Code to draw the screen goes here

        arcade.draw_text(
            "{}\n{}\n{}\n{}".format(
                generate_random_ascii_string(),
                generate_random_ascii_string(),
                generate_random_ascii_string(),
                generate_random_ascii_string(),
            ), 2, 2, arcade.color.WHITE
        )

window = TextRenderingTest()
window.setup()
arcade.run()
```

This snippet renders 4 lines of 100 random characters each, as follows:

<img width="1112" alt="Screen Shot 2019-08-19 at 12 56 10 AM" src="https://user-images.githubusercontent.com/1137253/63240116-42607000-c21c-11e9-8adc-8c25d19a1dc4.png">

This program runs at about 6 FPS on my Macbook Pro. I ran the `py-spy` profiler to see what was going on, and the vast majority of time was taken by functions relating to `draw_text`:

```
  %Own   %Total  OwnTime  TotalTime  Function (filename:line)                                                                                                                        
 36.00%  36.00%    6.13s     6.13s   getmask2 (PIL/ImageFont.py:397)
 25.00%  25.00%    5.40s     5.40s   getsize (PIL/ImageFont.py:223)
 13.00%  13.00%    2.34s     2.35s   resize (PIL/Image.py:1892)
 11.00%  11.00%    2.54s     2.54s   getmask2 (PIL/ImageFont.py:395)
  5.00%   5.00%   0.630s    0.630s   walk (os.py:359)
  2.00%   2.00%   0.120s    0.130s   compile_shader (arcade/shader.py:249)
  2.00%   2.00%   0.740s    0.740s   text (PIL/ImageDraw.py:280)
  1.00%   1.00%   0.490s    0.540s   __call__ (pyglet/libs/darwin/cocoapy/runtime.py:755)
  1.00%  99.00%   0.160s    19.65s   on_draw (01_open_window.py:45)
  1.00%   1.00%   0.550s    0.550s   convert (PIL/Image.py:1056)
  1.00%   1.00%   0.010s    0.010s   _splitext (genericpath.py:135)
  1.00%   1.00%   0.020s    0.020s   truetype (PIL/ImageFont.py:579)
  1.00%   1.00%   0.210s    0.210s   render (arcade/shader.py:498)
```

Over 99% of the total time of the program was spent in `on_draw`, due to the time-consuming text drawing procedure.

What could be the problem here? You seemed to have fixed it in #102 but apparently now the problem's back. My first hunch is that you're loading a new PIL image font every single time you draw text, and that might be causing the trouble.

**Comment by pvcraven** [comment]
Text is rendered as a texture, so creating new text each frame will be very slow.

**Comment by joezeng** [comment]
Is there any way to do it without rendering to texture? I feel like there's more to it than that given that similar strings rendered in LÖVE aren't nearly as slow, and I don't think the choice of language should affect OpenGL text rendering.

I'll try using Pyglet text drawing next and see what happens.

**Comment by pvcraven** [comment]
It has to do with using OpenGL shaders. Older Pyglet does not use shaders, but newer Pyglet 2.0 will. You are correct, it is independent of the language.

Using shaders allows for very fast and flexible drawing, but the bitmap needs to be loaded to the graphics card first as a separate operation. If you keep changing the bitmap, it is a slow operation. I'm not currently sure of how to make that faster.

I've seen some folks with ModernGL doing some interesting things with fonts lately, but I'm not sure if it is faster or not.

**Comment by joezeng** [comment]
Could I somehow specifically render text without shaders?

**Comment by joezeng** [comment]
Also, your text drawing method appears to draw to an upscaled bitmap using PIL and then scale it down again using Lanczos interpolation.

That would significantly slow things down, very plausibly to the point of taking 1/6 second to downscale a 4000 x 500 bitmap. I have a hunch that simply switching to a bilinear filter for downscaling would make things much faster.

**Comment by joezeng** [comment]
Alright, I got home and tried it, and it seems even reducing the amount the image upscales doesn't work — PIL still takes too long to draw the text to canvas.
