### ISSUE TITLE
Most of the examples crash or work incorrectly on Mac due to Pyglet issues

### ISSUE THREAD

**Issue by ageitgey** [pvcraven/arcade#467]
## Bug Report

Thanks for this cool library - it looks great and will be fun to play with! 

I was trying it out on a Mac, but almost all the examples crashed or were unusable. However I believe it is not the fault of this library and is related to bugs in pyglet. Despite that, I thought it was worth at least documenting for other users since things aren't currently working as expected on Mac.

### Actual behavior:

1. ~~Examples that set the window size via code will fail to resize the window. The window stays the default size.~~ (Fixed by upgrading to Pyglet 1.4.2)
1. In the resizeable_window example, the window can't be resized by the user. Grabbing a resize handle freezes or crashes the program.
1. ~~Any example programs using the mouse will map the mouse input to only the bottom left 1/4 of the window area instead of the whole window area. I believe this is because arcade asked Pyglet to resize the window and assumes it did, but it didn't actually happen which throws off the coordinate space calculations.~~ (Fixed by upgrading to Pyglet 1.4.2)
1. All examples segfault when you click the red "window close" button in the window toolbar.

I believe all of these issues are inter-related and due to https://github.com/pyglet/pyglet/issues/5 - the root issue is that window resizes aren't working at all in Pyglet/PyCocoa on newer Macs.

### Expected behavior:

1. None of the above things should happen.

### Steps to reproduce/example code:

1. Run any of the example programs using python.org's Python 3.7.* builds on macOS 10.14 Mojave on a recent Macbook Pro and arcade 2.1.1 / pyglet 1.4.0b1.

Again, I believe the root cause is https://github.com/pyglet/pyglet/issues/5 in pyglet and not the fault of this library. But unfortunately that means everything is currently broken on the Mac.

**Comment by pvcraven** [comment]
You definitely need Pyglet 1.4.2, and it won't work with Pyglet 1.4.0b1. The examples mostly seem to run for me, except the window resize.

**Comment by pvcraven** [comment]
Ah looks like in setup.py it tries to lock to an earlier version of Pyglet. I'll have to do another release to fix that.

**Comment by ageitgey** [comment]
Thanks for taking a look, @pvcraven! W

ith Pyglet 1.4.2, issues #1 and #3 above are fixed and issues #2 and #4 remain (at least on my system).

**Comment by ageitgey** [comment]
@pvcraven What version of macOS are you running? I'm on 10.14.6 (18G87). It sounds like from the pyglet / pycocoa issues that the crash is probably only happening on newer macOS versions. But who knows?

I'm pretty much getting exactly what is reported in https://github.com/pyglet/pyglet/issues/5, but I've attached fresh stack traces in case they are helpful.

Here's the segfault reported on the Python side:
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1121, in objc_method
    result = f(py_self, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/window/cocoa/pyglet_window.py", line 65, in nextEventMatchingMask_untilDate_inMode_dequeue_
    if self.inLiveResize():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 785, in __call__
    return self.method(self.objc_id, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 755, in __call__
    result = f(objc_id, self.selector, *args)
ctypes.ArgumentError: ("argument 1: <class 'RecursionError'>: maximum recursion depth exceeded in __instancecheck__", "selector = b'inLiveResize'", "argtypes =[<class 'ctypes.c_void_p'>, <class 'ctypes.c_void_p'>]", "encoding = b'c16@0:8'")
Segmentation fault: 11
```

And here's the segfault reported by macOS:

```
Process:               Python [86998]
Path:                  /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.7.4 (3.7.4)
Code Type:             X86-64 (Native)
Parent Process:        bash [56127]
Responsible:           Python [86998]
User ID:               501

Date/Time:             2019-08-28 15:18:25.771 +0100
OS Version:            Mac OS X 10.14.6 (18G87)
Report Version:        12
Bridge OS Version:     3.0 (14Y904)
Anonymous UUID:        405259AF-82DC-2EA5-E5C1-9027A2FDE60E

Sleep/Wake UUID:       1D98BE41-EE98-4D73-98EE-98618DF490CB

Time Awake Since Boot: 380000 seconds
Time Since Wake:       21000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [86998]

VM Regions Near 0x18:
--> 
    __TEXT                 000000010eea1000-000000010eea2000 [    4K] r-x/rwx SM=COW  /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python

Application Specific Information:
objc_msgSend() selector name: type


Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff6251169d objc_msgSend + 29
1   com.apple.AppKit              	0x00007fff35e5886b __46-[NSDragEventTracker trackEvent:usingHandler:]_block_invoke.51 + 54
2   com.apple.AppKit              	0x00007fff35cc7814 -[NSWindow(NSEventRouting) trackEventsMatchingMask:timeout:mode:handler:] + 285
3   com.apple.AppKit              	0x00007fff356ed99c -[NSDragEventTracker trackEvent:usingHandler:] + 1571
4   com.apple.AppKit              	0x00007fff356eceed -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 1875
5   com.apple.AppKit              	0x00007fff3571b29c -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 698
6   com.apple.AppKit              	0x00007fff356ebb1e -[NSControl mouseDown:] + 791
7   com.apple.AppKit              	0x00007fff3575525d -[_NSThemeWidget mouseDown:] + 86
8   com.apple.AppKit              	0x00007fff355c7937 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5724
9   com.apple.AppKit              	0x00007fff354fe1a6 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2295
10  com.apple.AppKit              	0x00007fff354fd667 -[NSWindow(NSEventRouting) sendEvent:] + 478
11  com.apple.AppKit              	0x00007fff3539ce6b -[NSApplication(NSEvent) sendEvent:] + 331
12  _ctypes.cpython-37m-darwin.so 	0x000000010f620177 ffi_call_unix64 + 79
13  _ctypes.cpython-37m-darwin.so 	0x000000010f6209d8 ffi_call + 872
14  _ctypes.cpython-37m-darwin.so 	0x000000010f61b99b _ctypes_callproc + 891
15  _ctypes.cpython-37m-darwin.so 	0x000000010f615a00 PyCFuncPtr_call + 1040
16  org.python.python             	0x000000010eec8707 PyObject_Call + 135
17  org.python.python             	0x000000010ef84b9e _PyEval_EvalFrameDefault + 25966
18  org.python.python             	0x000000010ef88413 _PyEval_EvalCodeWithName + 2467
19  org.python.python             	0x000000010eec817b _PyFunction_FastCallDict + 523
```

**Comment by olehermanse** [comment]
> @pvcraven What version of macOS are you running? I'm on 10.14.6 (18G87). It sounds like from the pyglet / pycocoa issues that the crash is probably only happening on newer macOS versions. But who knows?

@ageitgey Hello, I'm the one who's been looking at this issue in pyglet. It seems to happen on newer mac models, while not on older macs, with the same OS version.

Would be great if someone with better knowledge of Cocoa could take a look. More details here:

https://github.com/pyglet/pyglet/issues/5#issuecomment-536324906

**Comment by pvcraven** [comment]
I'm running Mojave 10.14.6 on a Late 2014 Mac Mini.

I do have students with Mac Books that get the crash.

**Comment by pvcraven** [comment]
Closing. Tracking the 'closing' problem with Issue #382.
