### ISSUE TITLE
GUI ELEMENTS

### ISSUE THREAD

**Issue by wamiqurrehman093** [pvcraven/arcade#475]
## Bug Report
Arcade does not have GUI elements like buttons, text boxes, radio or select boxes etc

### What should be added/changed?
It should have GUI and it can be done by adding a file in the arcade folder. The file should have classes or functions to help with the GUI like there should be a class for Button or multiple classes with one being the Base Class. Same can be done with other elements such as Text Box.
### What would it help with?
It is going to help developers getting the GUI elements ready made instead of writing their own every time they want to use some!

**Comment by wamiqurrehman093** [comment]
I have wrote the code for basic text buttons and added test as well. It works. Now should I do pull request?

**Comment by laticoda** [comment]
Hi, have a look here, maybe something to recycle to gain time.
[https://glooey.readthedocs.io/en/latest/getting_started.html](url)

**Comment by pvcraven** [comment]
Some basic support added in 2.1.7
