### ISSUE TITLE
Processing object layer raises an exception

### ISSUE THREAD

**Issue by eruvanos** [pvcraven/arcade#478]
## Bug Report
Processing object layer raises an exception

### Actual behavior:
Raises Error:
```
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
```
### Expected behavior:
Providing list of objects

### Steps to reproduce/example code:
Create new map file with an object layer, add a rectangle object, without adding any data.
Load the map and process object layer:

```
import arcade
map = arcade.tilemap.read_tmx('test_object.tmx')
layer = arcade.tilemap.process_layer(map, 'objects')
```

**Comment by pvcraven** [comment]
Was able to reproduce, thanks.

**Comment by pvcraven** [comment]
The `process_layer` function creates sprites out of the specified layer. If the object in the layer is not a sprite (like a rectangle object) we need to come up with the correct behavior. (Ignore, give warning, throw a better error, represent in some other fashion, ?)

I'm not sure what the best thing to do is here. (Not crash with an indecipherable error, obviously.) Open to suggestions.

**Comment by eruvanos** [comment]
Just found another bug,
creating an object from a tile without adding properties raises an error:

## Steps:

Same like in the top, but creating an object from a tile, without adding properties.

## Actual behavior
```
TypeError: 'NoneType' object is not iterable.
```

 Should I open another issue for this?

**Comment by eruvanos** [comment]
> The `process_layer` function creates sprites out of the specified layer. If the object in the layer is not a sprite (like a rectangle object) we need to come up with the correct behavior. (Ignore, give warning, throw a better error, represent in some other fashion, ?)
> 
> I'm not sure what the best thing to do is here. (Not crash with an indecipherable error, obviously.) Open to suggestions.

So my goal would be to have an object layer containing points, rectangles, and ellipses, to implement some scenarios like:
* Player reaches finish zone
* Player is in an interaction area
* Find player start position

So having the plain object layer from `arcade.tilemap.get_tilemap_layer(my_map, 'places')` and have some helper method to check wether a sprite is colliding with something from that layer would be nice.

My first idea would be:
```
places = arcade.tilemap.get_tilemap_layer(my_map, 'places')
start_pos = places.find(name='start') # or type; could also return a list
player.position = start_pos.location

# ...

finish_zone = layer.find(name='finish') # or type
if arcade.check_for_collides_with_object(player, finish_zone):
    pass

# or
colliding_places = arcade.check_for_collides_with_objects(player, places)

for place in colliding_places:
    if place.name == 'finish':
        pass
```

**Comment by pvcraven** [comment]
Adding to enhancement list. 
http://arcade.academy/enhancement_list.html
