### ISSUE TITLE
Error when importing arcade on Raspberry Pi 4 (Raspbian GNU/Linux 10 (buster))

### ISSUE THREAD

**Issue by Lima-Codes** [pvcraven/arcade#485]
## Bug Report
This bug is specific to ARM Raspberry Pi 4 devices.

A fix is proposed in Enhancement request section.

When trying to import arcade for the first time after installation in Python 3, an IndexError is thrown when the script pyglet_ffmpeg2/loader.py calls the function `_ensure_linux_symlinks`

### Actual behavior:
`load.py` fails to create symlinks because the path defined in the `bin_folder` variable defined by the function `_locate_binaries` uses
~~~python
path = os.path.join(this_dir, 'linux_x86_64')
~~~
instead of:
~~~python
path = os.path.join(this_dir, 'RPi')
~~~

because `sys.platform` returns 'linux' instead of the expected 'armv7l' in the conditional block:
~~~python
if 'armv7l' in sys.platform:
    path = os.path.join(this_dir, 'RPi')
else:
    path = os.path.join(this_dir, 'linux_x86_64')
~~~
### Expected behavior:
`sys.platform`  should return 'armv7l' and symlinks can be created

### Steps to reproduce/example code:
 - Install Raspbian GNU/Linux 10 (buster) on Raspberry Pi 4
- Upgrade pip3
- Run `pip3 install arcade`
- Start python 3 and import arcade

### What should be added/changed?
In `/usr/local/lib/python3.7/dist-packages/pyglet_ffmpeg2/loader.py`, change the condition on line 50 from this:
~~~python
if 'armv7l' in sys.platform
~~~

to this:
~~~python
if 'armv7l' in sys.platform or 'armv7l' in os.uname()
~~~

### What would it help with?
`os.uname()` returns more comprehensive and useful info on the OS and hardware

In addition, the `os` module is already imported in the load.py file

**Comment by pvcraven** [comment]
Passed to Pyglet team

**Comment by pvcraven** [comment]
Update pyglet-ffmpeg2 package and see if the fix is working for you.

**Comment by pvcraven** [comment]
Hopefully fixed? Closing. Reopen if not fixed
