### ISSUE TITLE
AttributeError: module 'arcade' has no attribute 'tilemap' 

### ISSUE THREAD

**Issue by mrwree14** [pvcraven/arcade#487]
I'm try to work through you platformer tutorial and have run into an error:

 my_map = arcade.tilemap.read_tmx(map_name)
AttributeError: module 'arcade' has no attribute 'tilemap'

i looked at the API and found arcade.tilemap.read so im not sure whats going on, is there a solution or am i missing something?

i saw another thread about some issues with arcade and tiled map editor, is there something that would work better that tiled? (i like tiled and would rather just get this error fixed)

**Comment by pvcraven** [comment]
Can you check to make sure you don't have a file names 'arcade.py' that is
getting imported instead?

**Comment by mrwree14** [comment]
i have looked through all my folders and cannot find any 'arcade.py' file

**Comment by pvcraven** [comment]
Next thing I'd check is to make sure you have the latest version of Arcade.

**Comment by mrwree14** [comment]
arcade installed using pip. arcade up to date, pip is not. i tried the upgrade pip command, so now both are up to date and still i get the same error for the platformer.

**Comment by mrwree14** [comment]
im using pycharm and when looking at the code pycharm shows an error, using f2 to cycle through problems in the code it pops up with "create a function tilemap() in module __init__.py"

**Comment by pvcraven** [comment]
Closing, was unable to replicate. Reopen if more detail is available.
