### ISSUE TITLE
Transparency not working in draw functions

### ISSUE THREAD

**Issue by chpurdy** [pvcraven/arcade#489]
### Actual behavior:
When using any of the draw_rectangle_filled, draw_circle_filled, etc. functions and using a color with transparency, ie. (255, 0, 0, 0) there is no transparent effect.  The shape appears as normal no matter what alpha value is used.

### Expected behavior:
I assumed if a color with transparency was used to fill a shape, there would be transparency and you would be able to see other shapes drawn behind it.

### Steps to reproduce/example code:
``` python
import arcade
arcade.open_window(600, 600, "test")
arcade.set_background_color(arcade.color.WHITE)
arcade.start_render()
arcade.draw_rectangle_filled(200, 200, 300, 300, (0,0,255,255))

# thought you should be able to see the rectangle above through this rectangle
arcade.draw_rectangle_filled(150, 150, 300, 300, (0,255,0,10))
arcade.finish_render()
arcade.run()
```

**Comment by pvcraven** [comment]
Verified. Seems like this has been around since 2.0, which seems weird because I really thought it was working by with 2.0.

**Comment by pvcraven** [comment]
Apparently it was working back in June? Issue #421.

**Comment by laticoda** [comment]
this may help you:
transparency does work at the beginning of this game  when you drop your units : green and red circle with transparency when hovering right or wrong positions:
[https://github.com/BlakeDalmas/Python/tree/master/The%20Great%20Skeleton%20War](url)

**Comment by pvcraven** [comment]
Should be fixed
