### ISSUE TITLE
order of parameters in draw_ellipse documentation

### ISSUE THREAD

**Issue by chpurdy** [pvcraven/arcade#490]
### What documentation needs to change? 
`draw_ellipse_filled` and `draw_ellipse_outline` parameters descriptions.

### Where is it located?
[documentation](http://arcade.academy/arcade.html?highlight=create_rectangle_filled) and the docstring for the functions.

### What is wrong with it? How can it be improved?#
The parameters listed for draw_ellipse_filled and draw_ellipse_outline have height listed before width in the docstring and API documentation.  It seems like this should be consistent with the order of the parameters in the function signature.

**Comment by pvcraven** [comment]
Should be updated now. Will close once confirmed it is pushed out to the cloud.

**Comment by pvcraven** [comment]
Fixed
