### ISSUE TITLE
need more example with slow displaying pitfall and tips. Are my loops wrong ?

### ISSUE THREAD

**Issue by laticoda** [pvcraven/arcade#504]
### What would it help with? A blog with forum,  error and solutions snippets. Arcade is really great, a place for sharing experience is needed.
Participation at game jams to show more code and make promotion. A lot of people are stuck on pygame which is ageing. 

## Documentation request: stressing cpu and gpu code example to put limit farer.
I would like shaders. Does modernGL can help ?

**Comment by pvcraven** [comment]
Hi, sorry. Having trouble understanding.

I'd suggest posting sample code somewhere that demonstrates the slow code.
