### ISSUE TITLE
Geometry fonction for detecting collision circle drawn with arcade.draw_circle

### ISSUE THREAD

**Issue by laticoda** [pvcraven/arcade#505]
I have trouble for detecting circles collision, (no sprite on it).
how to use are_polygons_intersecting() with circles ?

**Comment by pvcraven** [comment]
There isn't anything set up right now for circle collision. 

In the case of sprites, creating a polygon that roughly matches the circle would be the way to go.

If you aren't using sprites, adding the radius of both items, and seeing if it is less than the distance between the centers would be the way to go.
