### ISSUE TITLE
Text with custom fonts is cut off at larger sizes

### ISSUE THREAD

**Issue by alex-gale** [pvcraven/arcade#515]
## Bug Report
When using a custom font, descenders are cut off on text.
![image](https://user-images.githubusercontent.com/12378975/68075065-f9d83d80-fd9a-11e9-8e84-27e0c3862ba6.png)
(font here is Courgette)

### Actual behavior:
Descenders are cut off from text, as if a maximum height is applied to the text

### Expected behavior:
Text is rendered to the correct height

### Steps to reproduce/example code:
```arcade.draw_text("You Lose", 400, 400, (0,0,0), 25, font_name="Courgette-Regular.ttf", anchor_x="center", anchor_y="center")```
(it happens with any custom font, this one happens to be cursive)

**Comment by pvcraven** [comment]
Fixed with version 2.2.8.

**Comment by simensgreen** [comment]
arcade version 2.6.3 cut off returns at default font, UILabel
![image](https://user-images.githubusercontent.com/34134129/136283317-b1f7fe7a-9e23-4d54-89b6-f1fbfc3b81ad.png)

**Comment by einarf** [comment]
> arcade version 2.6.3 cut off returns at default font, UILabel ![image](https://user-images.githubusercontent.com/34134129/136283317-b1f7fe7a-9e23-4d54-89b6-f1fbfc3b81ad.png)

Can you put this in a new issue with a small code snippet?
