### ISSUE TITLE
arcade.stop_sound() not working (ubuntu)

### ISSUE THREAD

**Issue by hsweet** [pvcraven/arcade#519]
## Bug Report
arcade.stop_sound(sound) error

### Actual behavior:
/home/harry/.local/lib/python3.6/site-packages/arcade/sound.py in stop_sound(sound)
     89     :param sound:
     90     """
---> 91     sound.pause()
     92 
     93 

AttributeError: 'Sound' object has no attribute 'pause'
### Expected behavior:
Should stop sound... I'm using a background sound.  

### Steps to reproduce/example code:
sound = arcade.load_sound("somesound.wav")
arcade.play_sound(sound)
... on some event later on
arcade.stop_sound(sound)

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html

**Comment by ScotterMonk** [comment]
Yes, please fix. I build a game using this super useful library but now I'm stuck finishing it until I can get sound_stop to work. Thank you! Apology if my comment should go somewhere else. This is the only place I knew of to throw in my two cents :-)

**Comment by hsweet** [comment]
I'd be happy to give it a shot, but other than randomly fishing around in
github, I have no idea where to start.  That said, I liked working with
Arcade with my class this fall.  Even with the bug.
