### ISSUE TITLE
Add z order support

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#52]
Right now the sprites default to a opengl z-order (or z-coordinate really) of 0.5. Add support for a sprite property that allows the user to specify the z location instead of always using 0.5.

**Comment by pauleveritt** [comment]
I was reading in [recent pyglet-users threads](https://groups.google.com/forum/#!topic/pyglet-users/zj6L_617w3k) that this is a pretty ugly part of OpenGL and pyglet.

**Comment by pvcraven** [comment]
I remember it not being as easy as it should. Like there was an API for it, that seemed to ignore what we put it. Been a while though.

**Comment by pvcraven** [comment]
Sprite drawing order done by where the sprite is in the list. I don't see supporting z-order in the immediate future.
