### ISSUE TITLE
_process_object_layer() crashes when adding non-existent properties

### ISSUE THREAD

**Issue by JFincher42** [pvcraven/arcade#529]
## Bug Report

During the processing of an object layer, `arcade` crashes when executing `my_sprite.properties.update(cur_object.properties)`, with a NoneType is not iterable error

### Actual behavior:

Game crashes when loading second map

### Expected behavior:

No crash

### Steps to reproduce/example code:

The tileset used for my game has been modified between map levels. The first level opens properly - there, the tiles have custom properties added to the tiles on the object layer. For the second layer, custom properties were added to the tiles in the tileset. This may be causing the problem.

### What should be added/changed?

The fix is to add a check `if cur_object.properties is not None:` before calling `my_sprite.properties.update(cur_object.properties)`. PR coming shortly.

**Comment by pvcraven** [comment]
Implemented in release 2.2.0
