### ISSUE TITLE
Arcade should make its type hinting available to other modules via PEP 561

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#533]
## Bug Report
Arcade has type hints, but that type hinting information isn't exposed for other modules to use it. See the [mypy docs ](https://mypy.readthedocs.io/en/latest/installed_packages.html) and [PEP 561](https://www.python.org/dev/peps/pep-0561/) for more details.

### Actual behavior:

When running mypy against a project that relies on arcade, mypy reports that "arcade" does not provide type hinting:

```
$ mypy src/
src\myapp.py:4: error: Cannot find implementation or library stub for module named 'arcade'
```

### Expected behavior:

A project that depends on the arcade package should be able to leverage arcade's type hinting.

### The fix
A PR is forthcoming...

**Comment by pvcraven** [comment]
Is this fixed now with the PR?

**Comment by SirGnip** [comment]
Hm.  It appears the PR got it further but it is not 100% working.  If I install arcade 2.2.1, create a script named "test.py" that contains:

```
import arcade
print(arcade.Sprite())
```

...and run mypy on it like this:

```
$ venv/Scripts/mypy test.py --strict
test.py:2: error: Module has no attribute "Sprite"
Found 1 error in 1 file (checked 1 source file)
```

...it appears that mypy is able to use arcade's type hinting info (no more "Cannot find implementation or library stub for module named 'arcade'" error).  But, it can't find the specific Sprite class.  I'm guessing that is because of the `import *` syntax in `arcade/__init__.py`?  If I create `test2.py` with this snippet:

```
from arcade.sprite import Sprite
print(Sprite())
```

...and run mypy...

```
$ venv/Scripts/mypy test2.py --strict
Success: no issues found in 1 source file
```

...mypy reports no issues.

Unfortunately, refactoring `arcade/__init__.py` and not breaking backwards compatibility with existing scripts (import paths, etc) is beyond the time I have available right now.  This might be a helpful starting point on mypy's behavior with "star" imports: https://github.com/python/mypy/issues/4930

**Comment by pvcraven** [comment]
The master branch has a lot of work on it already, but yeah. It isn't proving to be easy:

https://github.com/pvcraven/arcade/blob/master/arcade/__init__.py

**Comment by SirGnip** [comment]
Ah!  I hadn't fetched in a couple weeks so I didn't notice this.  I'll do a fetch and see how things look with the new __init__.py.

**Comment by SirGnip** [comment]
My mind is mush.  I forgot about https://github.com/pvcraven/arcade/issues/537.  I'd consider this issue (#534 ) complete and #537 will make it fully functional,

**Comment by pvcraven** [comment]
How is this working?

**Comment by pvcraven** [comment]
Fixed in current versions.
