### ISSUE TITLE
Tiles in object layers are not placed properly

### ISSUE THREAD

**Issue by JFincher42** [pvcraven/arcade#535]
## Bug Report

When processing an object layer of a tilemap, the objects are not placed properly. This causes them to be rendered in the wrong place, possibly making them collide with other tiles on the screen.

The problem appears in `_process_object_layer()', when setting the sprite location. Instead of setting the  `.right` and `.top` properties, it should set the `.left` and `.bottom` properties. This accounts for the zero-index nature of the tilemap, and the y-axis flip between `arcade` and Tiled.

PR with this change forthcoming.

### Actual behavior:

Tiles are placed one tile width to the left and one tile height lower than they should be.

### Expected behavior:

Tiles are placed where they were found in the tile map

### Steps to reproduce/example code:

Read in a tile map with an object layer. Note where tiles are placed when rendered in `arcade` as opposed to where they are placed in Tiled.

**Comment by pvcraven** [comment]
Implemented in release 2.2.0
