### ISSUE TITLE
Draw bug/problem in arcade 

### ISSUE THREAD

**Issue by pablo2811** [pvcraven/arcade#540]
So long story short i'm coding chess game (newbie to arcade) and i wanted to create a pop-up window informing player that check has occured.

So in order to do so, i leave main game class using :
            
            arcade.close_window() #close the current game window
            Check(self.core, self.tura) #create new window
            arcade.run() #run it

And "go back" to main game class by:

        arcade.close_window() #close "informing" window
        MyGame(WIDTH,HEIGTH,TITLE,self.core,self.tura) #open up the game once again
        arcade.run() #run "the game"

After reopening main game class,  the following drawing command (used to draw board):

tex.draw(center_x=fig.x * 60 + 30, center_y=fig.y * 60 + 30, width=60, height=60) 

(for context: fig -> object representing figure on board (x,y) - coordinates, 
tex -> its png representant(picture))

**produce such an error:**
```
Traceback (most recent call last):
  File "C:\Users\fijal\Anaconda3\lib\weakref.py", line 628, in _exitfunc
    f()
  File "C:\Users\fijal\Anaconda3\lib\weakref.py", line 552, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\fijal\Anaconda3\lib\site-packages\arcade\shader.py", line 134, in _delete
    gl.glDetachShader(prog_id, shader_id)
  File "C:\Users\fijal\Anaconda3\lib\site-packages\pyglet\gl\lib.py", line 106, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'nieprawid\xb3owa warto\x9c\xe6'
```
Whats important, before changing window to "Check" and going back to main game class, everything works perfectly well and there are no errors.

As i've mentioned, i'm quite new to Arcade, so if you have some other ideas how to create such pop-ups or know what to do to avoid this problem i will be grateful for an advice.

**Comment by pvcraven** [comment]
I wonder if it is attempting to draw in the old window? Hard to tell what OpenGL is unhappy about.

I'd try making as small a code example as you can that boils it down to the basics that can reproduce the error. Then upload on git or similar so it can be debugged.

**Comment by pvcraven** [comment]
Closed due to lack of new information.
