### ISSUE TITLE
Folder 'resources' missing

### ISSUE THREAD

**Issue by mdob2k** [pvcraven/arcade#541]
## Bug Report
Unable to load resource-files, the folder arcade/resources is missing in release v2.2.0.
:resource:  points to [python_path]/lib/site-packages/arcade/resources/ which does not exist
### Actual behavior:
Built-in examples won't run due to missing resource-files:
Unable to load :resources:images/animated_characters/female_person/femalePerson_idle.png [Errno 2] No such file or directory

### Steps to reproduce/example code:
Run any of the included examples, for example:
python -m arcade.examples.sprite_move_keyboard_better

### What should be added/changed?
The folder 'resources' should be included after pip install arcade

**Comment by pvcraven** [comment]
Version 2.2.1 pushed out. Please check, but should be fixed.
