### ISSUE TITLE
Allow to control thought command line or debug? 

### ISSUE THREAD

**Issue by Fronzilla** [pvcraven/arcade#542]
## Enhancement request:
Game in arcade typically start with following.     
window = MyGame()
window.setup()
arcade.run()

Is there any way to control player thought command line or debug? Something like: the world is rendered, player can't move until you execute command like player.move_right() or player.move_left() in command line or in debug mode in PyCharm?

**Comment by pvcraven** [comment]
That's more of a turtle-like setup. I'm not sure how something like this would integrate very will into the current library. I could see a separate project to do something similar, built using an Arcade back-end.

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html
