### ISSUE TITLE
Installation on ubuntu and raspberry pi 3

### ISSUE THREAD

**Issue by OfirFlaysher** [pvcraven/arcade#543]
### What documentation needs to change? 
Ubuntu Installation Instructions

### Where is it located?
http://arcade.academy/installation_linux.html

### What is wrong with it? How can it be improved?
I get "pyglet.window.xlib.XlibException: Could not create UTF8 text property".
I follow the solution [here](https://stackoverflow.com/questions/41508988/python3-and-pyglet-help-needed) and it worked.

### What documentation needs to change? 
Raspberry Pi Installation Instructions

### Where is it located?
http://arcade.academy/installation_linux.html

### What is wrong with it? How can it be improved?
I get "pyglet.gl.ContextException: Could not create GL context".
Also, the latest raspbian comes with python 3.7.
Are the instructions on the docs works with raspberry pi 3? raspberry pi 4 is capable of OpenGL ES 3.2 where raspberry pi  3 only OpenGL ES 2.0.

**Comment by pvcraven** [comment]
Moving to enhancement list. Reopen as needed.
http://arcade.academy/enhancement_list.html

**Comment by pvcraven** [comment]
I think this is two separate requests.

Raspberry Pi does not support OpenGL 3.3 or above, which Arcade requires. Therefore I don't see support for that platform coming any time soon. The second is that Linux might need updated instructions.
