### ISSUE TITLE
Typo on some path variables.

### ISSUE THREAD

**Issue by Howld** [pvcraven/arcade#544]
### What documentation needs to change? 
`
image_source = ":resources:images/animated_characters/female_adventurer/femaleAdventurer_idle.png"
`

### Where is it located?
http://arcade.academy/examples/platform_tutorial/index.html

### What is wrong with it? How can it be improved?
Should do remove ':resources:' string.

**Comment by pvcraven** [comment]
With the current 2.2.1 library, it should work. The `:resources:` will auto-load from the source code's resources library and not require people to download image files to try code.

See: http://arcade.academy/resources.html
