### ISSUE TITLE
Website documentation for resources suggestions

### ISSUE THREAD

**Issue by MrGallo** [pvcraven/arcade#549]
Suggestions for the [Resources page](http://arcade.academy/resources.html)

- Fix typo for the tag from `:resource:` to `:resources:` in second paragraph
- Add an example usage such as:
    ```python
    player = arcade.Sprite(":resources:/images/animated_characters/male_adventurer/maleAdventurer_idle.png")
    ```
- Headers could be in the format `:resources:/gui_themes/Fantasy/Buttons/`
    - Including the `:resources:` tag and a trailing `/` to indicate the last thing is a directory
- File names should include the file extensions.

**Comment by pvcraven** [comment]
Updated with 2.2.5. Might take a bit for the cloud to update.
