### ISSUE TITLE
Feature request: arcade.draw_text() to return text_sprite

### ISSUE THREAD

**Issue by MrGallo** [pvcraven/arcade#564]
I think it might be useful to have `arcade.draw_text()` return the `text_sprite` it creates to have access to  potentially important information like the `width` and `height` of the text. It will also give the ability to check for collisions with other sprites, I guess more importantly, check for collision with the mouse location.

Example usage:
```python
# draw and get the sprite
title_sprite = arcade.draw_text("Menu", width//2, height//2, arcade.color.BLACK, anchor_x="center")
# underline the text
arcade.draw_line(title_sprite.left, title_sprite.bottom, title_sprite.right, title_sprite.bottom, arcade.color.BLACK, line_width=5)
```

**Comment by pvcraven** [comment]
Closed with release of 2.2.7.
