### ISSUE TITLE
Sprite.draw() call to draw_texture_rectangle causing error.

### ISSUE THREAD

**Issue by MrGallo** [pvcraven/arcade#570]
The `repeat_count_x` and `repeat_count_y` in this function call is causing an error. `arcade==2.2.8`

https://github.com/pvcraven/arcade/blob/136569ccf5c7bb224bad63f19b7441cd73a4271e/arcade/sprite.py#L704-L708

`TypeError: draw_texture_rectangle() got an unexpected keyword argument 'repeat_count_x'`

**Comment by pvcraven** [comment]
Thanks. Would have expected mypy to have caught that.

**Comment by pvcraven** [comment]
Should be ok in 2.3.0. Please test.
