### ISSUE TITLE
Give dual_stick_shooter example an interactive joystick configuration View

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#571]
A simple integer switch (`SHOOTING_AXIS_SELECTION`) was added to dual_stick_shooter.py to handle the lack of standardization in joystick layout.  This works, but doesn't handle all cases and potentially requires the student to tinker with the code to get their joystick to work.

I'm pushing up a PR to show what it would take to have an interactive way for the user to configure their joystick each time the example is launched.  It allows for lots of flexibility to support most dual-stick joysticks.  But, it does bloat the example (320-ish vs 400-ish lines).  Is this worth doing?  Or, is a simple-but-fiddly example better than this more complex multi-View example?

**Comment by pvcraven** [comment]
Fixed in 2.3.3.
