### ISSUE TITLE
Incorrect scaling cached sprites

### ISSUE THREAD

**Issue by NathanWilliams** [pvcraven/arcade#573]
## Bug Report

I am using arcade-2.2.8 on macOS (10.13.6).
When rendering a sprite with scaling, every sprite (of the same image) after the first is scaled twice.

### Actual behavior:

Cached sprites use incorrect scaling

### Expected behavior:

Cached sprites should behave identically to the initial sprite.

### Steps to reproduce/example code:

This is visible in the platformer.py example:
![Screen Shot 2020-01-29 at 7 10 02 pm](https://user-images.githubusercontent.com/1001203/73338967-d0607c80-42cb-11ea-8839-438224e1961a.png)

I have done some digging, and found the problematic bit of code here:
https://github.com/pvcraven/arcade/blob/fe77c919c4a65595511bfafd434abeb2a06ba6c4/arcade/drawing_support.py#L435-L436

If I disable this cache (eg hardcoding a can_cache=False), the sprites render correctly.
I was also able to fix it with the following change:

```
if can_cache and cache_name in load_texture.texture_cache: 
    texture = load_texture.texture_cache[cache_name]
    source_image = texture.image
    return Texture(cache_name, source_image)
```

However I don't know the code base well enough to be confident this doesn't have other side effects.

As an aside, while investigating this, I noticed you use the scale in the cache_name, but the scale isn't passed in from Sprite.__init__. Not sure if this matters (it doesn't impact this bug), but thought I would point it out while I noticed it.

**Comment by pvcraven** [comment]
Argh.

**Comment by pvcraven** [comment]
Caused by attempted fix for Issue #516.

**Comment by pvcraven** [comment]
2.2.9 was release, which is basically a roll-back to 2.2.7. Continuing to work on this.

**Comment by pvcraven** [comment]
Should be ok in 2.3.0. Please test.

**Comment by NathanWilliams** [comment]
Just installed 2.3.1 and the platformer example works as expected.
Thanks for the quick response.
