### ISSUE TITLE
Simplify reference to resources

### ISSUE THREAD

**Issue by MrGallo** [pvcraven/arcade#574]
## Enhancement request:
It would be cool to have an easier way to reference resources (much like arcade.key, or arcade.color).

For example, do this or something similar:
```python
sprite = arcade.Sprite(arcade.resources.male_person_idle)
```

I'm always having to check the website for the proper paths. Lazy.

**Comment by pvcraven** [comment]
I really like this idea. 

To do this, it would need a program to auto-create, and update to the program that creates the docs as well. And then (step 2) update all the examples.
