### ISSUE TITLE
Enhancement request: Volume control for sounds

### ISSUE THREAD

**Issue by ScotterMonk** [pvcraven/arcade#577]

**Comment by pvcraven** [comment]
This would be great, if we could get someone to work on it. I'd also like to see some ability to control L/R volume.

Moving to enhancement list. Please anyone starts working on this, please comment so it gets reopened.

http://arcade.academy/enhancement_list.html

**Comment by pvcraven** [comment]
Reopening, should be possible under Issue #372.

**Comment by chpurdy** [comment]
This seems to work now by passing in the volume to play and pan=1 for right speaker, pan=2 for left speaker.

**Comment by pvcraven** [comment]
Done
