### ISSUE TITLE
Sprite.scale error

### ISSUE THREAD

**Issue by humansHS** [pvcraven/arcade#578]
### Actual behavior:
Changing the scale of a Sprite (either using .scale = or _set_scale) sometimes does not scale the sprite.

### Expected behavior:
Should scale the sprite to the entered value.

### Steps to reproduce/example code:
Try scaling a sprite from initial to a new scale and back again.

### Where is it located?
I believe it is line 497 of the set_scale (line 495) of sprite.py Sprite class

### What is wrong with it? How can it be improved?
It should read:
`if new_value != self._scale:`
instead of:
`if new_value != self._height:`

**Comment by pvcraven** [comment]
Thanks for the detailed bug report. Fix should be out in next release.

**Comment by pvcraven** [comment]
Fixed in 2.3.3.
