### ISSUE TITLE
screenshot, image of screen

### ISSUE THREAD

**Issue by culurciello** [pvcraven/arcade#582]
Hi, great work here! I was wondering how can I get a screenshot = image of the window while game is running? Thanks a lot

**Comment by pvcraven** [comment]
Via code? Or manually?

Alt-Printscreen normally grabs a screenshot you can paste into a graphics program. Windows also has a "snipping tool".

**Comment by culurciello** [comment]
never mind, found it!
image = arcade.get_image()
image.save('screenshot.png', 'PNG')
thanks a lot!
