### ISSUE TITLE
return data from arcade

### ISSUE THREAD

**Issue by culurciello** [pvcraven/arcade#583]
while running the game/loop in:
http://arcade.academy/examples/sprite_collect_coins.html
I need to return to main some variables. How can I do that in a simple way?

**Comment by pvcraven** [comment]
Again, not sure what you are looking to do. Can you set an attribute as part of your window class, and use that as a spot for your data?

**Comment by culurciello** [comment]
I was wondering if there is a way to send back data to the main() function as the game runs. I wanted to send data at every loop step if possible

**Comment by culurciello** [comment]
thank you for your kind help

**Comment by pvcraven** [comment]
I'd just have your on_update trigger a call to a function that captures/logs the data you are interested in.

**Comment by MrGallo** [comment]
The `main()` function passes control to arcade when you call `arcade.run()`. Its like an infinite loop. The only way to resume control to the `main()` function is to stop the game.

Like, @pvcraven said, you would need to trigger some other function to handle the data you want from inside the `on_update` function.

**Comment by culurciello** [comment]
thank you noted!
