### ISSUE TITLE
How do you properly terminate a session?

### ISSUE THREAD

**Issue by culurciello** [pvcraven/arcade#584]
Hi, how can you properly terminate a game and restart another without re-running main() in: http://arcade.academy/examples/sprite_collect_coins.html
thanks!

**Comment by pvcraven** [comment]
Not really sure what you mean. You want to close one window, then open another?

**Comment by culurciello** [comment]
I wanted to terminate an episode of the game and then restart a new one on same window. For now I have done that with:
self.setup()
not sure if that is preferred way

**Comment by pvcraven** [comment]
Yes, that's the best way to do it. 

I've often been asked why we initialize variables in setup rather than only __init__, and the reason is to make restarting the game easy.
