### ISSUE TITLE
Sprites not being drawn

### ISSUE THREAD

**Issue by MrGallo** [pvcraven/arcade#585]
Current master branch doesn't draw sprites.

Last working commit: df35754c4922f370f9326d24c7e9d5a280b3e23e

**Comment by pvcraven** [comment]
Aaaargh!

**Comment by humansHS** [comment]
I really hope its not my code =\

**Comment by MrGallo** [comment]
@humansHS it's not. LOL

**Comment by pvcraven** [comment]
2.3.4 fixed.
