### ISSUE TITLE
GUI code isn't working nor are there tests for it

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#586]
The GUI button, dialog box, etc. code isn't working. As there are no unit tests on it, it seems to have been that way for a while. Not sure if it should be fixed or removed.

**Comment by wamiqurrehman093** [comment]
I implemented it before it worked but then I didn't check on it sorry I will go check and fix things here in few days.

**Comment by kamagan** [comment]
I have wrote tests for gui.Theme and changed the class some. I can continue this work if you approve.
https://github.com/pvcraven/arcade/pull/605

**Comment by eruvanos** [comment]
I just had a look on the example, 
looks like the text is not rendered because of  check for an empty string but it is None.
[arcade.gui Line259](https://github.com/pvcraven/arcade/blob/c5a5aa388df30eeff696d54052e133f69cf5c5ef/arcade/gui.py#L259)

After fixing this locally it looks like the example is crashing, because it can not render empty string.
Maybe a check if text is not empty be good in [arcade.gui Line237](https://github.com/pvcraven/arcade/blob/c5a5aa388df30eeff696d54052e133f69cf5c5ef/arcade/gui.py#L237)

**Comment by kamagan** [comment]
Gui code is very raw, I going to fix it.

**Comment by eruvanos** [comment]
I would also like to help, especially the InputBox (updating it via on_key_press).

Was there a reason why the on_update method was used?

**Comment by kamagan** [comment]
It is not single problem of InputBox. InputBox needs to global change.
I don't know reason of usage on_key_press.

**Comment by eruvanos** [comment]
The on_update call just checks every 1/60 seconds, in case of a slower update the input feels laggy. Using on_key_press would queue up every keystroke, what ever happens.

Will work on a PR to show the idea.

**Comment by eruvanos** [comment]
Hi,
working on some ideas I setup a separate repository: https://github.com/eruvanos/arcade_gui
Pulled over some of the existing GUI code and started over with a test driven approach.
 
I have some look into [pygame_gui ](https://github.com/MyreMylar/pygame_gui), which seems to be well designed with advanced features.

Label and text button are done so far, planing to work on an easier way to add behavior to buttons.
Next thing would be also the TextInput. I hope I can show some results in the next few days.

**Comment by kamagan** [comment]
Hi. I have extracted font settings from theme https://github.com/kamagan/arcade/blob/master/arcade/gui.py#L416
, changed gui.TextButton https://github.com/kamagan/arcade/blob/master/arcade/gui.py#L5
, rewrited TextButton's examples
https://github.com/kamagan/arcade/blob/master/arcade/examples/gui_button.py
https://github.com/kamagan/arcade/blob/master/arcade/examples/gui_text_button.py
and DialogueBox's example
https://github.com/kamagan/arcade/blob/master/arcade/examples/gui_dialogue_box.py

This is not fiished and I don't know if this is necessary to continue. I can finish and make merge request if you want.

**Comment by eruvanos** [comment]
Update:

Finished now the UIInputBox/TextBox using [pyglet.on_text](https://pyglet.readthedocs.io/en/latest/modules/window.html#pyglet.window.Window.on_text)
which reduces implementation effort of mapping keys to actual characters.

Would really appreciate some feedback, I am also open to move the work into arcade itself, while seeing the benefit in a separate library like pygame_gui.

**Comment by pvcraven** [comment]
This is looking pretty good. I really like the testing and implementation. The implementation that doesn't require added code in the base class (?) is a lot cleaner.

Right now for me 13 of the tests don't pass?

Also, on a minor item, I think the button text should move when pressing the button if the button is 3D.

Probably need some more configuration options? Like flat buttons that highlight instead?

**Comment by eruvanos** [comment]
@pvcraven 

> This is looking pretty good. I really like the testing and implementation.
Thanks, was great to have the existing GUI code and build on top of that :)

> Right now for me 13 of the tests don't pass?
I added travis, to run the tests, have some problems with Python 3.7 and even more with 3.6.

> Also, on a minor item, I think the button text should move when pressing the button if the button is 3D.
Sounds good, I will add an issue for this. First will work on the interaction system. Have some ideas to make the coding easier.

> Probably need some more configuration options? Like flat buttons that highlight instead?
Sounds great! Guess they will be easier to design than 3D buttons. 

@kamagan 
Will have a look on your new code, I guess there are good improvements I can copy over for the theme and font setup.

**Comment by kamagan** [comment]
I have finished update of TextButton, written tests and updated examples.
https://github.com/pvcraven/arcade/pull/691

**Comment by einarf** [comment]
new gui is out in 2.4
