### ISSUE TITLE
Unable to find match for ffmpeg sound library at expected location:

### ISSUE THREAD

**Issue by jdrjones1975** [pvcraven/arcade#587]
upon import of arcade, i receive the following error:

Unable to find match for ffmpeg sound library at expected location: /home/darthvader/Desktop/testenv/venv/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libavcodec.so.58.*
Unable to find match for ffmpeg sound library at expected location: /home/darthvader/Desktop/testenv/venv/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libavformat.so.58.*
Unable to find match for ffmpeg sound library at expected location: /home/darthvader/Desktop/testenv/venv/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libswresample.so.3.*
Unable to find match for ffmpeg sound library at expected location: /home/darthvader/Desktop/testenv/venv/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libavfilter.so.7.*
Unable to find match for ffmpeg sound library at expected location: /home/darthvader/Desktop/testenv/venv/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libavutil.so.56.*
Unable to find match for ffmpeg sound library at expected location: /home/darthvader/Desktop/testenv/venv/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libswscale.so.5.*
FFmpeg binaries could not be loaded.

**Comment by pvcraven** [comment]
Closing. Please track under Issue #372.
