### ISSUE TITLE
Should signals be added to arcade?

### ISSUE THREAD

**Issue by wamiqurrehman093** [pvcraven/arcade#593]
I have been coding games in Godot recently, one of the things I love about it is signals. you can connect and emit signals from one node to another it saves time for checking if conditions, but Godot has nodes like component based architecture. Is it gonna be good if we add it in arcade? or we structure arcade like with component based systems? I never did it I don't know how complex it can be but just asking if its worth it. I am willing to learn different topics and put my time for it. :)

**Comment by pvcraven** [comment]
Hm, interesting possibility. I'll have to think on this. I'm not opposed to it, but it would probably require a bit of thought to make sure we 'got it right'.

**Comment by wamiqurrehman093** [comment]
okay I am free this weekend I will research and try to do something, its gonna use observer pattern?

**Comment by akapkotel** [comment]
> okay I am free this weekend I will research and try to do something, its gonna use observer pattern?

Yup, it seems that observer pattern is what you need here. But be cautious, with Python it is not easy to replace if-statement with anything faster. When if-statement is a bottleneck, you have a problem.

I would rather try to solve such issue by "batching" together entities which are evaluating the same condition and then checking the condition for whole "batch" only once instead evaluating it for each entity.

**Comment by pvcraven** [comment]
Adding this to the enhancement list.

**Comment by hasii2011** [comment]
I see this is closed.  Did it actually make the future enhancement list?

**Comment by einarf** [comment]
It's still unclear to me how exactly this will benefit arcade. Do you have any examples? Showing some code with the existing arade api would probably convey the idea better. Signals are geat, but where and how?

**Comment by hasii2011** [comment]
That is fine.   I was just unsure if you would work on this.  I don't want to derail other work you are doing.  Currently, I just monitor delta_time on the update method and call various methods based on how many seconds have passed;  I will just build an internal callback engine once this gets too unwieldy

**Comment by einarf** [comment]
> That is fine. I was just unsure if you would work on this. I don't want to derail other work you are doing. Currently, I just monitor delta_time on the update method and call various methods based on how many seconds have passed; I will just build an internal callback engine once this gets too unwieldy

This is the first example in this issue. How would arcade code look like supporting this with signals? That is what I am looking for here. Some example that would illustrate the feature.

**Comment by hasii2011** [comment]
Here is how you would set it up:

```python
clockCall:  UserEventCall = UserEventCall(func=StarTrekScreen.clockCB, userEvent=Settings.CLOCK_EVENT)
ktkCall:    UserEventCall = UserEventCall(func=StarTrekScreen.ktkCB,   userEvent=Settings.KLINGON_TORPEDO_EVENT)
entHitCall: UserEventCall = UserEventCall(func=StarTrekScreen.enterpriseHitCB,
                                                  userEvent=Settings.ENTERPRISE_HIT_BY_TORPEDO_EVENT)

eventEngine.addUserEvent(clockCall)
eventEngine.addUserEvent(ktkCall)
eventEngine.addUserEvent(entHitCall)


#
# The callbacks like this:
#

@staticmethod
def clockCB(theEvent: Event):

    self = StarTrekScreen._myself
    self.logger.debug(f"clockEventCallback - Event Type: {theEvent.type} - relative time {theEvent.dict['time']}")

    randomTime = self.intelligence.computeRandomTimeInterval()
    self.statistics.remainingGameTime -= randomTime
    self.statistics.starDate += randomTime
    StarTrekScreen.quitIfTimeExpired()

@staticmethod
def ktkCB(theEvent: Event):

    self = StarTrekScreen._myself

    self.logger.debug(f"ktkEventCallback - Event Type: {theEvent.type} - relative time {theEvent.dict['time']}")
    self.fireKlingonTorpedoesAtEnterprise()

```
