### ISSUE TITLE
Texture transformations

### ISSUE THREAD

**Issue by specht** [pvcraven/arcade#596]
### What should be added/changed?

Add a `Texture.draw_transformed` method which draws a rectangular texture like `Texture.draw_sized` but takes a 3x3 2D affine transformation matrix as an additional argument which gets applied to the texture coordinates.

### What would it help with?

It's meant to be used for static rectangles with animated textures which may be useful for full-screen parallax scrolling and other effects.

I think this extends enhancement request #185 but adds translation, rotate and shear operations to scaling.

**Comment by pvcraven** [comment]
Released in 2.3.6.
