### ISSUE TITLE
arcade.Sprite.get_adjusted_hit_box() returns wrong values for some Sprites

### ISSUE THREAD

**Issue by Helios713** [pvcraven/arcade#602]
### Actual behavior:
The function arcade.Sprite.get_adjusted_hit_box() returns wrong values for all Sprites for which the heuristics in the first half of said function fail, for example textureless Sprites. 

### Expected behavior:
It should return the correct hitbox.

### Steps to reproduce/example code:
Create a textureless Sprite and place it at any point where 'center_x' and 'center_y' are not 0.
Then call the Sprite.draw_hit_box() on that Sprite. The hitbox is drawn far away from the Sprite. This even happens after you manually set Sprite.points or Sprite.hit_box.

### What should be added/changed?
A single line would do: the Sprite has to be moved by -center_x and by -center_y in the respective directions before calculating the hit_box in the for loop at the end of the function get_adjusted_hit_box()

### What would it help with?
calculating accurate hitboxes for textureless Sprites (arguably those hitboxes are the only important part of a textureless Sprite, so this would enable using them at all)

### What documentation needs to change? 
None, since the purpose of the function as documented would be fulfilled after the patch and nothing else.

### Where is it located?
arcade.Sprite.get_adjusted_hit_box(), in the for loop at the end

### What is wrong with it? How can it be improved?
I don't think this applies here.

**Comment by Helios713** [comment]
Here is a test for this, it consists of only the part in question and is ready to run as is.

import arcade

class Test():
    def __init__(self):
        # setup
        self.scale = 1.0
        self.angle = 0
        self.center_x = 100
        self.center_y = 100
        self._points = [[102, 100], [100, 102], [98, 100], [100, 98]]
        # outputs
        for self.scale in [1.0, 2.0, 0.5]:
            print()
            print(f'Testing with Scale = {self.scale} ')
            print('Hitbox: ')
            print(self._points)
            print('Original: ')
            self.original()
            print('Patch: ')
            self.patch()
        
    def original(self):
## between these is the original code from arcade.Sprite.get_adjusted_hit_box()
###############################################################################
        point_list = []
        for point_idx in range(len(self._points)):
            # Get the point
            point = [self._points[point_idx][0], self._points[point_idx][1]]

            # Scale the point
            if self.scale != 1:
                point[0] *= self.scale
                point[1] *= self.scale

            # Rotate the point
            if self.angle:
                point = rotate_point(point[0], point[1], 0, 0, self.angle)

            # Offset the point
            point = [point[0] + self.center_x,
                     point[1] + self.center_y]
            point_list.append(point)

        # Cache the results
        self._point_list_cache = point_list

        # if self.texture:
        #     print(self.texture.name, self._point_list_cache)
###############################################################################
    # should be equal to original, since scale and angle suggest no change
        print(self._point_list_cache)
    # instead doubled the center Point

### PATCH
    def patch(self):
        point_list = []
        for x, y in self._points:
            # Transport it to around (0,0)
            x, y = x-self.center_x, y-self.center_y
            
            # Scale the point
            if self.scale != 1:
                x, y = x*self.scale, y*self.scale

            # Rotate the point
            if self.angle:
                x, y = rotate_point(x, y, 0, 0, self.angle)

            # Transport it back
            x, y = x+self.center_x, y+self.center_y
            
            point_list.append([x,y])
        self._point_list_cache = point_list

        print(self._point_list_cache)
        
    

if __name__ == '__main__':
    Test()

**Comment by pvcraven** [comment]
Hm, ran your code but I'm not understanding the issue. This code seems to work as expected:
```
import arcade

def test():
    sprite = arcade.Sprite()
    sprite.hit_box = [[-15.0, -15.0], [15.0, -15.0], [15.0, 15.0], [-15.0, 15.0]]

    assert sprite.get_hit_box() == [[-15.0, -15.0], [15.0, -15.0], [15.0, 15.0], [-15.0, 15.0]]
    assert sprite.get_adjusted_hit_box() == [[-15.0, -15.0], [15.0, -15.0], [15.0, 15.0], [-15.0, 15.0]]

    sprite.scale = 2.0

    assert sprite.get_hit_box() == [[-15.0, -15.0], [15.0, -15.0], [15.0, 15.0], [-15.0, 15.0]]
    assert sprite.get_adjusted_hit_box() == [[-30.0, -30.0], [30.0, -30.0], [30.0, 30.0], [-30.0, 30.0]]

    sprite.center_x = 30
    sprite.center_y = 30

    assert sprite.get_hit_box() == [[-15.0, -15.0], [15.0, -15.0], [15.0, 15.0], [-15.0, 15.0]]
    assert sprite.get_adjusted_hit_box() == [[0.0, 0.0], [60.0, 0.0], [60.0, 60.0], [0.0, 60.0]]
```

**Comment by pvcraven** [comment]
Closing. Please update with more details if it is an issue we need to fix, and I just don't understand.
