### ISSUE TITLE
Alternatives for window = None

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#61]
This ticket is a place for us to discuss alternatives.

In examples/asteroid_smasher.py we see a module with an arcade.window subclass for the "application" and a couple of other classes (sprites) which need information from the window instance. Since "window" doesn't exist until the class is instantiated, this leads to a NameError problem, currently solved by window = None at the top. This then drives PyCharm crazy, saying None has no attribute width, etc.

Elsewhere in the codebase, we throw "global" at the problem. Both of these are code smells which aren't just signs of brittle code, hard-to-test code, but bad practices which shouldn't be taught.

I'd like to discuss ways to eliminate window = None. This discussion has two related pain-points:
- _Modules_. We shouldn't require arcade games to all exist in one module. But when split across modules, the global pattern won't work.
- _Framework_. I think we want arcade to between the game writer and Pyglet. If so, we need a framework in arcade which might do some work before/during/after the game writer's event handlers, which right now are called directly by Pyglet.

**Comment by pvcraven** [comment]
Examples have been updated to remove a lot of window = None examples. Pylint on Pycharm is showing fewer errors.

**Comment by pauleveritt** [comment]
I see you’ve done a lot of work, kudos. So I can better understand your thinking, what goes in “MyWindow” and what goes in “MyApplication”? I would expect domain-specific stuff, like tracking bullets in asteroid_smasher.py, to go in the application.

I think, at the end of the day, arcade will wind up sticking with the approach of “specially-named methods that Pyglet will call on events”, rather than be an intermediary between Pyglet and games. Which has its advantages. So let’s close this ticket.

—Paul

**Comment by pauleveritt** [comment]
Coming back to that, I’m not sure the Application class has any purpose, nor does the “setup” method on MyWindow. If you move everything from “setup” into __init__, you can get rid of class Application and just have this at that bottom:

window = MyWindow()
arcade.run()

—Paul

**Comment by pvcraven** [comment]
I think the Pycon group had a discussion about that, if there should be an app class or not. I think it depends on the complexity of the project. Most of the examples aren't very complex.

**Comment by pauleveritt** [comment]
I'm satisfied with the answer on this, closing the ticket.
