### ISSUE TITLE
Removing SpriteList from Spritesprite_lists should be done in SpriteList.remove()

### ISSUE THREAD

**Issue by akapkotel** [pvcraven/arcade#613]
### What should be added/changed?

When SpriteList.remove() method is called, it should also remove the SpriteList from Sprite.sprite_lists.

Like: item.sprite_lists.remove(self)

### What would it help with?
It allows for temporarily not-updating some Sprite without destroying it - e.g. when you want to 'hide' Sprite which should be not 'visible' for player/s and reveal it later.
Otherwise, manually removing Sprite from SpriteList (without killing it) causes error when SpriteList  is updating itself (KeyError when trying to obtain Sprite id from self.sprite_idx dictionary).
Currently, the only safe way to remove Sprite from SpriteList is to call it's kill() method - but it kills the Sprite.

It would also allow for removing self.sprite_lists.clear() call in Sprite.remove_from_sprite_lists() method.

**Comment by pvcraven** [comment]
Hey, I'll look into the `remove` part soon, but you can just pull a Sprite out of a SpriteList and put it into a regular Python list to 'hold' it.

**Comment by akapkotel** [comment]
The problem is not storing a Sprite somwhere, but the calls to SpriteList methods inside Sprite.

The problem is, when you manually pull the Sprite out of the SpriteList other way than by calling kill() on Sprite, Sprite will try to update it's position in the SpriteList (see for. example the call in _set_scale() method of Sprite) - everytime such a call would end with KeyError, if Sprite was manually removed from SpriteList.

That is why I had to write a wrapper for SpriteList for my own project I'am currently working on.

**Comment by pvcraven** [comment]
Thanks for the report. Think it should be fixed in next version.

**Comment by pvcraven** [comment]
Arcade 2.3.9 is out, should be fixed now.
https://arcade.academy/release_notes.html
