### ISSUE TITLE
Corner collisions causing 'shivering'

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#614]
See: https://www.reddit.com/r/pythonarcade/comments/fh56fg/sprite_shivering_after_corner_collision/

Colliding sprites right on the corner can cause 'shivering'. In the room example, running the character into the box on the corner does not work well.

**Comment by chpurdy** [comment]
I found a solution, but it's too simple, so I know I'm missing something.  Here is the gist (if you want me to do a pull request I can, but like I said, there has to be a reason you're doing it the way you have it now)...

In the `update` method of `PhysicsEngineSimple`, you get the x and y hit lists, then have it select the new position of the sprite based off of the items that were hit:
``` python
if len(hit_list_x) > 0:
             if self.player_sprite.change_x > 0:
                 for item in hit_list_x:
                     self.player_sprite.right = min(item.left,
                                                    self.player_sprite.right)
             ...
```
If I change it to:
``` python
if len(hit_list_x) > 0:
    if self.player_sprite.change_x != 0:
        self.player_sprite.center_x -= self.player_sprite.change_x
    else:
        print("Error, collision while player wasn't moving.")
```
It stops the sprite movement and we don't get the "shivering."  

Again, I figure there MUST be a use-case for the way you have it now, and I just haven't thought of it.

**Comment by pvcraven** [comment]
The issue with doing things that way, is if change_x is large, the character can never come in contact with the item.

For example, if change_x is 6 pixels and the item is 5 pixels away, then there will always be a 5 pixel gap that will never be closed. Even a 1 pixel gap can be noticable.

**Comment by chpurdy** [comment]
> The issue with doing things that way, is if change_x is large, the character can never come in contact with the item.
> 
> For example, if change_x is 6 pixels and the item is 5 pixels away, then there will always be a 5 pixel gap that will never be closed. Even a 1 pixel gap can be noticable.

And there it is.  Thanks!

**Comment by pvcraven** [comment]
Arcade 2.3.9 is out, should be fixed now.
https://arcade.academy/release_notes.html
