### ISSUE TITLE
64-bit windows not getting detected correctly with soloud

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#615]
See: https://www.reddit.com/r/pythonarcade/comments/fgkxsb/soloud_not_found/

**Comment by pvcraven** [comment]
Arcade 2.3.9 is out, should be fixed now.
https://arcade.academy/release_notes.html

**Comment by alexrudnick** [comment]
Hi there, I'm getting basically this same problem on 64-bit Linux.

I've got arcade 2.3.13 installed in a virtualenv on Ubuntu 18.04.4 LTS.

**Comment by alexrudnick** [comment]
Ah, pardon, I see the discussion on issue #622 . I might just stick with a pre-SoLoud version of arcade for a while then...
