### ISSUE TITLE
Small error in create_line_strip

### ISSUE THREAD

**Issue by NielsOkker** [pvcraven/arcade#616]
Dear arcade maintainers,

I noticed that only the final triangle of my line would be drawn on screen using 'create_line_strip' called with a line width bigger than 1. This appeared when I updated from version 2.1.3 to the current version, 2.3.8.

After investigating it appears that the return indenting has changed. It currently returns after the first triangle that it creates. It also seems to create a new shape for each triangle which also is not necessary. 
https://github.com/pvcraven/arcade/blob/57ee9f04b3d7b456faf327f3c840058f870c67da/arcade/buffered_draw_commands.py#L218

Hoping to help,

Niels

**Comment by pvcraven** [comment]
Thanks for the detailed report.

**Comment by NielsOkker** [comment]
Cool to see the fast fix! Thanks a lot.

**Comment by pvcraven** [comment]
Arcade 2.3.9 is out, should be fixed now.
https://arcade.academy/release_notes.html
