### ISSUE TITLE
latest version soloud_x86 not found,no sounds

### ISSUE THREAD

**Issue by chslink** [pvcraven/arcade#617]
## Bug Report
SoLoud dynamic link library D:\Programs\Python\Python37\lib\site-packages\arcade\soloud/soloud_x86 not found.
Warning, can't initialize soloud name 'soloud_dll' is not defined. Sound support will be limited.
### Actual behavior:
no sounds
### Expected behavior:
hear anything?
### Steps to reproduce/example code:
python version:Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32

I have read the arcade.sound code.seems use `sys.platform` value load soloud  dynamic link library not right.
see :https://stackoverflow.com/questions/23956229/i-have-a-win7-64bits-os-but-the-value-of-sys-platform-is-win32-why?noredirect=1&lq=1
and https://stackoverflow.com/questions/2208828/detect-64bit-os-windows-in-python

I do change the code  to load soloud_x64.dll directly, and it works.
I think we could try to load x64 dll again when load library failed.

**Comment by pvcraven** [comment]
What version of Arcade do you have? A release went out yesterday related to this.

**Comment by pvcraven** [comment]
See: https://github.com/pvcraven/arcade/issues/615

**Comment by chslink** [comment]
Sorry,it is 2.3.8. And I update to 2.3.9 this issue has fixed.
