### ISSUE TITLE
How about translating the document into Chinese？

### ISSUE THREAD

**Issue by callmebg** [pvcraven/arcade#618]
Not long ago, someone recommended "arcade" to me, but I found that arcade.academy only has English documents. If you can translate documents into multiple languages, this library might be very popular.

In addition, if I want to translate it into Chinese, what should I do.

**Comment by pvcraven** [comment]
The documents are built with 'restructured text' and a tool called 'Sphinx'. Sphinx does support internationalization. I'm not an expert at it, but you can create these 'po' files which support translation. Someone has already worked with German some:

https://github.com/pvcraven/arcade_book/tree/master/locale

**Comment by pvcraven** [comment]
Ok, I think I figured out how to do this with Transifex. It lets you translate on-line with minimal hassle. If you want to register there and send me a username, I can let you get started.

**Comment by callmebg** [comment]
> 
> 
> Ok, I think I figured out how to do this with Transifex. It lets you translate on-line with minimal hassle. If you want to register there and send me a username, I can let you get started.

cool！My username is callmebg.

**Comment by pvcraven** [comment]
Try looking at the 'arcade' file and translate a few strings. I'll do a build and make sure it works. This site is a bit more difficult than learn.arcade.academy.

**Comment by Rhodanthe1116** [comment]
Hi! I am curious about translation of Chinese too. How is it going?

**Comment by coolbii** [comment]
> Hi! I am curious about translation of Chinese too. How is it going?

I'm also interested and want to help translate to Chinese( from Taiwan btw )

**Comment by callmebg** [comment]
try it
https://www.transifex.com/arcade-academy/arcade-academy/dashboard/
https://www.transifex.com/arcade-academy/learn-with-arcade-academy/dashboard/

**Comment by Rhodanthe1116** [comment]
Thanks! My username is Rhodanthe1116. I have requested for Chinese(zh-tw).

**Comment by pvcraven** [comment]
I got an open-source license finally for transiflex, and there's a person that wants to do German as well.

Sometime I need to time things so that I can go back and forth to make sure changes can be pushed and pulled correctly. I don't know what time-zone you are in, I'm in (GMT-5). Any chance to join the Arcade Discord?
