### ISSUE TITLE
Windows installation currently fails as documented

### ISSUE THREAD

**Issue by ddekany** [pvcraven/arcade#619]
The installation process described on https://arcade.academy/installation_windows.html won't work with latest Python and PyCharm on Windows, because the installation of the "arcade" package will fail, because the installation of "numpy" and "Pillow" transitive dependencies will fail, because pip won't download their binaries, and instead tries to build them locally. This can be a blocker for beginners (and likely they will blame Arcade :) ), so I suggest adding below workaround to said page. (Also, I saw similar problems reported for numpy and Pillow in the past as well, so I guess it's something that tends to reappear for some reason.)

So the workaround I used is this:

If "arcade" installation fails in PyCharm, then, when the project is still open, try this:
1. Open the PyCharm Terminal (Alt+F12). (Then you will be in the project directory, and venv will be already activated. Or at least that's how it normally is.)
2. In the terminal issue this: `python -m pip install -U --force-reinstall pip`
3. Restart PyCharm (or at least close and reopen the project)
4. Try to install the "arcade" dependency again.

## More details

Python 3.8.2
PyCharm 2019.3.4 (Community Edition), Build #PC-193.6911.25, built on March 18, 2020
Windows 10

The virtualenv that PyCharm creates will use an old pip version, 19.0.3, regardless of what's installed globally. (Unless, you check in "Inherit global site-packages", though I guess that's not the best practice, plus then the user has to ensure that pip is upgraded globally.)
See also: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000530279-unable-to-upgrade-the-pip-version-

**Comment by pvcraven** [comment]
Updated. Thanks. Please add additional comments if you've got any other ideas on improving these docs!

**Comment by ddekany** [comment]
You have added "(or exit and restart the terminal)" there, but I guess that doesn't help. Because, after forcefully upgrading pip under the open project, the editor was broken, not finding any dependencies. Restarting PyCharm helped, and I guess restarting the terminal wouldn't.

**Comment by ddekany** [comment]
Also it turns out that `python -m pip install -U --force-reinstall pip` has to be issued twice, as first time it fails with some exception. 2nd time it succeeds. Ugh.
