### ISSUE TITLE
Problem installing on windows

### ISSUE THREAD

**Issue by MRFaria** [pvcraven/arcade#62]
after installing via pip, when i try running the examples on the website I get:
`Traceback (most recent call last):
  File "test.py", line 17, in <module>
    import arcade
  File "D:\whome\workspace\Arcade\venv\lib\site-packages\arcade\__init__.py", line 9, in <module>
    from arcade.arcade_types import *
  File "D:\whome\workspace\Arcade\venv\lib\site-packages\arcade\arcade_types.py", line 4, in <module>
    from typing import Tuple
ImportError: No module named 'typing'
(venv)`

**Comment by pauleveritt** [comment]
Are you running it in Python 3.5?

**Comment by pvcraven** [comment]
Was the typing module added in 3.5.2? I'm not sure it even exists in 3.5.1. With a version test, we could probably come up with a better error message than this.

**Comment by gantlion** [comment]
No I'm running 3.4.4

**Comment by pvcraven** [comment]
Ok. It will have to be with 3.5.2 or better. I'll try to come up with a better error message, and add to the documentation to make this clear. Thank you for reporting the issue.

**Comment by gantlion** [comment]
No problem, I'll try running it on the linux subsytem on windows, I have python 3.5 installed on it

**Comment by pvcraven** [comment]
Code was updated earlier to give a warning that Python 3.5+ was required. Closing issue.
