### ISSUE TITLE
No sound on Ubuntu 18/Python 3.6/arcade 2.3.9

### ISSUE THREAD

**Issue by HiranChaudhuri** [pvcraven/arcade#622]
## Bug Report
On Ubuntu 18, Python 3.6 and arcade 2.3.9 I do not get any sound output.
I see that 2.3.9 was not yet released. However that is what my code prints on the console.
I tried the Reddit community but so far no response on https://www.reddit.com/r/pythonarcade/comments/fgkxsb/soloud_not_found/

### Actual behavior:
I do get sound from various applications so I do not expect a problem on my sound system per se.
When running my self created arcade based application, code that is expected to play sound seems to remain silent.

### Expected behavior:
I'd like to hear the sound, just as I do when clicking the resource sound on the web page.

### Steps to reproduce/example code:
```
print("Running on arcade {}", arcade.__version__)
...
self.sound_cheer = arcade.Sound(":resources:sounds/happykids.wav")
...
self.sound_cheer.play()
```

This code prints out:
```
SoLoud dynamic link library /home/hiran/PycharmProjects/PyPong/venv/lib/python3.6/site-packages/arcade/soloud/libsoloud.so not found. /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/hiran/PycharmProjects/PyPong/venv/lib/python3.6/site-packages/arcade/soloud/libsoloud.so)
Warning, can't initialize soloud name 'soloud_dll' is not defined. Sound support will be limited.
Running on arcade {} 2.3.9
```

**Comment by HiranChaudhuri** [comment]
Now that I actually found the library at 
/home/hiran/PycharmProjects/PyPong/venv/lib/python3.6/site-packages/arcade/soloud/libsoloud.so
I realize the latter part of the error message claims that GLIBC 2.29 is missing.

**Comment by HiranChaudhuri** [comment]
Analysis of libsoloud.so shows it depends on some libraries:
```
$ readelf -d /home/hiran/PycharmProjects/PyPong/venv/lib/python3.6/site-packages/arcade/soloud/libsoloud.so 

Dynamic section at offset 0xd7bf8 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libasound.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x2c000
 0x000000000000000d (FINI)               0xbda0c
 0x0000000000000019 (INIT_ARRAY)         0xd7d00
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0xd7d08
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x260
 0x0000000000000005 (STRTAB)             0xcaa8
 0x0000000000000006 (SYMTAB)             0x3298
 0x000000000000000a (STRSZ)              48691 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0xd9000
 0x0000000000000002 (PLTRELSZ)           17280 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x27548
 0x0000000000000007 (RELA)               0x19688
 0x0000000000000008 (RELASZ)             57024 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x19588
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0x188dc
 0x000000006ffffff9 (RELACOUNT)          1946
 0x0000000000000000 (NULL)               0x0

```

**Comment by HiranChaudhuri** [comment]
```
readelf -d /lib/x86_64-linux-gnu/libm.so.6

Dynamic section at offset 0x19cd90 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libm.so.6]
 0x000000000000000c (INIT)               0xb7f0
 0x000000000000000d (FINI)               0xca2f8
 0x0000000000000019 (INIT_ARRAY)         0x39cd80
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x39cd88
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x19a5c0
 0x000000006ffffef5 (GNU_HASH)           0x210
 0x0000000000000005 (STRTAB)             0x8808
 0x0000000000000006 (SYMTAB)             0x2610
 0x000000000000000a (STRSZ)              8530 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x39d000
 0x0000000000000002 (PLTRELSZ)           888 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xb478
 0x0000000000000007 (RELA)               0xb340
 0x0000000000000008 (RELASZ)             312 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffc (VERDEF)             0xb188
 0x000000006ffffffd (VERDEFNUM)          10
 0x000000000000001e (FLAGS)              STATIC_TLS
 0x000000006ffffffe (VERNEED)            0xb2e0
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0xa95a
 0x000000006ffffff9 (RELACOUNT)          3
 0x0000000000000000 (NULL)               0x0
```

**Comment by HiranChaudhuri** [comment]
> readelf -d /lib/x86_64-linux-gnu/libc.so.6 
> 
> Dynamic section at offset 0x1eab80 contains 26 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
>  0x000000000000000e (SONAME)             Library soname: [libc.so.6]
>  0x000000000000000c (INIT)               0x21920
>  0x0000000000000019 (INIT_ARRAY)         0x3e7630
>  0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
>  0x0000000000000004 (HASH)               0x1e3638
>  0x000000006ffffef5 (GNU_HASH)           0x2b8
>  0x0000000000000005 (STRTAB)             0x119d0
>  0x0000000000000006 (SYMTAB)             0x3ee8
>  0x000000000000000a (STRSZ)              24286 (bytes)
>  0x000000000000000b (SYMENT)             24 (bytes)
>  0x0000000000000003 (PLTGOT)             0x3eb000
>  0x0000000000000002 (PLTRELSZ)           1104 (bytes)
>  0x0000000000000014 (PLTREL)             RELA
>  0x0000000000000017 (JMPREL)             0x20b78
>  0x0000000000000007 (RELA)               0x18f28
>  0x0000000000000008 (RELASZ)             31824 (bytes)
>  0x0000000000000009 (RELAENT)            24 (bytes)
>  0x000000006ffffffc (VERDEF)             0x18af0
>  0x000000006ffffffd (VERDEFNUM)          29
>  0x000000000000001e (FLAGS)              STATIC_TLS
>  0x000000006ffffffe (VERNEED)            0x18ef8
>  0x000000006fffffff (VERNEEDNUM)         1
>  0x000000006ffffff0 (VERSYM)             0x178ae
>  0x000000006ffffff9 (RELACOUNT)          1237
>  0x0000000000000000 (NULL)               0x0
>

**Comment by HiranChaudhuri** [comment]
This stuff seems to help little. Checking version numbers I find this file on my computer:
```
ls -ld /lib/x86_64-linux-gnu/libc*
-rwxr-xr-x 1 root root 2030544 Apr 16  2018 /lib/x86_64-linux-gnu/libc-2.27.so
lrwxrwxrwx 1 root root      12 Apr 16  2018 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.27.so

```

So for some reason GLIBC 2.29 is searched but the system has only 2.27.

**Comment by pvcraven** [comment]
Sound library doesn't work on Ubuntu 18. It does on 19. I can't get a working compile of soloud with an older glib library for some reason.

**Comment by HiranChaudhuri** [comment]
That would explain the library versions.
Things like that happen but if you kindly put information on that into documentation, or maybe into the code so the error message would at least point to some explanation it would save a lot of time and frustration.
I would have expected Ubuntu 18 would be better supported than 19 and was searching for errors on my side - after all it is the LTS version...

**Comment by HiranChaudhuri** [comment]
I just checked my Ubuntu 19.10 system.
```
ls -ld -lib-x86_64-linux-gnu/libc-*
-rwxr-xr-x 1 root root 2025032 Nov 29 15:19 libc-2.30.so
```
This is newer than what arcarde is trying to run. It could mean arcade plays sound only on a very limited minor version of Ubuntu 19.

**Comment by pvcraven** [comment]
I would have expected it to work with 2.30. That's interesting. In kind of a bad way.

**Comment by HiranChaudhuri** [comment]
Some small improvement:
```
def setup(self):
    sound_cheer = pygame.mixer.Sound("sounds/happykids.wav")

def someOtherMethod(self):
    sound_cheer.play()
```
did not remove the delay in sound play.
But I initialized the pygame mixer with a smaller buffer and now the sounds play ok.
That means I introduced
```
    def __init__(self):
        super().__init__()
        #pygame.init()
        pygame.mixer.init(44100, -16, 2, 512)

```
and it seems sufficient to just initialize the sound system of PyGame.

**Comment by HiranChaudhuri** [comment]
> There have been a lot of improvements to the audio support in pyglet 1.5.x as well. That might be something to explore. Upgrade to latest 1.5.x.

It seems I match the prerequisites.
```
    print("Running on arcade {}", arcade.__version__)
    print("Running on pygame {}", pygame.version.ver)
    print("Running on pyglet {}", pyglet.version)
```
delivers this output:
```
Running on arcade {} 2.3.9
Running on pygame {} 1.9.6
Running on pyglet {} 1.5.2
```

I shall give pyglet a try as well.

**Comment by HiranChaudhuri** [comment]
So running the pyglet sounds is even easier than pgame. No further init required, I simply load the sounds like
`        self.sound_cheer   = pyglet.media.load("sounds/happykids.wav", streaming=False)`
then the playing of them looks like
`        self.sound_cheer.play()`

So this seems to work smooth, and as Arcade works on pyglet anyway it would be on dependency less than using pygame. Thank you for that hint, @einarf

**Comment by pvcraven** [comment]
I dived back into the glib thing, and I really don't understand why it would not work with 2.30. It uses several functions out of 2.29, but that should not hinder 2.30 functionality.

**Comment by HiranChaudhuri** [comment]
> I dived back into the glib thing, and I really don't understand why it would not work with 2.30. It uses several functions out of 2.29, but that should not hinder 2.30 functionality.

Whatever the outcome may be here, it would involve that all my games were limited to Ubuntu 19+ while Ubuntu 18 is the current LTS version. Thus I will rather stick with a workaround.

**Comment by HiranChaudhuri** [comment]
Indeed my Ubuntu 18 is a 64 bit system, too.
```
uname -a
Linux silver 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pvcraven** [comment]
Unless someone can create a working SoLoud build for Ubuntu 18, we are kind of stuck with work-around or Ubuntu 19+ support.
