### ISSUE TITLE
Collision detection for walls at edge of level not working

### ISSUE THREAD

**Issue by richstokes** [pvcraven/arcade#625]
I am building off of the "Load a TMX Map" example.

I initialized the 'Platform's layer and then switched to the simple physics engine with:

```
self.physics_engine = arcade.PhysicsEngineSimple(self.player_sprite,
                                                            self.wall_list)
```
&nbsp; 

I loaded the 'Platforms' layer with:
```
self.wall_list = arcade.tilemap.process_layer(my_map, 'Platforms', TILE_SPRITE_SCALING)
```

&nbsp;

`on_update`, I call `self.physics_engine.update()` and then check for wall collisions with:
```
walls_hit = arcade.check_for_collision_with_list(self.player_sprite, self.wall_list)
for wall in walls_hit:
      print("Hit a wall")
```

I also tried doing this with:
```
if self.player_sprite.collides_with_list(self.wall_list)
```
but this gives the same behavior. 

&nbsp;

Whats strange is collisions do not seem to be detected if the wall is at the edge of the level. I  edited the tilemap and drew a big square around all the edges.  

If my player hits these, no collision is detected. If my player hits a platform tile elsewhere inside the map, the collision is detected.

Is there another/better way I should be checking for collisions to make them more reliable?

**Comment by pvcraven** [comment]
The physics engine keeps you from hitting walls. So if you run the physics engine, afterwards you should not be in contact with any wall whatsoever. The fact that you were is a bug and should be resolved in 2.3.11.

`my_list = self.physics_engine.update()`
If you want to know what walls you collided with, the physics engine returns a list.

**Comment by richstokes** [comment]
What happens is the player touches the wall - they stop at the wall - so the physics is working in that respect, but `if self.player_sprite.collides_with_list(self.wall_list)` returns False.

I am trying to find a way to know if the player has hit the walls. Maybe I need to call the physics engine after checking for collisions?

**Comment by pvcraven** [comment]
Check the list that comes back from the physics engine update. If the length > 0 then you hit a wall.

**Comment by richstokes** [comment]
Thanks - that works. And thanks for making this project, its really fun to work with :)
