### ISSUE TITLE
Is there a way to reset a Pymunk physics game?

### ISSUE THREAD

**Issue by richstokes** [pvcraven/arcade#626]
Looking at this example; https://arcade.academy/examples/pymunk_box_stacks.html#pymunk-box-stacks

How can I tell them game to reset/restart?

In the other tutorials it looked like you could do this by re-calling setup(), but there isnt a setup method here.

**Comment by pvcraven** [comment]
You'd just need to create a setup method, and call it. Move the PyMunk setup code to it.

**Comment by richstokes** [comment]
Thanks. Works great
