### ISSUE TITLE
Question - what is the best way to handle multiple key presses?

### ISSUE THREAD

**Issue by richstokes** [pvcraven/arcade#628]
I'm following this example:
https://arcade.academy/examples/pymunk_platformer.html#pymunk-platformer

Problem is the first key pressed isn't released until you release it, and during this time its blocking other key presses being registered. So you can't quickly change directions or move while mid-jump.

Is there a good way to handle this other than having a whole load of if statements under `on_key_press` to handle the various combinations of key presses?

**Comment by mikesmith** [comment]
I haven't tried that example but I found this example to be very helpful for basic movements with a keyboard. It is still a bunch of if statements where it keeps the current button states in bools. That state is then checked in on_update() to perform any changes.

https://arcade.academy/examples/sprite_move_keyboard_better.html

**Comment by pvcraven** [comment]
Right, that example is a bit more complex, but it should handle tracking what to do if multiple keys are pressed at the same time.

**Comment by akapkotel** [comment]
Easiest and performant way would be to use set() of pressed keys and just add pressed key to the set in on_key_press() and discard it in on_key_release().

The main advantage is that you can cheaply test for key-being-pressed with: key in keys or even test for whole combinations using {key1, key2}.intersection(keys)
