### ISSUE TITLE
Question - Is it possible to run for one step?

### ISSUE THREAD

**Issue by mhtb32** [pvcraven/arcade#629]
I was going to use the arcade to create an Open AI [gym](https://github.com/openai/gym) environment. One trait that a `gym` environment has is to render the _environment_(aka _game_ in arcade context) for one step. I should mention that stepping is controlled by the user and he/she can step the environment whenever he wants.

I found that conflicting with the idea of `arcade.run()`, which handles the game automatically with the desired frame rate. I wonder is there a way to run the game just for one step?

**Comment by Scottes** [comment]
My initial thought would be to put something in on_update() that would loop until some specific key was released, and then continue. Something like that should give you frame-by-frame control.

**Comment by SirGnip** [comment]
For reference, there is a somewhat similar approach in the `test()` method of the `Window` class.  https://github.com/pvcraven/arcade/blob/master/arcade/application.py#L423

You can see the `test()` method used in the `tests/unit2/test_sprite.py` file, among others.

**Comment by HiranChaudhuri** [comment]
> My initial thought would be to put something in on_update() that would loop until some specific key was released, and then continue. Something like that should give you frame-by-frame control.

My gut feeling tells me it might be wise not to block on_update. But what the heck, we could introduce an int (a counter) how many steps shall be simulated. That counter could be increased if we find the user is pressing a button.
Otherwise every on_update run would decrease that counter.

So if the counter reaches zero the game would pause but still get rendered....

**Comment by mhtb32** [comment]
> For reference, there is a somewhat similar approach in the `test()` method of the `Window` class. https://github.com/pvcraven/arcade/blob/master/arcade/application.py#L423
> 
> You can see the `test()` method used in the `tests/unit2/test_sprite.py` file, among others.

So this means I can use `test(frames=1)` to step the game. Isn't that useful to add something like `arcade.step()` to give the user more control of game loop?

**Comment by pvcraven** [comment]
It would seem that you'd have the 'step' in a function, and only call it when triggered. `on_update` is to update the screen logic, and UI. It is important for it to run often, so the UI doesn't seem sluggish.

**Comment by mhtb32** [comment]
For gaming purposes, you are right. But in educational or scientific purposes, some might benefit from having control of the rendering. Even some want to update the logic at a regular interval but only update UI after a reasonable amount of time. This is why packages like [gym](https://github.com/openai/gym) gave the trigger of rendering to the user.

But if arcade is not intended to serve such use cases, then it is better off not adding such functionality.

**Comment by HiranChaudhuri** [comment]
Now I am getting curious as well. When would you need to have absolute control over rendering while you do not care about the game progress? Is it debugging or something else?

So far I thought as long as the rendering redraws the same scene over and over again I would not care, but I might be interested in changes in the model that would then lead to something different being rendered.

This is the case in GUI programming where you do not have absolute control when a widget gets rendered. What you can control though is how the widget renders itself. The UI is responsible to decide when, even the application just gives a hint by saying that something changed.

**Comment by Scottes** [comment]
When "debugging" I will often record the gameplay using Bandicam to save it to an MPEG video, then play it back 1 frame at a time to see exactly what is happening. (As a player I use MPC-HC, which allows single-frame forwards and backwards.)

I do this **constantly** to debug anomalies and hitboxes and collisions. I often have debug info printed to the screen - stuff that changes 60 times per second - to see exact debug info per frame.

I would absolutely love to have a way to play the game one frame at a time. But I also realize that it wouldn't be right for every single debug issue that I have. But it would be nice.

**Comment by einarf** [comment]
In 2.4 you could use a framebuffer (offscreen rendertarget) to capture a frame. `on_draw` could just show that one until you set a flag and it will capture a new frame. Could make an example doing this.

**Comment by mhtb32** [comment]
[Here](https://github.com/eleurent/highway-env) is a gym environment using **pygame** for rendering. Maybe it helps to clear the idea.

**Comment by einarf** [comment]
If you don't need event loop I guess you can just do ..
```python
window = arcade.Window(...)
while True:
    window.clear()
    # Render something
    window.flip()
```
Not actually tested this with arcade, but it's perfectly valid in pyglet.
Somewhere you need to detect exit condition.

**Comment by pvcraven** [comment]
A boolean would seem to make it easy. Flip it to 'True' when you want to advance a frame, triggered by something like a space bar. Then in the on_update, if True do your calculations and after flip the boolean back to False.
