### ISSUE TITLE
2.3.12 not rendering background correctly

### ISSUE THREAD

**Issue by Scottes** [pvcraven/arcade#630]
![background](https://user-images.githubusercontent.com/3163518/78792115-bc499300-797e-11ea-9c0d-cf895b4dbaf4.png)

Ran "pip install -U arcade", got 2.3.12, then ran game.py, got image on right half.
Ran "pip install -U arcade==2.3.11", then ran game.py, got image on left half, which is expected.
Repeated - flipping back and forth between version - with same results.

Please let me know what I can do to debug, or fix, or provide more information.

Map is 32x16 of 128x128 blocks, and only the Background layer is affected. The background fills the entire map, and every tile on the background displays wrong.

Windows 10, Python 3.8.2

**Comment by pvcraven** [comment]
Drat. If you can create any sort of example, zip it and email to paul@cravenfamily.com that would help a lot. I don't know where to start looking without an example.

**Comment by Scottes** [comment]
Email sent with a Google Drive download link. Let me know if there's a problem with that. Or anything else I can do to help/debug/etc.

**Comment by pvcraven** [comment]
If we have tiles with different dimensions, I think it is grabbing the shorter sprites from the bottom instead of the top.

![aaa_3](https://user-images.githubusercontent.com/1463116/78836727-4d892b80-79b8-11ea-8e69-45baf59622b5.png)

**Comment by Scottes** [comment]
Yes, if I remove that door everything is fine.

**Comment by pvcraven** [comment]
Version 2.3.13 is out which should fix the issue. Please let me know.

**Comment by Scottes** [comment]
Almost. The doors are fine but now another graphic is messed up.

![image](https://user-images.githubusercontent.com/3163518/78838209-b629d580-79c3-11ea-9693-f16c895ff03b.png)

**Comment by Scottes** [comment]
I also think this is caused by 2.3.13 - I've never seen it before and it popped up in under a minute of play with 2.3.13, and was reproduced within another minute of gameplay.

![image](https://user-images.githubusercontent.com/3163518/78902143-5ffe7600-7a47-11ea-9272-c30d41123990.png)

I could not reproduce with 2.3.11 after several minutes of gameplay.

**Comment by pvcraven** [comment]
Oh man, a transporter accident. Poor guy.

**Comment by Scottes** [comment]
He was fighting robots but was defeeted by the transporter.

**Comment by pvcraven** [comment]
Could you please test Arcade 2.3.14b2? I worked with a lot of unit tests, and I think it is better.

**Comment by Scottes** [comment]
Yes, that looks good, even with those over-sized door tiles. No anomalies seen.
