### ISSUE TITLE
Supporting `pathlib.Path` in opening tiledmaps

### ISSUE THREAD

**Issue by mhtb32** [pvcraven/arcade#636]
## Enhancement request:
The function `arcade.tilemap.read_tmx()` expects `tmx_file` path to be a string, checks whether it starts with `:resources:` and then passes it to `pytiled_parser.parse_tile_map()` which can accept either a string or a `pathlib.Path`. 

### What should be added/changed?
If `read_tmx()` handles `Path` objects in the input too, one can benefit from the advantages of using a `Path` object instead of a raw string. Right now this can't be processed because of [this line](https://github.com/pvcraven/arcade/blob/master/arcade/tilemap.py#L56) which uses a string method:

```Python
if tmx_file.startswith(":resources:"):
```

### What would it help with?
It helps the user to handle file paths better without the need to convert `Path` to a string.

**Comment by einarf** [comment]
Definitely nice to support pathlib. Because min python version is 3.6, `Path` objects are well integrated in the standard lib.

**Comment by pvcraven** [comment]
Released in 2.4.
