### ISSUE TITLE
Overall confusion with the volume control in the Sound class

### ISSUE THREAD

**Issue by markjoshua12** [pvcraven/arcade#645]
There are three functions that mention about volume control, those are
[set_volume()][1]
[set_left_right_volume()][2]
and [play()][3]
all inside the Sound class.

Two of them ([set_volume()][1] and [set_left_right_volume()][2]) throws a `TypeError` when called.
Here is the code to replicate (added in the [Coins and Sound example code](https://arcade.academy/examples/platform_tutorial/index.html#platformer-part-six) after loading sounds):

```
        self.collect_coin_sound.set_left_right_volume(0, 0)
        self.jump_sound.set_left_right_volume(0, 0)
```
or
```
        self.collect_coin_sound.set_volume(0)
        self.jump_sound.set_volume(0)
```

The exception for both:
```
TypeError: an integer is required (got type NoneType)
```

Futhermore, the example code uses [play_sound()][4] instead to play sounds as seen [here](https://arcade.academy/examples/platform_tutorial/index.html#platformer-part-six). This does not have an option to control volume unlike the three functions mention before.

See also #577 

Thank you and have a nice day.

[1]: https://arcade.academy/arcade.html#arcade.Sound.set_volume
[2]: https://arcade.academy/arcade.html#arcade.Sound.set_left_right_volume
[3]: https://arcade.academy/arcade.html#arcade.Sound.play
[4]: https://arcade.academy/arcade.html#arcade.play_sound

**Comment by pvcraven** [comment]
You can only set the volume AFTER you start playing the sound. If you want to set the volume BEFORE playing, do that as part of the play sound.

This works:
```
        hit_sound1 = arcade.load_sound(":resources:sounds/explosion1.wav")
        hit_sound1.play()
        hit_sound1.set_volume(0)
```
But it doesn't if you flip the last two lines.

Likewise this works if you want to set the volume first:
```
hit_sound1.play(volume=0.5)
```

**Comment by pvcraven** [comment]
Updated docs.
