### ISSUE TITLE
on_key_press not triggering when multiple keys are held down

### ISSUE THREAD

**Issue by maxymoo22** [pvcraven/arcade#649]
## Bug Report
The on_key_press method is not being called all of the time. This happens when the user holds down multiple keys and presses another. An example of this is to hold down the A, S and D keys, and then press E. It wont fire.

### Actual behavior:
Event not firing when a key is pressed.
Actual example output:
KEY PRESSED:   97
KEY PRESSED:   115
KEY PRESSED:   100

### Expected behavior:
Event should fire regardless of how many keys are being held down.
Actual expected output:
KEY PRESSED:   97
KEY PRESSED:   115
KEY PRESSED:   100
KEY PRESSED:   101

### Steps to reproduce/example code:
1. Run this code
```python
import arcade

class MyGame(arcade.Window):
    def __init__(self, width, height, title):
        super().__init__(width, height, title)

    def on_key_press(self, symbol, modifiers):
        print("KEY PRESSED:   " + str(symbol))

if __name__ == "__main__":
    window = MyGame(600, 300, "Window")
    arcade.run()
```

2. Hold down the A, S and D keys at the same time.
3. Press the E key. It wont trigger the function.
4. Let go of the E key and press the W key. It will trigger the function. ????!?!?!?!?!? Something's messed up

This also happens with numerous other combinations, one of them being the up arrow wont trigger when the bottom 3 arrow keys are being held down.

**Comment by pvcraven** [comment]
What OS? I'm pressing 10 at a time and it works with the example.. Might also want to check the keyboard you are using.

**Comment by maxymoo22** [comment]
I'm using windows 10 on a laptop. The keyboard is fully functional. Do you think it might have something to do with how the OS handles key presses?

**Comment by einarf** [comment]
See if get ghosting in this test : https://drakeirving.github.io/MultiKeyDisplay/

**Comment by 1-max-1** [comment]
Huh. It seems it is the computer/OS not allowing me to press certain keys when others are held down.

**Comment by einarf** [comment]
It's most likely the physical wiring in your keyboard. Laptop keyboards are normally matrix based so keys are wired together in rows and columns in some patter + the controller is usually limited to 3 keys. Arrow keys and AWSD are often wired in a similar way.

**Comment by SirGnip** [comment]
I think the "technical" term for what you are seeing is called keyboard "rollover": https://en.wikipedia.org/wiki/Rollover_(key)

There is also something called "accidental activation prevention" (AAP) where some mouse/touchpad clicks will suppress some keyboard keypresses.

Just some things to Google...

**Comment by maxymoo22** [comment]
Ah, I see. Thank you for enlightening me.
