### ISSUE TITLE
Docs don't mention how to call render_rectangle

### ISSUE THREAD

**Issue by makusu2** [pvcraven/arcade#650]
## Bug Report
The docs (2.4a2) mention that `create_rectangle` should be rendered with `render_rectangle`, but a search of `render_rectangle` doesn't reveal how to call it. Is it `my_rectangle.render_rectangle()`, `arcade.render_rectangle(my_rectangle)`, `self.render_rectangle(my_rectangle)` (self being the window)?

### Actual behavior:
No explanation of how to call `render_rectangle`

### Expected behavior:
An explanation in the docs of how to call `render_rectangle`

### Steps to reproduce/example code:
Look up `render_rectangle` on the docs

### What documentation needs to change? 
Wherever you want to put the `render_rectangle` documentation

### Where is it located?
*It's not*

### What is wrong with it? How can it be improved?
It doesn't exist

**Comment by pvcraven** [comment]
Updated, this and some other similar functions with the same issue. Thanks for the report.
