### ISSUE TITLE
Remove unused variable `scale` in example sprite_collect_coins_background

### ISSUE THREAD

**Issue by makusu2** [pvcraven/arcade#651]
## Bug Report
There's an unused variable `scale` in https://github.com/pvcraven/arcade/blob/34f912bc0c9dfdec79da5a3bb2d1a0ffef47cfcc/arcade/examples/sprite_collect_coins_background.py#L99

### Actual behavior:
It's there

### Expected behavior:
It's not there

### Steps to reproduce/example code:
are you serious

### What should be added/changed?
It should be removed

### What would it help with?
Making the examples easier to understand

I'm not sure this template is a good idea when the project isn't huge yet... it makes submitting an issue really exhausting

**Comment by pvcraven** [comment]
Thanks for the report. Looks like this has already been removed from the 2.4 shader branch that the docs are built from.

And you don't have to follow the template.
