### ISSUE TITLE
Add docstring on how to run gui_button example (or remove reference to it)

### ISSUE THREAD

**Issue by makusu2** [pvcraven/arcade#652]
## Bug Report
At https://github.com/pvcraven/arcade/blob/34f912bc0c9dfdec79da5a3bb2d1a0ffef47cfcc/arcade/examples/gui_button.py#L40, it looks like there's supposed to be an explanation of how to run the example at the top of the file, like other files. The explanation (with `python -m arcade.examples.sprite_collect_coins`) should be added, or this comment referencing it should be removed.

### Actual behavior:
There's no difference in behavior

### Expected behavior:
There's no difference in behavior

### Steps to reproduce/example code:
Look at https://github.com/pvcraven/arcade/blob/34f912bc0c9dfdec79da5a3bb2d1a0ffef47cfcc/arcade/examples/gui_button.py#L40

### What should be added/changed?
A comment should be added regarding how to run the example, or the comment which references explaining it should be removed

### What would it help with?
Making the example easier to run and making the module more truthful

**Comment by kamagan** [comment]
I am rewriting gui.TextButton and examples of it's usage right now. I will make a merge request in some days.

**Comment by eruvanos** [comment]
With the input from @kamagan I started to work on a separate library and have some working examples for label, buttons and textinputs.

Still work in progress.

https://github.com/eruvanos/arcade_gui

**Comment by makusu2** [comment]
@eruvanos You made a different library instead of a PR? Why are you advertising it here?

**Comment by pvcraven** [comment]
For something like this, creating a separate library, and then maybe later
integrating in the main code base when done isn't a bad idea.

**Comment by eruvanos** [comment]
@makusu2 
Still have the option to merge it at some point, started with that idea.

The lib required no change in arcade itself, so editing everything in a separate repo felt way faster for development. 

Also I used some different concepts and I was not sure if this would be fine within arcade. 
Having a look at pygame_gui, the project looked so advanced that I still see a benefit of separating the game library from a GUI implementation.

> Edit: didn't mean to sound super rude
Thanks for the edit :)

**Comment by kamagan** [comment]
It works like this "python -m arcade.examples.gui_button" now. Also other examples of gui have been rewrite.

**Comment by pvcraven** [comment]
Should be fixed now.
