### ISSUE TITLE
Bold an italic arguments in draw_text() have no effect

### ISSUE THREAD

**Issue by Jeluri** [pvcraven/arcade#656]
### Actual behavior:
```python
arcade.draw_text("Hello world!", 200, 260, arcade.color.RED)  # (1)
arcade.draw_text("Hello world!", 200, 230, arcade.color.RED, bold=True)  # (2)
arcade.draw_text("Hello world!", 200, 200, arcade.color.RED, italic=True)  # (3)
```
**The above lines produce the same result regardless of the `bold` and `italic` arguments.**
Note: `arcade.draw_text_2()` handles bold/italic but has no cache mechanism.

### Expected behavior:
(2) shoud display "Hello world!" with a bold font.
(3) shoud display "Hello world!" with an italic font.

### Fast analysis:
These arguments are not used within `arcade.draw_text()`. I guess this is because PIL doesn't handle bold and italic whithout explicitly providing the bold/italic version of the font file name. The following example works:
```python
arcade.draw_text("Hello world!", 200, 260, arcade.color.RED, font_name='arial')
arcade.draw_text("Hello world!", 200, 230, arcade.color.RED, font_name='ariblk')
arcade.draw_text("Hello world!", 200, 200, arcade.color.RED, font_name='ariali')
```
Should `bold` and `italic` arguments be removed from `arcade.draw_text()`?

**Arcade version:** 2.3.15

**Comment by pvcraven** [comment]
Updated docs to reflect this info.

The parameters should go back to being supported after we move to Pyglet 2.0 when its text processing works with OpenGL 3.3 shaders.
