### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by sanslash332** [pvcraven/arcade#67]
Well, this is more a doubt instead a issue. The library current have full joystick Support?
Or for joystick, you need use a thirth library.
Thanks for all

**Comment by pauleveritt** [comment]
There's a recent [pyglet discussion](https://groups.google.com/forum/#!topic/pyglet-users/rESCzGNBV3U) about work on a branch to figure this out. Since we have to wait for pyglet to support it, I'd say there's not much immediate to do.

**Comment by pvcraven** [comment]
It works on pyglet. We just need to make our API, document it, and finish out examples. move_joystick.py example at least lets you move.

**Comment by sanslash332** [comment]
Ok, thanks, perfect!

 

Hmm it have rumble support? Or only for buttons pov and axis.

**Comment by danboid** [comment]
Joystick support seems to work now. What doesn't work except fancy stuff like rumble? Paul seems to indicate its not finished.

I've not tested more than 1 USB joypad yet. Do multiple USB joysticks/joypads work OK?

Can we use (multiple) joysticks at the same time as the keyboard and/or mouse input without doing anything fancy?

**Comment by pauleveritt** [comment]
Pardon me on the noise on that. I was repeating something I saw on the pyglet mailing list.

Looks like I need to buy a USB joystick.

—Paul

**Comment by danboid** [comment]
Hi Paul!

I was actually referring to the other Paul, Professor Craven! :)

**Comment by danboid** [comment]
Maybe I'm getting confused here. Are Paul Everitt and Paul Craven one and the same?

**Comment by pauleveritt** [comment]
Paul Craven is the creator of Arcade, long-time Python game organizer. Paul Everitt is just a small-scale occasional contributor on Arcade. :)

—Paul

**Comment by benmoran56** [comment]
Hi @pvcraven, and others, 

I'm the pyglet contributor who is working on GameController support. I was planning on merging this in a future release, but I'd love to get feedback on it. I've basically copied how SDL2 does things, by implementing a static internal layout for the controllers. This uses a mapping database for auto-configuration of most common game controllers. My fork is located here:  https://bitbucket.org/HigashiNoKaze/pyglet/branch/game_controller
Interesting stuff is in pyglet/input/gamecontroller.py, and a new GameController class in /pyglet/input/base.py

**Comment by pvcraven** [comment]
With the addition of game controller examples, I'm thinking of marking this closed for 1.2.2.

**Comment by pvcraven** [comment]
Closed, implemented in 1.2.2 which is now deployed on PyPi.
