### ISSUE TITLE
Replace arcade.TextBox

### ISSUE THREAD

**Issue by Den4200** [pvcraven/arcade#673]
## Enhancement request:
I think Arcade should have a `TextInput` class to get text input from the user. Currently the only option for this is `arcade.TextBox`, but that is non-functional.

### What should be added/changed?
I've already made a `TextInput` class in a project [here](https://github.com/Den4200/game-jam-2020/blob/master/monkeys-and-frogs-on-fire/triple_vision/text_input.py), so `arcade.TextBox` should be removed and replaced with the `TextInput` class. 

### What would it help with?
Users currently cannot get any text input using Arcade without creating their own solution, so this would solve that issue.

**Comment by eruvanos** [comment]
Will be fixed with the new GUI in 2.4

**Comment by pvcraven** [comment]
Fixed in 2.4
