### ISSUE TITLE
Bug in the documentation

### ISSUE THREAD

**Issue by Leterax** [pvcraven/arcade#677]
# What documentation needs to change? 
https://arcade.academy/examples/sound_demo.html#sound-demo
### Where is it located?
https://github.com/pvcraven/arcade/blob/master/arcade/examples/sound_demo.py
### What is wrong with it? How can it be improved?
the docs for the sound demo are slightly wrong:
the doc-string tells you to call "python -m arcade.examples.starting_template"
but it should be "python -m arcade.examples.sound_demo"

**Comment by pvcraven** [comment]
Fixed, thanks for the report.
