### ISSUE TITLE
Modifier keys (MOD_*) not parsed correctly on some systems

### ISSUE THREAD

**Issue by notklaatu** [pvcraven/arcade#685]
## Bug Report

MOD_SHIFT, MOD_ALT, MOD_CTRL, and MOD_COMMAND are not detected on some systems.

Here's the breakdown so far:

* RHEL 8 / Python 3.7.7 / Wayland: works as expected
* Slackware 14.2 / Python 3.7.7 / X11: fails
* MacOS / Python 3.7.3/Cocoa?: fails

### Actual behavior:

When using ``arcade.key(key, modifiers)``, my RHEL 8 (python 3.7.7) computer successfully detects MOD_SHIFT (for example). 

Running the same code on my Slackware system, or on a MacOS system, the modifiers are not detected, and a workaround using numerical sums of keys pressed is required (although the numbers I get from different systems don't seem to match).

As both Slackware and RHEL 8 are on the same version of Python, I assume this is external to that. Could it possibly be X11 vs Wayland??

### Expected behavior:

Modifiers should be parsed.

### Steps to reproduce/example code:

```
#!/usr/bin/env python3
import arcade
SCREEN_WIDTH = 150
SCREEN_HEIGHT = 150

class MyGame(arcade.Window):
    def __init__(self, width, height, title):
        # Call the parent class and set up the window
        super().__init__(width, height, title)

    def setup(self):
        True
        
    def on_key_press(self, key, modifiers):
        if key == arcade.key.RIGHT:
            print('a key press') # this always works
        elif key == arcade.key.LEFT and modifiers:
            print('modifier detected') # always works, but prints different ints across systems
        elif key == arcade.key.LEFT and modifiers == arcade.key.MOD_SHIFT:
            print(modifiers) # works on RHEL 8, fails on Slackware or MacOS

def main():
    """ Main method """
    game = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, "foo")
    game.setup()
    arcade.run()

if __name__ == "__main__":
    main()
```

### What should be added/changed?

I'm still looking for a consistent pattern of when the code works and when it fails, so I have no suggested fix yet.

**Comment by pvcraven** [comment]
This might be good to pass up to the pyglet projects. For Arcade, this is just a pass-through to the base class. The Pyglet people might have more wisdom to share.

**Comment by notklaatu** [comment]
Great, thanks for the info. I'll file a bug with Pyglet.
