### ISSUE TITLE
Full Screen Display

### ISSUE THREAD

**Issue by OversizedYans** [pvcraven/arcade#686]
### Actual behavior: 

Toggling full screen opens on a different display, which can't be changed, regardless of the display that the window is on.

### Expected behavior: 

Should full screen on display that the window is on, or at least be able to select/change it.

### Steps to reproduce/example code:

Using this code and hitting 'F' on the keyboard:

```
def on_key_press(self, key, modifiers):
        if key == arcade.key.F:
            # User hits s. Flip between full and not full screen.
            self.set_fullscreen(not self.fullscreen)

            # Instead of a one-to-one mapping, stretch/squash window to match the
            # constants. This does NOT respect aspect ratio. You'd need to
            # do a bit of math for that.
            self.set_viewport(0, SCREEN_WIDTH, 0, SCREEN_HEIGHT)

```

**Comment by pvcraven** [comment]
Currently in the shader experimental branch. Needs testing as I don't have a dual-monitor setup at home.

**Comment by pvcraven** [comment]
This should be in the current release. Closing. Notify if it isn't working.
