### ISSUE TITLE
Player sometimes goes into the ground when using the pymunk physics engine

### ISSUE THREAD

**Issue by maxymoo22** [pvcraven/arcade#689]
If you look in the pymunk platformer tutorial, at the top of the page where there is the demo image you can see that the player sometimes goes into the ground before popping back out when you jump. I tried this myself with similar code and it's even more visible. The player goes up to 10 pixels into the ground when landing, and it looks really bad. Is this a problem with pymunk and/or arcade?

**Comment by maxymoo22** [comment]
This also sometimes stops the player from moving side to side for some reason

**Comment by pvcraven** [comment]
For the first issue, when things "sink" into other objects, that's how the 2D physics library works. See:
http://www.pymunk.org/en/latest/pymunk.html#pymunk.Space.collision_bias.

The second is kind of unrelated I think? 
http://www.pymunk.org/en/latest/pymunk.html#pymunk.Poly.__init__

If you bevel edges, it kind of leaves things 'sunk' in, so some additional hitbox work would be required. I just try to keep the lower part of my sprite rounded to avoid this.

I'll try and add explanation on the tutorial. Thanks for the feedback.

**Comment by 1-max-1** [comment]
` `

**Comment by pvcraven** [comment]
Updated tutorial to hopefully explain this better.
