### ISSUE TITLE
Line of Sight function not working...

### ISSUE THREAD

**Issue by Nikhil-K-Singh** [pvcraven/arcade#690]
while attempting the example in 
https://arcade.academy/examples/line_of_sight.html#line-of-sight

below output is obtained on running the command:
python -m arcade.examples.line_of_sight

![image](https://user-images.githubusercontent.com/37348724/82151926-cadb7200-987b-11ea-9ab9-b08ff5abe176.png)

when i attempted to try the code by writing the same in a new file below statement was printed but no error.. kindly suggest.

**module 'arcade' has no attribute 'has_line_of_sight'**

**Comment by pvcraven** [comment]
Install the 2.4a version instead of 2.3.15

**Comment by pvcraven** [comment]
See #657.
