### ISSUE TITLE
Is It possible to render without opening window?

### ISSUE THREAD

**Issue by 678098** [pvcraven/arcade#692]
This might be related to #298 
So for example user can't open window for rendering in existing env (in docker, for example) but want to render anyway somehow, to the image or to some buffer.
Is It possible with arcade?

**Comment by pvcraven** [comment]
I haven't tried it. With the new frame buffers in the upcoming 2.4 it might be possible. However, if it is, it would still require OpenGL 3.3. Not sure if docker instances support that.

**Comment by einarf** [comment]
There are work being done in pygelt to support headless rendering with EGL. That should work in docker. I'm guessing this is more of a pyglet issue than arcade.
https://github.com/pyglet/pyglet/issues/51

**Comment by CourchesneA** [comment]
It is possible to use pyglet applications without a screen (i.e. on docker) using a virtual display, i.e. with xvfb. However, until pyglet supports EGL, it is not possible to use hardware acceleration this way.

**Comment by pvcraven** [comment]
So, I think the short answer is that it isn't possible right now.
