### ISSUE TITLE
How to detect collisions between a sprite and a non-sprite like a circle or a rectangle or between two non-sprites. I have tried to add a circle to the sprite list but it's not working. 

### ISSUE THREAD

**Issue by AyusDas** [pvcraven/arcade#696]

**Comment by pvcraven** [comment]
I don't have an easy answer for that one. 

There's nothing built-in for circle collision, although that is easy, just check distance. 

If things are a polygon you can use (are_polygons_intersecting)[https://arcade.academy/arcade.html#arcade.are_polygons_intersecting]. Each sprite has a hitbox you can use for the polygon, and you can feed your drawing shape points in for the other one.

**Comment by AyusDas** [comment]
Ok I will try. Thanks.
