### ISSUE TITLE
on_show called twice on start up

### ISSUE THREAD

**Issue by eruvanos** [pvcraven/arcade#701]
## Bug Report
`View.on_show` called twice on start up, because the view is pushed as a handler to the window and receives the `on_show` event which has the same name like the `Window.on_show` callback.

### Actual behavior:
`on_show` is called twice

1.  window.show_view(view)
2. arcade.run() -> view receives on_show event of the window

### Expected behavior:
on_show called once

### Steps to reproduce/example code:
```
import arcade

class MyView(arcade.View):
    def on_show(self):
        print('on_show')

if __name__ == '__main__':
    window = arcade.Window(width=300, height=300)
    view = MyView()
    window.show_view(view)
    arcade.run()
```

### Suggestion 
Rename `View.on_show` to prevent that it is picked up as callback.

**Comment by pvcraven** [comment]
Adjusting ``view_screens_minimal``, I see that ``on_show`` does get called twice at first. It doesn't get called twice when switching views, just on start-up. Not sure I want to fix by adding a backwards-breaking change though and rename ``on_show``.

**Comment by eruvanos** [comment]
Get the argument against a rename, what about explicitly removing the handler?

**Comment by eruvanos** [comment]
Ok, removing the handler did not work, don't get the problem.

Alternative:
```
self.push_handlers(
            **{
                et: getattr(new_view, et, None)
                for et in self.event_types
                if et != 'on_show' and hasattr(new_view, et)
            }
        )
```
instead of 
```
        self.push_handlers(self._current_view)
```

**Comment by eruvanos** [comment]
My main concern is, that I still have no solution for removing the UIManager as handler on view change.

Two options I see:

1. View gets build in UIManager, so `Window.show_view()` can handle push and remove the UIManager
2. View gets a new callback which we will trigger in `Window.show_view()` maybe `on_hide_view()`

The second solution sounds great, but we have to make sure, that `View.on_show()` and `View.on_hide_view()` are called always at the right point in time and especially not twice.

**Comment by eruvanos** [comment]
@pvcraven will work on this on the weekend, so that supporting multiple views with UIManager is not a problem.

Let me no if you have some thoughts to the messages above.
