### ISSUE TITLE
Documentation Request: Simple Platformer Tutorial has wrong parameter keyword(s)

### ISSUE THREAD

**Issue by nartr1** [pvcraven/arcade#702]
Within the "Simple Platformer tutorial" on the wiki, line 47 of the final code has the keyword "flipped_horizontally" while the api code now has "flipped". Changing it from "flipped_horizontally" to "mirrored" now works as expected. The same goes for the "process_layer" calls on lines 241, 255, and 260 which contain the "use_spatial_hashing", while the api does not include the keyword. I have included the full code with the updated calls.
[full_platformer.txt](https://github.com/pvcraven/arcade/files/4762142/full_platformer.txt)

**Comment by pvcraven** [comment]
I believe you are running version 2.3.15 of Arcade. That example is, I think, updated to 2.4 branch which has some backwards-breaking name changes. Unfortunately I'm not set up to keep multiple versions of the documentation right now.

**Comment by pvcraven** [comment]
Closed with release of 2.4
