### ISSUE TITLE
Problem 12.2.2 on learn.arcade.academy gives no indication of how to reset to printing on a new line

### ISSUE THREAD

**Issue by SuperPupperDoggo** [pvcraven/arcade#710]
##Documentation request #710 :

### What documentation needs to change? 

The learn.arcade.academy course

### Where is it located?
[Chapter 12](http://learn.arcade.academy/chapters/12_advanced_looping/advanced_looping.html#problem-2)
### What is wrong with it? How can it be improved?

It doesn't give any indication anywhere for how to tell the program to go to the next line. This one took me a while. Most people will probably be stuck with this(or at least I was):

```python
for i in range(1,11):
    print("*",end=" ")

for i in range(1,6):
    print("*",end=" ")

for i in range(1,21):
    print("*",end=" ")
```

Which prints this:
`* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * `

When I looked at the answer after giving up, I noticed you needed empty print statements, which wasn't mentioned on the page

*Again apologies for the edits, markdown seems to not like the way I'm using asterisks

**Comment by pvcraven** [comment]
Thanks! Updated: https://learn.arcade.academy/chapters/12_advanced_looping/advanced_looping.html#moving-to-the-next-line
