### ISSUE TITLE
Missing highlighting in chapter 17

### ISSUE THREAD

**Issue by SuperPupperDoggo** [pvcraven/arcade#713]
### What documentation needs to change? 
The [learn.arcade.academy](learn.arcade.academy) course
### Where is it located?

[Chapter 17](http://learn.arcade.academy/chapters/16_user_control/user_control.html#id3) on [learn.arcade.academy](learn.arcade.academy)

### What is wrong with it? How can it be improved?

The addition of the `MOVEMENT_SPEED` variable as well as the addition of the `update` method and `change_x` and `change_y` attributes in the `Ball` class were not highlighted despite being either mentioned in or necessary for the highlighted code to work.

**Comment by pvcraven** [comment]
Updated, thanks. May take 24 hours for cloud hosting to catch up with the change.
