### ISSUE TITLE
The example code in Listing 2, Chapter 20 still has the logic to delete the coins.

### ISSUE THREAD

**Issue by SuperPupperDoggo** [pvcraven/arcade#720]
### What documentation needs to change? 
[learn.arcade.academy](learn.arcade.academy) course
### Where is it located?
[Chapter 20](http://learn.arcade.academy/chapters/19_moving_sprites/moving_sprites.html)
### What is wrong with it? How can it be improved?
The example code at [_Listing 2_](http://learn.arcade.academy/chapters/19_moving_sprites/moving_sprites.html#id4) still has the logic to delete the coins.
Edit: Same for all the examples after it

**Comment by pvcraven** [comment]
Thanks for the report. Fixed. Can take up to 24 hrs for cloud to update.
