### ISSUE TITLE
Bad modiffiers-key mapping for on_key_press on some machines

### ISSUE THREAD

**Issue by akapkotel** [pvcraven/arcade#735]
### Actual behavior:
Modiffier value passed to on_key_press on Acer Inspire 3 laptop equals to 16 when NO modiffier-keys are pressed, instead of 0.
So, for egzample, when L-CTRL is pressed on Acer Inspire 3 laptop, modiffier code passed to on_key_press method equals 18 instead of 2.

### Expected behavior:
According to arcade.key it should pass value 2, and with no key pressed should be 0.

### Steps to reproduce/example code:
Run in debug-mode arcade on Acer Inspire 3 laptop (I do not know if on other laptops the bug appears) and press L-CTRL to see what is passed as 'modiffiers' to on_key_press.

### What should be added/changed?
Key-bindings should work with different key-mappings.

### What would it help with?
Key-bindings would work properly on every machine

**Comment by xlatb** [comment]
According to [this](https://arcade.academy/arcade.key.html), the value 16 signifies Numlock, so it's probably by design. Numlock and Capslock are considered modifiers.

Probably your best bet is to bitwise-and the keys you care about into the modifier flags value before testing it.

**Comment by pvcraven** [comment]
I'll update docs to clarify.
