### ISSUE TITLE
Allow quick running via -m

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#84]
Two interesting cases. First, was someone able to get arcade installed correctly? Sure would be nice to have a very easy way to find out. For example, ``python3 -m arcade.hello`` which might launch a window, do a test for Pillow and avbin etc.

Next, people want to have a nice first experience. Instead of making them cut-and-paste an example then run it, same as the above: ``python -m arcade.demo``.

Some things to think about:

- Do we want just one sexy demo, several, or all of the examples?
- Perhaps we should make a different thing to install, e.g. ``pip install arcade_gamepack`` which has a dependency on arcade, and they can do ``python3 -m arcade_gamepack.asteroid``. If we did that, we might want to look at a ``pyarcade`` github organization for various repos.

**Comment by pvcraven** [comment]
We could move the "examples" directory to "arcade/examples" enabling ``python -m arcade.examples.myexample``. After this, we'd need to:

* Update documentation, so that it points to the new folder
* Update conf file to include the image and sound folder contents

A demo would be nice, not sure what that would entail. But making the examples easier to run would be a nice improvement,

**Comment by pauleveritt** [comment]
Agreed, once we decide how we’d like it, I can do it. I’d still like *one* that was shorter than arcade.examples.myexample, if that’s ok. Just a hello world self check kind of thing.

—Paul

**Comment by pvcraven** [comment]
Sounds great. An easy-to-use demo / hello world in the base package also sounds great.

**Comment by pauleveritt** [comment]
@pvcraven When you say "Update conf file to include the image and sound folder contents", I think you mean that we need to add a MANIFEST.in and add include_package_data=True in setup.py, correct?

**Comment by pvcraven** [comment]
Probably. Not sure off-hand what is needed, but that sounds right. Basically whatever is required so that the users have the sounds and images, otherwise it the demos won't be nearly as exciting.

**Comment by pvcraven** [comment]
I have no idea how to manage the images and sound resources properly.

**Comment by pvcraven** [comment]
Putting this in the `__init__()` sets the working directory to where the file is:

        file_path = os.path.dirname(os.path.abspath(__file__))
        os.chdir(file_path)

But we aren't distributing the images and sounds with the package yet.

**Comment by pauleveritt** [comment]
When I first worked on this ticket, I reached the same conclusion. Arcade needs something like what Pyramid has: a path specification language in strings for resolving static assets. But that’s for distribution of games, which is a long way off.

I vote we drop this for now.

—Paul

**Comment by pvcraven** [comment]
I think I'm getting a workable solution for this.

**Comment by pvcraven** [comment]
Done and closed with release 1.2.3.
