### ISSUE TITLE
Alternative to global pyglet window subclass as the unit of programming

### ISSUE THREAD

**Issue by pauleveritt** [pvcraven/arcade#85]
For non-trivial coding, arcade provides a base class at application.Window. IMO, there are a few flaws with this:

- We have to have a global variable "window"
- People code to the pyglet API directly, and we can't mediate that relationship
- Some odd things pop up, e.g. making users call start_render() because we're not mediating

My previous alternative used decorators and thus, raised the conceptual complexity dramatically. Here's a different proposal.

First, leave the function-oriented approach as-is, and portray it as aimed at interactive use by people that barely know Python.

Next, have an arcade.Game base class which doesn't subclass from pyglet.window.Window. Instead, its constructor creates an instance of arcade.Window, which subclasses from pyglet.window.Window.

The most important part: arcade.Game passes its ``self`` into arcade.Window. Then, arcade.Window implements all the ``animate`` etc. methods, doing some work and calling ``self.app.animate`` which the user implements.

Here is an example of a game written that way: https://github.com/pauleveritt/asteroids/blob/master/gameng.py

It has no user-visible additional complexity from the current approach. It has a couple of things that are complexity reduction (e.g. no start_render).

Here are the base classes: https://github.com/pauleveritt/asteroids/blob/master/arcadeng.py

Very simple, no advanced concepts. The magic is on line 50, where self is passed into the window.

With this in place, arcade users don't have to learn pyglet. For example, I changed pyglet's ``animate`` method to ``update_model`` to better reflect the intention of our programming model. Later, I'd like to make batching transparent to use: https://github.com/pauleveritt/asteroids/blob/master/experiment_pyglet_sprites.py

This example is 4x faster than the non-batching, but it is complex to use. We might be able to come up with a simplified programming model, once we mediate the relationship.

I'd also like to make our base class into an abstract base class, so it will be clear what they have to implement.

Finally, I realize this is a colossal change. If this was approved, I'd have to do all the work to make the change. I'm not asking others to do it.

**Comment by pvcraven** [comment]
First glance, this seems good. I think I'd need to see a bit more details.

Random thoughts:

- I'm not sure "animate" or "update_model" are the best method names. I'm over-thinking it, but I know from teaching that names mean a lot, and I'd like to pick a name that makes it obvious to a new programmer what that method is supposed to do.
- We need to make sure we can support OpenGL batch drawing. I think that's more of a SpriteList type of thing, but it makes a big difference in speed. Even right now it is slower than ideal from the way it is coded. All the objects are moved off an origin point before drawing.

**Comment by pauleveritt** [comment]
@pvcraven By "more details" do you mean, fill in more of the arcade scope/features that I left out? Or, for the current scope, more explanation of what it is doing?

I agree on the names. In fact, one attraction of this direction (mediating pyglet) is that we can rename. In fact^2, for batching, we might split ``update`` into multiple plug points.

On the second bullet, I'm following the experiments done by my friend. He's actually gone a lot further...he re-did pyglet Sprite and has and example with some crazy, crazy performance. Want me to take this prototype further by bringing some of that in?

**Comment by pvcraven** [comment]
This seems worth opening a second branch to work on. I'd like to make sure examples like drawing_primitives.py would work without much in the way of changes.

**Comment by pauleveritt** [comment]
I made a branch (unpushed) and found that doing labels in batches, even backwards compatible without batches without re-implementing the existing drawing code, was easy.

Sprites are a different story. Pyglet sprites have an option to let you create a sprite in a batch. Since you don't use pyglet sprites, I have to understand what that option does, then learn about how you are using vertex buffer objects, textures, etc...then apply the pyglet sprite batching code.

**Comment by pvcraven** [comment]
Without the vertex buttering and drawing things as a batch, Arcade is slower than Pygame. A lot slower. It took me by surprise.

**Comment by pauleveritt** [comment]
I’m still hoping to get batching worked into your implementation, but it could require that I learn a lot about pyglet, plus the parts you’ve added. I can push my branch, but its not much to show on batching…though it does show the “Game API” that I’m hoping to propose.

—Paul

**Comment by pvcraven** [comment]
Cool, eager to look at it.

Paul Vincent Craven

**Comment by pvcraven** [comment]
This:

`game = Game()`

requires students know what an object is, a function, variables, and a host of other things that the first example does not requires. Unless the instructor is willing to just toss in boiler-plate code and not fully explain how it works. Not looking to go there. Whole reason I moved from Java while instructing.

**Comment by pauleveritt** [comment]
That’s true, but importing a module, calling a function, and having a stupendous amount of Python and C called is also happening. However, I concede the point.

—Paul

**Comment by pauleveritt** [comment]
@pvcraven Let's close this ticket and delete the branch. If we think about changes in both the initial experience and the large-scale experience, it will likely be different.

**Comment by pvcraven** [comment]
Ok
