### ISSUE TITLE
draw_texture_rectangle needs to call gl.glDisable(gl.GL_TEXTURE_2D)

### ISSUE THREAD

**Issue by jittat** [pvcraven/arcade#90]
I used Sprite together with drawing primitives, and it turned out that after sprites were drawn I could not use any other drawing functions, e.g., `arcade.draw_rectangle_filled`.

I looked up the code and noticed that Sprite uses `draw_texture_rectangle`, and inside that function, `gl.glEnable(gl.GL_TEXTURE_2D)` is called.  I suspected that it is the reason, so I called `gl.glDisable(gl.GL_TEXTURE_2D)` inside my `on_draw` after all sprites are drawn.   And it seems everything works again.

The following is short testing code (you need some sprite image).  You can try turning glDisable on and off by commenting out that line.

```
import arcade
from models import World
import pyglet.gl as gl

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400

class MyWindow(arcade.Window):
    def __init__(self, width, height):
        super().__init__(width, height)
 
        arcade.set_background_color(arcade.color.GRAY)

        self.dot_sprite = arcade.Sprite('images/dot.png')
        self.dot_sprite.set_position(100, 100)
        
        
    def on_draw(self):
        arcade.start_render()
        self.dot_sprite.draw()

        # ----- test by turning this on and off
        gl.glDisable(gl.GL_TEXTURE_2D)
        
        arcade.draw_rectangle_outline(200,200,50,50,arcade.color.BLACK)
        arcade.draw_rectangle_filled(300,200,50,50,arcade.color.BLACK)

 
if __name__ == '__main__':
    window = MyWindow(SCREEN_WIDTH, SCREEN_HEIGHT)
    arcade.run()
```

If this is a real issue, I will write a fix and will come back with a pull request.

**Comment by pvcraven** [comment]
The disable was in the 'draw multiple sprites code', but not the 'draw a single sprite' code. Should be fixed with the code I just checked in. Seems ok when I run the example code above anyway.

**Comment by jittat** [comment]
Thanks a lot for a very quick response.  :+1:
