### ISSUE TITLE
Can't add a sprite to the sprite list

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#91]
Issue reported to me via the web. Seems like .append isn't working in the sprite list:

/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5   File "/PycharmProjects/Project.py", line 95, in __init__
    self.all_sprites_list.append(self.player)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/arcade/sprite.py", line 517, in append
    item._register_sprite_list(self)
TypeError: _register_sprite_list() missing 1 required positional argument: 'new_list'

**Comment by pvcraven** [comment]
Not sure what is tripping that error. This works:

```
import arcade

class Test:
    def __init__(self):
        self.all_sprites_list = arcade.SpriteList()
        self.player = arcade.Sprite()
        self.all_sprites_list.append(self.player)

t = Test()
```

**Comment by pauleveritt** [comment]
Is this report from someone running from a PyPI install or from master?

If you’d like, send the person to me and I’ll follow up.

—Paul

**Comment by pvcraven** [comment]
He's supposed to send more code. We'll see if I can get enough to reproduce the error.

**Comment by pvcraven** [comment]
Closing, no new info. Don't have enough to reproduce.
