### ISSUE TITLE
Ex Code "def main()" Inconsistency

### ISSUE THREAD

**Issue by Nick-the-BinaryTree** [pvcraven/arcade#92]
Hi, I just discovered this library and am currently running through the examples.

I noticed some of the tutorial code snippets create a window class through a traditional Python "def main()", whereas others do not.

For instance, this uses the main method: https://github.com/pvcraven/arcade/blob/master/examples/sprite_bullets.py

And the next example does not:
https://github.com/pvcraven/arcade/blob/master/examples/sprite_bullets_aimed.py

I wasn't sure if there was any reason for this.

P.S. This is a very cool project!

**Comment by pauleveritt** [comment]
I'll try to give an answer for @pvcraven -- I think he uses this code as part of teaching to people that don't know Python. As such, he sometimes doesn't want to make people think of that idiom.

**Comment by pvcraven** [comment]
I have a few code examples that don't use main() for exactly the reason @pauleveritt mentions. Mostly examples that can be easily understood without having learned functions. In the case of this example, it looks like it should use a main method. I'll go ahead and update the example.
