### ISSUE TITLE
Tile outlines showing in ramp

### ISSUE THREAD

**Issue by Nick-the-BinaryTree** [pvcraven/arcade#95]
As you can see faintly in this screenshot, an outline of the full square tile is still showing, despite having followed the tutorial to make it a ramp, here: https://pythonhosted.org/arcade/examples/sprite_ramps.html

![ScreenShot](http://i.imgur.com/SsX8Elh.png)
(Running on Windows x64)

Here is a link to the project:
https://github.com/Nick-the-BinaryTree/ArcadeVehicleTest

Also, is it possible to give a more in-depth explanation of these lines? I don't quite understand how the negative coordinates work.

```
if item == 4:
   wall.points = ((-wall.width // 2, wall.height // 2),
                          (wall.width // 2, -wall.height // 2),
                          (-wall.width // 2, -wall.height // 2))

elif item == 5:
    wall.points = ((-wall.width // 2, -wall.height // 2),
                           (wall.width // 2, -wall.height // 2),
                           (wall.width // 2, wall.height // 2))
```

Thanks!

**Comment by pvcraven** [comment]
Keep tile sizes in powers of two, (64, 128, 256, etc. with a scaling of 1 or 0.5, or similar) and make sure tiles don't line up fractionally. Integer values only.This seems to get rid of most edge problems.
