### ISSUE TITLE
Created Background Music Test App

### ISSUE THREAD

**Issue by Nick-the-BinaryTree** [pvcraven/arcade#96]
Hi, I created a small app that plays looped background music using Pyglet, as per this to-do list:
https://pythonhosted.org/arcade/examples/examples_to_do.html

Here's a link to the project:
https://github.com/Nick-the-BinaryTree/ArcadeBackgroundMusic

I couldn't figure out how to schedule repeated calling of a "update_sound" function inside the Window class, so, embarrassingly, I just put a call inside the on_draw function (If someone could explain how to do that more elegantly, I would be very appreciative).

If you would like me to make a pull request adding "set_background_music" and "stop_background_music" commands to the library, let me know; although it might be a bit more tricky.

Thanks for reading!

**Comment by pvcraven** [comment]
Seems like there should be a way of firing an event after the music is done. Might be support in Pyglet that we need to add in. Something like:

http://programarcadegames.com/python_examples/f.php?file=background_music.py

Polling to see if the music is done should be a last-resort.

**Comment by kevinrandell** [comment]
How do you install the sound library on the virtual environment for Mac OSX?

**Comment by pvcraven** [comment]
Merge into #184. Just handle with one issue so I don't get as sad.
