### ISSUE TITLE
website: search broken

### ISSUE THREAD

**Issue by danboid** [pvcraven/arcade#99]
Is this the right place to report bugs with the arcade website? Please move it if not.

The Arcade docs search at https://pythonhosted.org/arcade/search.html doesn't work for me. If  search for a term, I see a "Searching..." message and then... nothing. I suppose I can always just use another search engine instead.

Maybe its server is under too much load?

**Comment by pauleveritt** [comment]
I think it’s fine to report it here. Looks like the Sphinx JS for search is busted:

Uncaught TypeError: Cannot read property 'length' of undefined
    at displayNextItem (searchtools.js:543)
    at Object.query (searchtools.js:574)
    at Object.setIndex (searchtools.js:362)
    at <anonymous>:1:8
    at p (jquery.js:2)
    at Function.globalEval (jquery.js:2)
    at text script (jquery.js:4)
    at Nb (jquery.js:4)
    at A (jquery.js:4)
    at XMLHttpRequest.<anonymous> (jquery.js:4)

—Paul

**Comment by pvcraven** [comment]
I've never tried this before. Looks like you have to have an app server set up on the back-end. It wasn't obvious to me how it should be set up.

**Comment by pauleveritt** [comment]
Actually Sphinx has a system where it builds a JS file with a bunch of inverted index information. Search then loads that file and performs the logic client-side.

—Paul

**Comment by pvcraven** [comment]
Is this still an issue? I've tried searching on http://arcade.academy (now that pythonhosted is no longer hosting) and search seems to work ok.

**Comment by pvcraven** [comment]
Closed, implemented in 1.2.2 which is now deployed on PyPi.
